"""Shared helpers for backend parity tests."""

from __future__ import annotations

import asyncio
import json
import os
import secrets
from collections.abc import AsyncIterator
from pathlib import Path
from typing import Any

import pytest

from docker_agent.agent import BackendQueryParams, create_backend
from docker_agent.loop_context import PlanReadyPayload
from docker_agent.services.api.types import (
    MessageStopEvent,
    TextDeltaEvent,
    ToolUseDeltaEvent,
    ToolUseStartEvent,
    ToolUseStopEvent,
)
from docker_agent.state.state_store import StateStore
from docker_agent.types.events import LoopEvent
from docker_agent.types.message import Message
from docker_agent.types.permissions import (
    AlwaysAllowInSession,
    Approve,
    Deny,
    PermissionResponse,
    TypedConfirmValue,
)
from tests.mocks.mock_compose_runner import MockComposeRunner
from tests.mocks.mock_docker_engine import MockDockerEngine


def _nanoid() -> str:
    return secrets.token_urlsafe(16)


def fake_provider(calls: list[list[Any]]):
    call_idx = 0

    class _Provider:
        name = "fake"

        async def stream(self, _params: object) -> AsyncIterator[Any]:
            nonlocal call_idx
            events = calls[call_idx] if call_idx < len(calls) else []
            call_idx += 1
            for ev in events:
                yield ev

    return _Provider()


def tool_use_call(tool_name: str, input_data: object) -> list[Any]:
    return [
        ToolUseStartEvent(id="t1", name=tool_name),
        ToolUseDeltaEvent(id="t1", args_partial_json=json.dumps(input_data)),
        ToolUseStopEvent(id="t1"),
        MessageStopEvent(stop_reason="tool_use"),
    ]


def text_done(text: str = "done") -> list[Any]:
    return [
        TextDeltaEvent(text=text),
        MessageStopEvent(stop_reason="end_turn"),
    ]


class _ParityLoopContext:
    """Concrete LoopContext for parity tests with mock Docker/Compose."""

    def __init__(
        self,
        *,
        cwd: str,
        state_store: StateStore,
        docker_engine: MockDockerEngine,
        compose_runner: MockComposeRunner,
        abort_signal: asyncio.Event,
        request_permission: Any,
        request_confirm: Any,
        request_typed_confirm: Any,
        request_secrets_input: Any,
        allow_set: set[str],
    ) -> None:
        self.cwd = cwd
        self.state_store = state_store
        self.docker_engine = docker_engine
        self.compose_runner = compose_runner
        self.abort_signal = abort_signal
        self.image_validator = None
        self.session_id = None
        self.health_check_deadline_ms = None
        self.request_permission = request_permission
        self.request_confirm = request_confirm
        self.request_typed_confirm = request_typed_confirm
        self.request_secrets_input = request_secrets_input
        self.allow_set = allow_set
        self.logger = None


@pytest.fixture
def tmp_project(tmp_path: Path) -> Path:
    (tmp_path / "project-policies.yaml").write_text("project: {}", encoding="utf-8")
    return tmp_path


@pytest.fixture
def make_context(tmp_project: Path):
    def _make(**opts: Any) -> _ParityLoopContext:
        emit = opts.get("emit")

        async def request_permission(tool: str, input_data: object) -> PermissionResponse:
            if emit is not None:
                emit(
                    {
                        "type": "permission_request",
                        "id": _nanoid(),
                        "tool": tool,
                        "input": input_data,
                    }
                )
            return opts.get("permission_response", Approve())

        async def request_confirm(plan: PlanReadyPayload | dict[str, Any]) -> PermissionResponse:
            if not isinstance(plan, PlanReadyPayload):
                plan = PlanReadyPayload.model_validate(plan)
            if emit is not None:
                payload: dict[str, Any] = {
                    "type": "plan_ready",
                    "id": _nanoid(),
                    "composeYaml": plan.compose_yaml,
                    "diff": plan.diff.model_dump(by_alias=True),
                }
                if plan.auto_generated_secrets is not None:
                    payload["autoGeneratedSecrets"] = plan.auto_generated_secrets
                if plan.config_files is not None:
                    payload["configFiles"] = plan.config_files
                emit(payload)
            return opts.get("confirm_response", Approve())

        async def request_typed_confirm(phrase: str, reason: str) -> PermissionResponse:
            if emit is not None:
                emit(
                    {
                        "type": "typed_confirm_request",
                        "id": _nanoid(),
                        "phrase": phrase,
                        "reason": reason,
                    }
                )
            return opts.get("typed_confirm_response", TypedConfirmValue(value="x"))

        async def request_secrets_input(
            _service: str, _keys: list[str], _reason: str
        ) -> PermissionResponse:
            return opts.get("secrets_response", Deny())

        return _ParityLoopContext(
            cwd=str(tmp_project),
            state_store=opts.get("state_store") or StateStore(str(tmp_project)),
            docker_engine=MockDockerEngine(),
            compose_runner=opts.get("compose_runner") or MockComposeRunner(str(tmp_project)),
            abort_signal=asyncio.Event(),
            request_permission=opts.get("request_permission") or request_permission,
            request_confirm=opts.get("request_confirm") or request_confirm,
            request_typed_confirm=opts.get("request_typed_confirm") or request_typed_confirm,
            request_secrets_input=opts.get("request_secrets_input") or request_secrets_input,
            allow_set=opts.get("allow_set", set()),
        )

    return _make


@pytest.fixture
def run_backend():
    async def _run(
        *,
        backend_name: str,
        messages: list[Message],
        ctx: _ParityLoopContext,
        provider: Any,
    ) -> list[LoopEvent]:
        prev = os.environ.get("DOCKER_AGENT_BACKEND")
        os.environ["DOCKER_AGENT_BACKEND"] = backend_name
        try:
            backend = create_backend()
            events: list[LoopEvent] = []
            async for ev in backend.query(
                BackendQueryParams(messages=messages, ctx=ctx, provider=provider)
            ):
                events.append(ev)
            return events
        finally:
            if prev is None:
                os.environ.pop("DOCKER_AGENT_BACKEND", None)
            else:
                os.environ["DOCKER_AGENT_BACKEND"] = prev

    return _run


def output_field(output: object, field: str) -> object:
    if isinstance(output, dict):
        return output.get(field)
    return getattr(output, field, None)


__all__ = [
    "AlwaysAllowInSession",
    "Approve",
    "Deny",
    "TypedConfirmValue",
    "fake_provider",
    "output_field",
    "text_done",
    "tool_use_call",
]