"""Plan generation phases: secret staging and Compose assembly."""

from __future__ import annotations

import contextlib
import copy
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Literal, cast

from docker_mcp_server.state.drift_detector import detect_drift
from docker_mcp_server.state.env_file import merge_env
from docker_mcp_server.state.secret_redactor import looks_like_credential_uri, should_redact
from docker_mcp_server.tools.base import ToolContext
from docker_mcp_server.tools.shared.compose_builder import (
    PlanInput,
    build_stack_definition,
    stack_to_yaml,
)
from docker_mcp_server.tools.shared.config_files import (
    StagedConfigFile,
    detect_missing_config_files,
    stage_config_files,
)
from docker_mcp_server.tools.shared.db_app_wiring import wire_dependent_app_secrets
from docker_mcp_server.tools.shared.required_secrets import (
    find_required_secrets,
    is_weak_secret_value,
)
from docker_mcp_server.tools.shared.secret_staging import SecretFileStager, StagedSecretFile
from docker_mcp_server.tools.shared.spec_schemas import DraftServiceSpec, StackDraft
from docker_mcp_server.tools.shared.translator import PreparedStack
from docker_mcp_server.tools.shared.yaml_round_trip import validate_yaml_round_trip
from docker_mcp_server.tools.validate_spec import SpecIssue
from docker_mcp_server.types.stack import EnvFileSource, ServiceSpec, StackDiff


@dataclass
class AutoGeneratedSecret:
    service: str
    keys: list[str]


@dataclass
class SecretStageOk:
    ok: Literal[True] = True
    services: dict[str, DraftServiceSpec] = field(default_factory=dict)
    staged_files: list[StagedConfigFile] = field(default_factory=list)
    auto_generated_secrets: list[AutoGeneratedSecret] = field(default_factory=list)
    generated_env_file_sources: dict[str, EnvFileSource] = field(default_factory=dict)
    stager: SecretFileStager | None = None


@dataclass
class SecretStageBlocked:
    ok: Literal[False] = False
    reason: str = ""
    issues: list[SpecIssue] | None = None
    missing_by_service: dict[str, list[str]] | None = None
    missing_files: list[str] | None = None


SecretStageResult = SecretStageOk | SecretStageBlocked


@dataclass
class AssembleOk:
    ok: Literal[True] = True
    compose_yaml: str = ""
    scale_overrides: dict[str, int] = field(default_factory=dict)
    diff: StackDiff | None = None


@dataclass
class AssembleBlocked:
    ok: Literal[False] = False
    reason: str = ""
    error: str | None = None


AssembleResult = AssembleOk | AssembleBlocked


def _generated_env_file_path(cwd: str, stack_name: str, service_name: str) -> Path:
    return Path(cwd) / ".docker-agent" / "secrets" / f"{stack_name}-{service_name}.env"


def _generated_env_file_ref(stack_name: str, service_name: str) -> str:
    return f"./.docker-agent/secrets/{stack_name}-{service_name}.env"


def _resolve_env_file(cwd: str, ref_path: str) -> Path:
    return Path(cwd).resolve() / ref_path


def _to_service_spec(spec: DraftServiceSpec) -> ServiceSpec:
    return spec


def stage_stack_secrets(
    input: StackDraft,
    prepared: PreparedStack,
    ctx: ToolContext,
) -> SecretStageResult:
    """Stage config files, migrate inline secrets, and auto-generate env files."""
    services = copy.deepcopy(prepared.services)
    staged_config = stage_config_files(ctx.cwd, services, input.config_files)
    if not staged_config.get("ok"):
        return SecretStageBlocked(
            reason="invalid_spec",
            issues=[
                SpecIssue(
                    code="invalid_config_path",
                    path="configFiles",
                    message=str(staged_config.get("error", "unknown")),
                )
            ],
        )
    staged_files = cast(list[StagedConfigFile], staged_config.get("staged", []))

    auto_generated_secrets: list[AutoGeneratedSecret] = []
    generated_env_file_sources: dict[str, EnvFileSource] = {}
    missing_by_service: dict[str, list[str]] = {}
    stager = SecretFileStager()

    for service_name, spec in services.items():
        moved_secrets: dict[str, str] = {}
        inline_environment = dict(spec.environment or {})
        remaining_inline_environment: dict[str, str] = {}

        for key, value in inline_environment.items():
            if should_redact(key) or looks_like_credential_uri(value):
                moved_secrets[key] = value
            else:
                remaining_inline_environment[key] = value

        service_env_file = list(spec.env_file or [])

        if moved_secrets:
            target_path = _generated_env_file_path(ctx.cwd, input.stack_name, service_name)
            stager.stage(
                target_path,
                {**stager.read(target_path), **moved_secrets},
            )
            target_ref = _generated_env_file_ref(input.stack_name, service_name)
            if target_ref not in service_env_file:
                service_env_file.append(target_ref)
            existing = generated_env_file_sources.get(service_name)
            added_keys = [
                *(existing.added_keys if existing and existing.added_keys else []),
                *moved_secrets.keys(),
            ]
            generated_env_file_sources[service_name] = EnvFileSource(
                generated=True,
                path=target_ref,
                added_keys=added_keys,
            )
            auto_generated_secrets.append(
                AutoGeneratedSecret(service=service_name, keys=list(moved_secrets.keys()))
            )

        rule = find_required_secrets(spec.image)
        if rule and rule.required:
            from_env_file: dict[str, str] = {}
            for env_file_path in service_env_file:
                from_env_file.update(stager.read(_resolve_env_file(ctx.cwd, env_file_path)))

            merged = merge_env(from_env_file, remaining_inline_environment)
            missing = [key for key in rule.required if merged.get(key) is None]
            weak = [
                key
                for key in rule.required
                if merged.get(key) is not None
                and isinstance(merged[key], str)
                and is_weak_secret_value(key, merged[key], rule)
            ]
            replaceable = [*missing, *weak]
            safe_keys = [
                key for key in replaceable if rule.safe_defaults.get(key) is not None
            ]
            unsafe_keys = [
                key for key in replaceable if rule.safe_defaults.get(key) is None
            ]

            if unsafe_keys:
                missing_by_service[service_name] = unsafe_keys

            if safe_keys:
                target_path = _generated_env_file_path(ctx.cwd, input.stack_name, service_name)
                target_values = dict(stager.read(target_path))
                for key in safe_keys:
                    make_default = rule.safe_defaults.get(key)
                    if make_default is not None:
                        target_values[key] = make_default()
                stager.stage(target_path, target_values)
                target_ref = _generated_env_file_ref(input.stack_name, service_name)
                if target_ref not in service_env_file:
                    service_env_file.append(target_ref)
                existing = generated_env_file_sources.get(service_name)
                added_keys = [
                    *(existing.added_keys if existing and existing.added_keys else []),
                    *safe_keys,
                ]
                generated_env_file_sources[service_name] = EnvFileSource(
                    generated=True,
                    path=target_ref,
                    added_keys=added_keys,
                )
                auto_generated_secrets.append(
                    AutoGeneratedSecret(service=service_name, keys=safe_keys)
                )

        next_spec = spec.model_copy(
            update={
                "environment": (
                    remaining_inline_environment if remaining_inline_environment else None
                ),
                "env_file": service_env_file or None,
            }
        )
        services[service_name] = next_spec

    wired_secrets = wire_dependent_app_secrets(
        ctx.cwd,
        input.stack_name,
        services,
        generated_env_file_sources,
        stager,
    )
    for service_name, keys in wired_secrets:
        auto_generated_secrets.append(AutoGeneratedSecret(service=service_name, keys=keys))

    if missing_by_service:
        return SecretStageBlocked(
            reason="missing_required_env",
            missing_by_service=missing_by_service,
        )

    missing_config = detect_missing_config_files(
        services,
        {f.path for f in staged_files},
        ctx.cwd,
    )
    if missing_config:
        return SecretStageBlocked(
            reason="missing_config_file",
            missing_files=[item["path"] for item in missing_config],
        )

    return SecretStageOk(
        services=services,
        staged_files=staged_files,
        auto_generated_secrets=auto_generated_secrets,
        generated_env_file_sources=generated_env_file_sources,
        stager=stager,
    )


async def assemble_compose(
    input: StackDraft,
    prepared: PreparedStack,
    services: dict[str, DraftServiceSpec],
    generated_env_file_sources: dict[str, EnvFileSource],
    ctx: ToolContext,
) -> AssembleResult:
    """Build Compose YAML, validate round-trip, and detect drift."""
    previous = ctx.state_store.read(input.stack_name)
    stack_services = {name: _to_service_spec(spec) for name, spec in services.items()}
    plan_input = PlanInput(
        stack_name=input.stack_name,
        intent=input.intent,
        services=stack_services,
        networks=prepared.networks,
        volumes=prepared.volumes,
    )
    build = build_stack_definition(
        plan_input,
        previous,
        ctx.provider_name,
        ctx.model or f"{ctx.provider_name}-default",
    )
    definition = build.definition
    definition.x_infra_agent.env_file_sources = {
        **definition.x_infra_agent.env_file_sources,
        **generated_env_file_sources,
    }
    compose_yaml = stack_to_yaml(definition)
    yaml_check = validate_yaml_round_trip(compose_yaml)
    if not yaml_check.ok:
        return AssembleBlocked(
            reason="invalid_yaml",
            error=yaml_check.error or "unknown YAML error",
        )

    diff = StackDiff.model_validate(
        {
            "stackName": input.stack_name,
            "status": "missing",
            "serviceDiffs": [],
        }
    )
    with contextlib.suppress(Exception):
        diff = await detect_drift(
            input.stack_name, ctx.state_store, ctx.docker_engine, ctx.cwd
        )

    return AssembleOk(
        compose_yaml=compose_yaml,
        scale_overrides=build.scale_overrides,
        diff=diff,
    )


__all__ = [
    "AssembleBlocked",
    "AssembleOk",
    "AssembleResult",
    "AutoGeneratedSecret",
    "SecretStageBlocked",
    "SecretStageOk",
    "SecretStageResult",
    "assemble_compose",
    "stage_stack_secrets",
]
