"""Plugin-neutral loop context passed to agent backends."""

from __future__ import annotations

import asyncio
from typing import Any, Protocol, runtime_checkable

from pydantic import BaseModel, ConfigDict, Field

from docker_agent.state.logger import StructuredLogger


class ActionReviewArtifact(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    kind: str
    label: str
    content: Any
    language: str | None = None


class ActionReviewPayload(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    pending_action_id: str = Field(alias="pendingActionId")
    tool: str
    title: str
    summary: str
    artifacts: list[ActionReviewArtifact] = Field(default_factory=list)
    warnings: list[str] = Field(default_factory=list)
    secrets: list[dict[str, Any]] = Field(default_factory=list)
    config_files: list[dict[str, Any]] = Field(default_factory=list, alias="configFiles")

    @classmethod
    def from_pending_action_display(
        cls,
        *,
        pending_action_id: str,
        tool: str,
        display: dict[str, Any],
    ) -> ActionReviewPayload:
        artifacts = list(display.get("artifacts") or [])
        title = str(display.get("title") or f"Review {tool}")
        summary = str(
            display.get("summary") or display.get("reason") or "Review action before commit."
        )
        return cls.model_validate(
            {
                "pendingActionId": pending_action_id,
                "tool": tool,
                "title": title,
                "summary": summary,
                "artifacts": artifacts,
                "warnings": display.get("warnings") or [],
                "secrets": display.get("secrets")
                or display.get("auto_generated_secrets")
                or display.get("autoGeneratedSecrets")
                or [],
                "configFiles": display.get("config_files") or display.get("configFiles") or [],
            }
        )


@runtime_checkable
class LoopContext(Protocol):
    """Backend context plus user-interaction callbacks used by the engine loop."""

    cwd: str
    abort_signal: asyncio.Event
    session_id: str | None
    provider_name: str
    model: str | None
    request_permission: Any
    request_confirm: Any
    request_typed_confirm: Any
    request_secrets_input: Any
    allow_set: set[str]
    logger: StructuredLogger | None


__all__ = ["ActionReviewArtifact", "ActionReviewPayload", "LoopContext"]
