import { Box } from "ink";
import type React from "react";
import { useMemo, useRef, useState } from "react";
import type { PermissionResponse } from "src/types/permissions";
import type { StackDiff } from "src/types/stack";
import { QueryEngine, type QueryEngineDeps } from "../QueryEngine";
import { Footer } from "../components/Footer";
import { Header } from "../components/Header";
import { MessageList, type UIMessage } from "../components/MessageList";
import { PermissionDialog } from "../components/PermissionDialog";
import { PlanPreview } from "../components/PlanPreview";
import { PromptInput } from "../components/PromptInput";
import { SecretsInputDialog } from "../components/SecretsInputDialog";
import { TypedConfirmDialog } from "../components/TypedConfirmDialog";

type Pending =
  | { kind: "permission"; id: string; tool: string; input: unknown }
  | {
      kind: "confirm";
      id: string;
      composeYaml: string;
      diff: StackDiff;
      autoGeneratedSecrets?: Array<{ service: string; keys: string[] }>;
    }
  | { kind: "typed"; id: string; phrase: string; reason: string }
  | { kind: "secrets"; id: string; service: string; keys: string[]; reason: string };

export function REPL({
  deps,
}: { deps: QueryEngineDeps & { providerName: string } }): React.ReactElement {
  const engine = useMemo(() => new QueryEngine(deps), [deps]);
  const [messages, setMessages] = useState<UIMessage[]>([]);
  const [pending, setPending] = useState<Pending | null>(null);
  const [streaming, setStreaming] = useState(false);
  const [usage, setUsage] = useState({ inputTokens: 0, outputTokens: 0 });
  const nextKey = useRef(0);
  const mk = (): number => nextKey.current++;

  const handleSubmit = async (input: string) => {
    setMessages((m) => [...m, { key: mk(), role: "user", text: input }]);
    setStreaming(true);
    try {
      for await (const ev of engine.query(input)) {
        switch (ev.type) {
          case "assistant_text":
            setMessages((m) => {
              const last = m[m.length - 1];
              if (last && last.role === "assistant" && last.text !== undefined) {
                return [...m.slice(0, -1), { ...last, text: last.text + ev.delta }];
              }
              return [...m, { key: mk(), role: "assistant", text: ev.delta }];
            });
            break;
          case "tool_call":
            setMessages((m) => [
              ...m,
              { key: mk(), role: "tool", name: ev.name, status: "running" },
            ]);
            break;
          case "tool_progress":
            setMessages((m) => {
              const copy = [...m];
              for (let i = copy.length - 1; i >= 0; i--) {
                const item = copy[i];
                if (item && item.role === "tool" && item.name === ev.msg) {
                  copy[i] = { ...item, status: "running" as const };
                  break;
                }
              }
              return copy;
            });
            break;
          case "tool_result":
            setMessages((m) => {
              const copy = [...m];
              for (let i = copy.length - 1; i >= 0; i--) {
                const item = copy[i];
                if (item && item.role === "tool" && item.name === ev.name) {
                  copy[i] = { ...item, status: "done" as const };
                  break;
                }
              }
              return copy;
            });
            break;
          case "plan_ready":
            setPending({
              kind: "confirm",
              id: ev.id,
              composeYaml: ev.composeYaml,
              diff: ev.diff,
              ...(ev.autoGeneratedSecrets ? { autoGeneratedSecrets: ev.autoGeneratedSecrets } : {}),
            });
            break;
          case "permission_request":
            setPending({ kind: "permission", id: ev.id, tool: ev.tool, input: ev.input });
            break;
          case "typed_confirm_request":
            setPending({ kind: "typed", id: ev.id, phrase: ev.phrase, reason: ev.reason });
            break;
          case "secrets_input_request":
            setPending({
              kind: "secrets",
              id: ev.id,
              service: ev.service,
              keys: ev.keys,
              reason: ev.reason,
            });
            break;
          case "usage":
            setUsage((u) => ({
              inputTokens: u.inputTokens + ev.inputTokens,
              outputTokens: u.outputTokens + ev.outputTokens,
            }));
            break;
          case "error":
            setMessages((m) => [...m, { key: mk(), role: "error", text: ev.error.message }]);
            break;
        }
      }
    } finally {
      setStreaming(false);
    }
  };

  const onAnswer = (answer: PermissionResponse) => {
    if (!pending) return;
    engine.respondTo(pending.id, answer);
    setPending(null);
  };

  return (
    <Box flexDirection="column">
      <Header provider={deps.providerName} />
      <MessageList messages={messages} />
      {pending?.kind === "permission" && (
        <PermissionDialog tool={pending.tool} input={pending.input} onAnswer={onAnswer} />
      )}
      {pending?.kind === "confirm" && (
        <PlanPreview
          composeYaml={pending.composeYaml}
          diff={pending.diff}
          {...(pending.autoGeneratedSecrets
            ? { autoGeneratedSecrets: pending.autoGeneratedSecrets }
            : {})}
          onAnswer={onAnswer}
        />
      )}
      {pending?.kind === "typed" && (
        <TypedConfirmDialog phrase={pending.phrase} reason={pending.reason} onAnswer={onAnswer} />
      )}
      {pending?.kind === "secrets" && (
        <SecretsInputDialog
          service={pending.service}
          keys={pending.keys}
          reason={pending.reason}
          onAnswer={onAnswer}
        />
      )}
      {!pending && !streaming && <PromptInput onSubmit={handleSubmit} />}
      <Footer usage={usage} />
    </Box>
  );
}
