import fs from "node:fs";
import path from "node:path";
import { Box, Text, useApp, useStdout } from "ink";
import type React from "react";
import { useEffect, useMemo, useRef, useState } from "react";
import type { PermissionResponse } from "src/types/permissions";
import type { StackDiff } from "src/types/stack";
import { QueryEngine, type QueryEngineDeps } from "../QueryEngine";
import { ApiKeyInputDialog } from "../components/ApiKeyInputDialog";
import { Footer } from "../components/Footer";
import { LogPane } from "../components/LogPane";
import { MessageList, type UIMessage } from "../components/MessageList";
import { ModelPickerDialog } from "../components/ModelPickerDialog";
import { PermissionDialog } from "../components/PermissionDialog";
import { PlanPreview } from "../components/PlanPreview";
import { PromptInput } from "../components/PromptInput";
import { SecretsInputDialog } from "../components/SecretsInputDialog";
import { ThinkingIndicator } from "../components/ThinkingIndicator";
import { TypedConfirmDialog } from "../components/TypedConfirmDialog";
import { WelcomeBanner } from "../components/WelcomeBanner";
import { isValidProvider } from "../config";
import {
  type ApiKeyProviderName,
  type ApiKeyStore,
  apiKeyEnvVar,
  createApiKeyStore,
  describeApiKeyStatus,
  isApiKeyProviderName,
} from "../secrets/apiKeyStore";
import { resolveProviderForRequest } from "../services/api";
import { formatSlashHelp } from "../slashCommands";
import type { SessionStore } from "../state/SessionStore";
import { scrubLine } from "../state/secretRedactor";
import { collectSecretKeys } from "../tools/shared/secretKeys";

type Pending =
  | { kind: "permission"; id: string; tool: string; input: unknown }
  | {
      kind: "confirm";
      id: string;
      composeYaml: string;
      diff: StackDiff;
      autoGeneratedSecrets?: Array<{ service: string; keys: string[] }>;
    }
  | { kind: "typed"; id: string; phrase: string; reason: string }
  | { kind: "secrets"; id: string; service: string; keys: string[]; reason: string }
  | { kind: "apiKey"; provider: ApiKeyProviderName }
  | { kind: "modelPicker"; models: string[] };

const DESTRUCTIVE_TOOLS = new Set(["apply_stack", "destroy_stack", "destroy_all_stacks"]);

const COMPACT_WELCOME_MAX_ROWS = 16;
const COMPACT_WELCOME_MAX_COLUMNS = 84;

function safeFrameWidth(stdout: NodeJS.WriteStream): number {
  return Math.max(1, (stdout.columns || 80) - 1);
}

function useSafeFrameWidth(): number {
  const { stdout } = useStdout();
  const [width, setWidth] = useState(() => safeFrameWidth(stdout));

  useEffect(() => {
    const onResize = () => setWidth(safeFrameWidth(stdout));
    stdout.on("resize", onResize);
    return () => {
      stdout.off("resize", onResize);
    };
  }, [stdout]);

  return width;
}

export function REPL({
  deps,
  version,
  resumedRecord,
  showBanner = true,
}: {
  deps: QueryEngineDeps & { providerName: string; yes?: boolean; apiKeyStore?: ApiKeyStore };
  version: string;
  resumedRecord?: import("../state/SessionStore").SessionRecord;
  showBanner?: boolean;
}): React.ReactElement {
  const engine = useMemo(() => new QueryEngine(deps), [deps]);
  const apiKeyStore = useMemo(() => deps.apiKeyStore ?? createApiKeyStore(), [deps.apiKeyStore]);
  const [messages, setMessages] = useState<UIMessage[]>(() => {
    if (resumedRecord) {
      engine.loadSession(resumedRecord);
      return engine.getMessages().map((m, i) => {
        if (m.role === "user") {
          return { key: i, role: "user" as const, text: m.content };
        }
        if (m.role === "assistant") {
          const text = m.content
            .filter((b) => b.type === "text")
            .map((b) => (b as { type: "text"; text: string }).text)
            .join("");
          return { key: i, role: "assistant" as const, text };
        }
        return { key: i, role: "assistant" as const, text: "(tool result)" };
      });
    }
    return [];
  });
  const [pending, setPending] = useState<Pending | null>(null);
  const [streaming, setStreaming] = useState(false);
  const [activeLogPane, setActiveLogPane] = useState<{
    stackName: string;
    service?: string;
    controller: AbortController;
  } | null>(null);
  const [logLines, setLogLines] = useState<string[]>([]);
  const logControllerRef = useRef<AbortController | null>(null);

  const LOG_RING_MAX = 200;

  const stopLogPane = () => {
    logControllerRef.current?.abort();
    logControllerRef.current = null;
    setActiveLogPane(null);
    setLogLines([]);
  };

  const startLogPane = (stackName: string, service?: string) => {
    const yamlPath = path.join(deps.cwd, ".docker-agent", "stacks", `${stackName}.yaml`);
    if (!fs.existsSync(yamlPath)) {
      setMessages((m) => [
        ...m,
        { key: mk(), role: "user", text: `/logs ${stackName}${service ? ` ${service}` : ""}` },
        { key: mk(), role: "error", text: `stack ${stackName} not found` },
      ]);
      return;
    }
    // Abort any prior pane first.
    logControllerRef.current?.abort();
    const controller = new AbortController();
    logControllerRef.current = controller;
    setLogLines([]);
    setActiveLogPane({ stackName, controller, ...(service ? { service } : {}) });

    const secretKeys = collectSecretKeys(stackName, {
      cwd: deps.cwd,
      stateStore: deps.stateStore,
    });
    const bound = deps.composeRunner.forStack(stackName, yamlPath);
    void (async () => {
      try {
        for await (const chunk of bound.logs({
          follow: true,
          tailLines: 50,
          signal: controller.signal,
          ...(service ? { service } : {}),
        })) {
          if (controller.signal.aborted) break;
          const scrubbed = scrubLine(chunk, secretKeys);
          setLogLines((prev) => {
            const next = [...prev, scrubbed];
            return next.length > LOG_RING_MAX ? next.slice(-LOG_RING_MAX) : next;
          });
        }
      } catch {
        /* generator ended or aborted — pane lifecycle handles cleanup */
      }
    })();
  };

  const [activeProviderName, setActiveProviderName] = useState(deps.providerName);
  const [activeModel, setActiveModel] = useState<string | undefined>(deps.model);
  const { exit } = useApp();
  const frameWidth = useSafeFrameWidth();
  const { stdout } = useStdout();
  const compact =
    (stdout.rows || 24) <= COMPACT_WELCOME_MAX_ROWS || frameWidth < COMPACT_WELCOME_MAX_COLUMNS;
  const nextKey = useRef(0);
  const mk = (): number => nextKey.current++;

  useEffect(() => {
    return () => {
      logControllerRef.current?.abort();
      logControllerRef.current = null;
    };
  }, []);

  const handleSubmit = async (input: string) => {
    let targetPrompt = input.trim();
    const lowered = targetPrompt.toLowerCase();
    if (lowered === "exit" || lowered === "quit") {
      // Defer exit by three setImmediate ticks so that any in-flight
      // waitUntilExit() promises are created before the Ink instance resolves.
      // Three levels are needed because the test sets up waitUntilExit() after
      // two setImmediate ticks following the input submission.
      setImmediate(() => setImmediate(() => setImmediate(() => exit())));
      return;
    }
    if (targetPrompt.startsWith("/")) {
      const parts = targetPrompt.split(/\s+/);
      const cmd = parts[0]?.toLowerCase();
      const arg = parts.slice(1).join(" ");

      if (cmd === "/quit" || cmd === "/exit") {
        stopLogPane();
        exit();
        return;
      }
      if (cmd === "/clear") {
        stopLogPane();
        engine.reset();
        setMessages([]);
        nextKey.current = 0;
        return;
      }
      if (cmd === "/help") {
        setMessages((m) => [
          ...m,
          { key: mk(), role: "user", text: input },
          { key: mk(), role: "assistant", text: formatSlashHelp() },
        ]);
        return;
      }
      if (cmd === "/provider") {
        const providerName = arg.toLowerCase();
        if (!providerName) {
          setMessages((m) => [
            ...m,
            { key: mk(), role: "user", text: input },
            { key: mk(), role: "error", text: "Missing provider. Example: /provider openai" },
          ]);
          return;
        }
        if (!isValidProvider(providerName)) {
          setMessages((m) => [
            ...m,
            { key: mk(), role: "user", text: input },
            {
              key: mk(),
              role: "error",
              text: "Unknown provider. Use one of: gemini, openai, ollama",
            },
          ]);
          return;
        }
        engine.provider = resolveProviderForRequest(providerName, process.env, { apiKeyStore });
        setActiveProviderName(providerName);
        setMessages((m) => [
          ...m,
          { key: mk(), role: "user", text: input },
          { key: mk(), role: "assistant", text: `Provider set to ${providerName}` },
        ]);
        return;
      }
      if (cmd === "/apikey") {
        const subcommand = parts[1]?.toLowerCase();
        const providerArg = parts[2]?.toLowerCase();
        if (subcommand === "status") {
          const statuses = await describeApiKeyStatus(apiKeyStore, process.env);
          setMessages((m) => [
            ...m,
            { key: mk(), role: "user", text: input },
            {
              key: mk(),
              role: "assistant",
              text: statuses
                .map((status) =>
                  status.source
                    ? `${status.provider}: ${status.state} (${status.source})`
                    : `${status.provider}: ${status.state}`,
                )
                .join("\n"),
            },
          ]);
          return;
        }
        if (subcommand === "set") {
          if (!isApiKeyProviderName(providerArg)) {
            setMessages((m) => [
              ...m,
              { key: mk(), role: "user", text: input },
              { key: mk(), role: "error", text: "Use /apikey set openai or /apikey set gemini" },
            ]);
            return;
          }
          setMessages((m) => [...m, { key: mk(), role: "user", text: input }]);
          setPending({ kind: "apiKey", provider: providerArg });
          return;
        }
        setMessages((m) => [
          ...m,
          { key: mk(), role: "user", text: input },
          { key: mk(), role: "error", text: "Use /apikey set <provider> or /apikey status" },
        ]);
        return;
      }
      if (cmd === "/models") {
        const provider = engine.provider;
        if (typeof provider.listModels !== "function") {
          setMessages((m) => [
            ...m,
            { key: mk(), role: "user", text: input },
            {
              key: mk(),
              role: "error",
              text: `Provider "${activeProviderName}" cannot list models. Use /model <id> to set one manually.`,
            },
          ]);
          return;
        }
        setMessages((m) => [...m, { key: mk(), role: "user", text: input }]);
        try {
          const models = await provider.listModels();
          if (models.length === 0) {
            setMessages((m) => [
              ...m,
              {
                key: mk(),
                role: "assistant",
                text: `No models found for ${activeProviderName}. For Ollama, pull one with: ollama pull <model>`,
              },
            ]);
            return;
          }
          setPending({ kind: "modelPicker", models });
        } catch (err) {
          setMessages((m) => [
            ...m,
            {
              key: mk(),
              role: "error",
              text: `Failed to list models: ${(err as Error).message}`,
            },
          ]);
        }
        return;
      }
      if (cmd === "/model") {
        const model = arg.trim();
        if (!model) {
          setMessages((m) => [
            ...m,
            { key: mk(), role: "user", text: input },
            { key: mk(), role: "error", text: "Missing model id. Example: /model gpt-4.1-mini" },
          ]);
          return;
        }
        engine.model = model;
        setActiveModel(model);
        setMessages((m) => [
          ...m,
          { key: mk(), role: "user", text: input },
          { key: mk(), role: "assistant", text: `Model set to ${model}` },
        ]);
        return;
      }

      if (cmd === "/resume") {
        const sessionStore = deps.sessionStore;
        if (!sessionStore) {
          setMessages((m) => [
            ...m,
            { key: mk(), role: "user", text: input },
            { key: mk(), role: "error", text: "Session persistence not configured." },
          ]);
          return;
        }
        const sessionId = arg.trim() || undefined;
        const rec = sessionId ? sessionStore.read(sessionId) : sessionStore.latest();
        if (!rec) {
          setMessages((m) => [
            ...m,
            { key: mk(), role: "user", text: input },
            {
              key: mk(),
              role: "error",
              text: sessionId
                ? `Session "${sessionId}" not found.`
                : "No previous session found to resume.",
            },
          ]);
          return;
        }
        engine.loadSession(rec);
        const repainted = engine.getMessages().map((m, i) => {
          if (m.role === "user") {
            return { key: i, role: "user" as const, text: m.content };
          }
          if (m.role === "assistant") {
            const text = m.content
              .filter((b) => b.type === "text")
              .map((b) => (b as { type: "text"; text: string }).text)
              .join("");
            return { key: i, role: "assistant" as const, text };
          }
          return { key: i, role: "assistant" as const, text: "(tool result)" };
        });
        nextKey.current = repainted.length;
        setMessages(repainted);
        return;
      }

      if (cmd === "/logs") {
        const logParts = arg.split(/\s+/).filter(Boolean);
        const stackName = logParts[0];
        const service = logParts[1];
        if (!stackName) {
          setMessages((m) => [
            ...m,
            { key: mk(), role: "user", text: input },
            { key: mk(), role: "error", text: "Usage: /logs <stack> [service]" },
          ]);
          return;
        }
        startLogPane(stackName, service);
        return;
      }

      if (cmd === "/stacks") targetPrompt = "Show the current stacks as a table";
      else if (cmd === "/status") targetPrompt = `Show status and drift for stack ${arg}`;
      else if (cmd === "/destroy" && arg === "all") targetPrompt = "Destroy all stacks";
      else if (cmd === "/destroy") targetPrompt = `Destroy stack ${arg}`;
      else if (cmd === "/secrets" && parts[1] === "list")
        targetPrompt = `List secret keys for stack ${parts.slice(2).join(" ")}`;
      else if (cmd === "/secrets" && parts[1] === "rotate") {
        const subparts = parts.slice(2);
        targetPrompt = `Rotate secrets for service ${subparts[1]} in stack ${subparts[0]}`;
      } else if (cmd === "/yaml") targetPrompt = `Show the YAML config file for stack ${arg}`;
    }

    setMessages((m) => [...m, { key: mk(), role: "user", text: input }]);
    setStreaming(true);
    try {
      for await (const ev of engine.query(targetPrompt)) {
        switch (ev.type) {
          case "assistant_text":
            setMessages((m) => {
              const last = m[m.length - 1];
              if (last && last.role === "assistant" && last.text !== undefined) {
                return [...m.slice(0, -1), { ...last, text: last.text + ev.delta }];
              }
              return [...m, { key: mk(), role: "assistant", text: ev.delta }];
            });
            break;
          case "tool_call":
            setMessages((m) => [
              ...m,
              { key: mk(), role: "tool", name: ev.name, status: "running" },
            ]);
            break;
          case "tool_progress":
            setMessages((m) => {
              const copy = [...m];
              for (let i = copy.length - 1; i >= 0; i--) {
                const item = copy[i];
                if (item && item.role === "tool") {
                  copy[i] = { ...item, text: ev.msg };
                  break;
                }
              }
              return copy;
            });
            break;
          case "tool_result":
            setMessages((m) => {
              const copy = [...m];
              for (let i = copy.length - 1; i >= 0; i--) {
                const item = copy[i];
                if (item && item.role === "tool" && item.name === ev.name) {
                  copy[i] = { ...item, status: "done" as const };
                  break;
                }
              }
              return copy;
            });
            break;
          case "plan_ready":
            setPending({
              kind: "confirm",
              id: ev.id,
              composeYaml: ev.composeYaml,
              diff: ev.diff,
              ...(ev.autoGeneratedSecrets ? { autoGeneratedSecrets: ev.autoGeneratedSecrets } : {}),
            });
            break;
          case "permission_request":
            if (deps.yes && !DESTRUCTIVE_TOOLS.has(ev.tool)) {
              engine.respondTo(ev.id, { kind: "approve" });
            } else {
              setPending({ kind: "permission", id: ev.id, tool: ev.tool, input: ev.input });
            }
            break;
          case "typed_confirm_request":
            setPending({ kind: "typed", id: ev.id, phrase: ev.phrase, reason: ev.reason });
            break;
          case "secrets_input_request":
            setPending({
              kind: "secrets",
              id: ev.id,
              service: ev.service,
              keys: ev.keys,
              reason: ev.reason,
            });
            break;
          case "usage":
            break;
          case "error":
            setMessages((m) => [...m, { key: mk(), role: "error", text: ev.error.message }]);
            break;
          case "rollback_started":
            setMessages((m) => [
              ...m,
              {
                key: mk(),
                role: "assistant" as const,
                text: `⚠️ Rolling back stack "${ev.stackName}" (reason: ${ev.reason})${ev.detail ? ` — ${ev.detail}` : ""}`,
              },
            ]);
            break;
          case "rollback_result":
            setMessages((m) => [
              ...m,
              {
                key: mk(),
                role: ev.ok ? ("assistant" as const) : ("error" as const),
                text: ev.ok
                  ? `✅ Rollback succeeded for stack "${ev.stackName}" (restored: ${ev.restored})`
                  : `❌ Rollback FAILED for stack "${ev.stackName}" (restored: ${ev.restored})${ev.detail ? ` — ${ev.detail}` : ""}. Manual intervention may be required.`,
              },
            ]);
            break;
        }
      }
    } finally {
      setStreaming(false);
    }
  };

  const onAnswer = (answer: PermissionResponse) => {
    if (!pending || pending.kind === "apiKey" || pending.kind === "modelPicker") return;
    engine.respondTo(pending.id, answer);
    setPending(null);
  };

  const onModelPicked = (model: string) => {
    engine.model = model;
    setActiveModel(model);
    setPending(null);
    setMessages((m) => [...m, { key: mk(), role: "assistant", text: `Model set to ${model}` }]);
  };

  const onApiKeySubmit = async (provider: ApiKeyProviderName, value: string) => {
    try {
      await apiKeyStore.set(provider, value);
      process.env[apiKeyEnvVar(provider)] = value;
      setPending(null);
      setMessages((m) => [
        ...m,
        { key: mk(), role: "assistant", text: `API key saved for ${provider}` },
      ]);
    } catch (err) {
      setPending(null);
      setMessages((m) => [...m, { key: mk(), role: "error", text: (err as Error).message }]);
    }
  };

  return (
    <Box flexDirection="column" width={frameWidth} overflowX="hidden">
      {showBanner && (
        <WelcomeBanner
          version={version}
          provider={activeProviderName}
          model={activeModel}
          compact={compact}
        />
      )}
      {!showBanner && (
        <Box paddingX={1} overflowX="hidden">
          <Text>
            docker-agent | provider: <Text color="yellow">{activeProviderName}</Text>
            {" | "}
            model: <Text color="yellow">{activeModel ?? "default"}</Text>
          </Text>
        </Box>
      )}
      <MessageList messages={messages} />
      {pending?.kind === "permission" && (
        <PermissionDialog tool={pending.tool} input={pending.input} onAnswer={onAnswer} />
      )}
      {pending?.kind === "confirm" && (
        <PlanPreview
          composeYaml={pending.composeYaml}
          diff={pending.diff}
          {...(pending.autoGeneratedSecrets
            ? { autoGeneratedSecrets: pending.autoGeneratedSecrets }
            : {})}
          onAnswer={onAnswer}
        />
      )}
      {pending?.kind === "typed" && (
        <TypedConfirmDialog phrase={pending.phrase} reason={pending.reason} onAnswer={onAnswer} />
      )}
      {pending?.kind === "secrets" && (
        <SecretsInputDialog
          service={pending.service}
          keys={pending.keys}
          reason={pending.reason}
          onAnswer={onAnswer}
        />
      )}
      {pending?.kind === "apiKey" && (
        <ApiKeyInputDialog
          provider={pending.provider}
          envVarName={apiKeyEnvVar(pending.provider)}
          onSubmit={(value) => void onApiKeySubmit(pending.provider, value)}
          onCancel={() => {
            setPending(null);
            setMessages((m) => [
              ...m,
              { key: mk(), role: "assistant", text: "API key setup cancelled" },
            ]);
          }}
        />
      )}
      {pending?.kind === "modelPicker" && (
        <ModelPickerDialog
          models={pending.models}
          {...(activeModel ? { current: activeModel } : {})}
          onSelect={onModelPicked}
          onCancel={() => {
            setPending(null);
            setMessages((m) => [
              ...m,
              { key: mk(), role: "assistant", text: "Model selection cancelled" },
            ]);
          }}
        />
      )}
      {activeLogPane && (
        <LogPane
          stackName={activeLogPane.stackName}
          {...(activeLogPane.service ? { service: activeLogPane.service } : {})}
          lines={logLines}
          onClose={stopLogPane}
        />
      )}
      {!pending && streaming && !activeLogPane && (
        <Box paddingLeft={1} marginY={1}>
          <ThinkingIndicator />
        </Box>
      )}
      {!pending && !streaming && !activeLogPane && <PromptInput onSubmit={handleSubmit} />}
      <Footer usage={engine.totalUsage} />
    </Box>
  );
}
