import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { QueryEngine } from "src/QueryEngine";
import type { ProviderEvent } from "src/services/api/types";
import { StateStore } from "src/state/StateStore";
import { afterEach, beforeEach, describe, expect, test } from "vitest";
import { MockComposeRunner } from "../mocks/mockComposeRunner";
import { MockDockerEngine } from "../mocks/mockDockerEngine";

function fakeProvider(eventLists: ProviderEvent[][]) {
  let callIndex = 0;
  return {
    name: "fake",
    stream: async function* () {
      const events = eventLists[callIndex] ?? [];
      callIndex += 1;
      for (const ev of events) yield ev;
    },
  };
}

function planStackEvents(input: object): ProviderEvent[] {
  return [
    { type: "tool_use_start", id: "t1", name: "plan_stack" },
    { type: "tool_use_delta", id: "t1", argsPartialJson: JSON.stringify(input) },
    { type: "tool_use_stop", id: "t1" },
    { type: "message_stop", stopReason: "tool_use" },
  ];
}

function makeEngine({
  tmp,
  stateStore,
  composeRunner,
  providerEvents,
}: {
  tmp: string;
  stateStore: StateStore;
  composeRunner: MockComposeRunner;
  providerEvents: ProviderEvent[][];
}) {
  return new QueryEngine({
    cwd: tmp,
    stateStore,
    dockerEngine: new MockDockerEngine() as never,
    composeRunner: composeRunner as never,
    provider: fakeProvider(providerEvents),
    healthCheckDeadlineMs: 0, // avoid health-gate polling in integration tests
  });
}

function seedStack(store: StateStore, name: string) {
  store.write(name, {
    "x-docker-agent": {
      name,
      createdAt: "x",
      lastApplied: "x",
      intent: "x",
      provider: "x",
      generatedBy: "x",
      envFileSources: {},
    },
    services: { web: { image: "nginx:1.27" } },
  });
}

describe("deploy flow", () => {
  let tmp: string;
  let stateStore: StateStore;
  let composeRunner: MockComposeRunner;

  beforeEach(() => {
    tmp = fs.mkdtempSync(path.join(os.tmpdir(), "plan-flow-"));
    fs.mkdirSync(path.join(tmp, ".docker-agent"), { recursive: true });
    fs.writeFileSync(path.join(tmp, ".docker-agent", "policies.yaml"), "project: {}");
    stateStore = new StateStore(path.join(tmp, ".docker-agent"));
    composeRunner = new MockComposeRunner(tmp);
  });

  afterEach(() => {
    fs.rmSync(tmp, { recursive: true, force: true });
  });

  test("nginx: plan -> confirm -> apply via ComposeRunner.forStack", async () => {
    // Configure bound runners to return healthy service rows so the health gate passes
    composeRunner.onBoundRunnerCreated = (runner) => {
      runner.setRunningServices(["web"]);
    };

    const engine = makeEngine({
      tmp,
      stateStore,
      composeRunner,
      providerEvents: [
        planStackEvents({
          stackName: "nginx",
          intent: "tao nginx",
          services: [
            {
              name: "web",
              kind: "custom",
              image: "nginx:1.27-alpine",
              exposure: "public",
              hostPort: 8080,
              containerPort: 80,
            },
          ],
        }),
      ],
    });
    const events: string[] = [];

    for await (const ev of engine.query("tao nginx")) {
      events.push(ev.type);
      if (ev.type === "plan_ready") engine.respondTo(ev.id, { kind: "approve" });
    }

    expect(events).toContain("plan_ready");
    expect(composeRunner.forStackCalls[0]).toMatchObject({
      stackName: "nginx",
      yamlPath: path.join(tmp, "docker-stacks", "nginx.yaml"),
    });
    expect(composeRunner.boundFor("nginx").cwd).toBe(tmp);
    expect(composeRunner.boundFor("nginx").upCalls[0]).toEqual({ detach: true });
    expect(fs.existsSync(path.join(tmp, "docker-stacks", "nginx.yaml"))).toBe(true);
  });

  test("postgres: auto-generates POSTGRES_PASSWORD secret file", async () => {
    const engine = makeEngine({
      tmp,
      stateStore,
      composeRunner,
      providerEvents: [
        planStackEvents({
          stackName: "pg",
          intent: "tao postgres",
          services: [
            {
              name: "db",
              kind: "catalog",
              catalogId: "postgresql:16",
            },
          ],
        }),
      ],
    });
    let autoGeneratedSecrets: Array<{ service: string; keys: string[] }> = [];

    for await (const ev of engine.query("tao postgres")) {
      if (ev.type === "plan_ready") {
        autoGeneratedSecrets = ev.autoGeneratedSecrets ?? [];
        engine.respondTo(ev.id, { kind: "approve" });
      }
    }

    expect(autoGeneratedSecrets).toContainEqual({
      service: "db",
      keys: ["POSTGRES_PASSWORD"],
    });
    const secretFile = fs.readFileSync(
      path.join(tmp, ".docker-agent", "secrets", "pg-db.env"),
      "utf-8",
    );
    expect(secretFile).toMatch(/POSTGRES_PASSWORD=.{20,}/);
  });

  test("destroy_all aborts without typed DESTROY ALL", async () => {
    seedStack(stateStore, "webapp");
    const stackPath = path.join(tmp, "docker-stacks", "webapp.yaml");
    const engine = makeEngine({
      tmp,
      stateStore,
      composeRunner,
      providerEvents: [
        [
          { type: "tool_use_start", id: "t1", name: "destroy_all_stacks" },
          { type: "tool_use_delta", id: "t1", argsPartialJson: "{}" },
          { type: "tool_use_stop", id: "t1" },
          { type: "message_stop", stopReason: "tool_use" },
        ],
        [{ type: "message_stop", stopReason: "end_turn" }],
      ],
    });
    let typedConfirmRequested = false;

    for await (const ev of engine.query("destroy all")) {
      if (ev.type === "typed_confirm_request") {
        typedConfirmRequested = true;
        engine.respondTo(ev.id, { kind: "typed_confirm_value", value: "nope" });
      }
    }

    expect(typedConfirmRequested).toBe(true);
    expect(composeRunner.forStackCalls).toHaveLength(0);
    expect(fs.existsSync(stackPath)).toBe(true);
  });

  test("rollback_started includes runningServices on partial failure", async () => {
    composeRunner.onBoundRunnerCreated = (runner) => {
      runner.up = async function* () {
        yield "partial failure\n";
        return 1;
      } as never;
      runner.psRows = [{ Name: "partial-web-1", Service: "web", State: "running" }];
    };

    const engine = makeEngine({
      tmp,
      stateStore,
      composeRunner,
      providerEvents: [
        planStackEvents({
          stackName: "partial",
          intent: "deploy partial",
          services: [
            {
              name: "web",
              kind: "custom",
              image: "nginx:1.27",
              exposure: "public",
              hostPort: 8080,
              containerPort: 80,
            },
            {
              name: "db",
              kind: "catalog",
              catalogId: "postgresql:16",
            },
          ],
        }),
        [{ type: "message_stop", stopReason: "end_turn" }],
      ],
    });

    const rollbackEvents: Array<{ type: string; runningServices?: string[] }> = [];

    for await (const ev of engine.query("deploy partial")) {
      if (ev.type === "plan_ready") {
        engine.respondTo(ev.id, { kind: "approve" });
      }
      if (ev.type === "rollback_started") {
        rollbackEvents.push(ev);
      }
    }

    expect(rollbackEvents).toHaveLength(1);
    const rb = rollbackEvents[0];
    expect(rb).toBeDefined();
    expect(rb?.runningServices).toEqual(["web"]);
  });
});
