import { Annotation } from "@langchain/langgraph";
import type { Message } from "src/types/message";
import type { ToolProgress } from "src/Tool";

export interface PendingToolResult {
  toolUseId: string;
  name: string;
  input: unknown;
  output: unknown;
  isError: boolean;
}

const spec = {
  messages: Annotation<Message[]>({
    reducer: (a, b) => [...a, ...b],
    default: () => [],
  }),
  iter: Annotation<number>({
    reducer: (_a, b) => b,
    default: () => 0,
  }),
  // session-scoped permission set, mirrors LoopContext.allowSet
  allowSet: Annotation<Set<string>>({
    reducer: (_a, b) => b,
    default: () => new Set(),
  }),
  // tool results produced by toolsNode, drained into messages each loop
  pendingToolResults: Annotation<PendingToolResult[]>({
    reducer: (a, b) => [...a, ...b],
    default: () => [],
  }),
  // progress lines produced by toolsNode for streaming
  progress: Annotation<ToolProgress[]>({
    reducer: (a, b) => [...a, ...b],
    default: () => [],
  }),
  // set when plan_review node has emitted a plan_ready and is waiting for resume
  pendingApproval: Annotation<
    | { stackName: string; composeYaml: string; diff: unknown; configFiles: unknown; autoGeneratedSecrets: unknown }
    | null
  >({
    reducer: (_a, b) => b,
    default: () => null,
  }),
};

export const AgentState = Object.assign(Annotation.Root(spec), spec);
