"""Textual TUI components."""

from docker_agent.components.activity_timeline import ActivityTimeline
from docker_agent.components.api_key_input_dialog import ApiKeyInputDialog
from docker_agent.components.command_palette import CommandPalette
from docker_agent.components.footer import Footer, StatusFooter
from docker_agent.components.log_pane import LogPane
from docker_agent.components.model_picker_dialog import ModelChoice, ModelPickerDialog
from docker_agent.components.ollama_setup_dialog import OllamaSetupDialog, OllamaSetupResult
from docker_agent.components.permission_dialog import PermissionDialog
from docker_agent.components.plan_preview import (
    AutoGeneratedSecret,
    ConfigFile,
    render_action_review_preview,
)
from docker_agent.components.prompt_input import PromptInput, PromptSubmitted, ResumeQueue
from docker_agent.components.provider_connect_dialog import ProviderConnectDialog
from docker_agent.components.queue_panel import QueueAction, QueuePanel
from docker_agent.components.secrets_input_dialog import SecretsInputDialog
from docker_agent.components.thinking_indicator import ThinkingIndicator
from docker_agent.components.tool_details_panel import ToolDetailsPanel
from docker_agent.components.typed_confirm_dialog import InlineConfirmDialog, TypedConfirmDialog
from docker_agent.components.welcome_banner import WelcomeBanner
from docker_agent.services.provider_status import ProviderStatus

__all__ = [
    "ActivityTimeline",
    "ApiKeyInputDialog",
    "CommandPalette",
    "Footer",
    "LogPane",
    "ModelChoice",
    "ModelPickerDialog",
    "OllamaSetupDialog",
    "OllamaSetupResult",
    "PermissionDialog",
    "AutoGeneratedSecret",
    "ConfigFile",
    "render_action_review_preview",
    "PromptInput",
    "PromptSubmitted",
    "ProviderConnectDialog",
    "ProviderStatus",
    "QueueAction",
    "QueuePanel",
    "ResumeQueue",
    "SecretsInputDialog",
    "StatusFooter",
    "ThinkingIndicator",
    "ToolDetailsPanel",
    "InlineConfirmDialog",
    "TypedConfirmDialog",
    "WelcomeBanner",
]