"""Inline plan preview rendering for the activity timeline."""

from __future__ import annotations

from dataclasses import dataclass

import yaml
from rich.text import Text

from docker_agent.types.stack import StackDiff
from docker_agent.ui.activity import PlanActivity, PlanActivityStatus, PlanConfigRef, PlanSecretRef
from docker_agent.ui.tool_presentation import safe_json_value, sanitize_tool_text


@dataclass
class ConfigFile:
    path: str
    content: str
    bytes: int


@dataclass
class AutoGeneratedSecret:
    service: str
    keys: list[str]


def compose_yaml_for_preview(compose_yaml: str) -> str:
    try:
        parsed = yaml.safe_load(compose_yaml)
        if not isinstance(parsed, dict):
            return compose_yaml
        parsed.pop("x-docker-agent", None)
        dumped = yaml.safe_dump(parsed, default_flow_style=False).strip()
        return str(dumped)
    except yaml.YAMLError:
        return compose_yaml


def _render_service_diffs(diff: StackDiff) -> Text:
    content = Text()
    if not diff.service_diffs:
        content.append(" No changes detected\n", style="dim")
        return content
    for service_diff in diff.service_diffs:
        if not service_diff.actual:
            action, color = "[+] (create)", "green"
        elif not service_diff.desired:
            action, color = "[-] (delete)", "red"
        else:
            action, color = "[~] (modify)", "yellow"
        content.append(f"{service_diff.service} {action}\n", style=f"bold {color}")
        for change in service_diff.changes:
            content.append(
                f"  - {change.field}: {safe_json_value(change.from_)} -> "
                f"{safe_json_value(change.to)}\n",
                style="dim",
            )
        if service_diff.desired:
            content.append(f"  - Image: {service_diff.desired.image}\n", style="dim")
            if service_diff.desired.ports:
                content.append(
                    f"  - Ports: {', '.join(service_diff.desired.ports)}\n",
                    style="dim",
                )
    return content


def _render_secrets(auto_generated_secrets: list[PlanSecretRef]) -> Text:
    if not auto_generated_secrets:
        return Text("")
    content = Text("Auto-generated secret keys (values hidden):\n", style="bold cyan")
    for entry in auto_generated_secrets:
        content.append(f"{entry.service}:\n", style="bold cyan")
        for key in entry.keys:
            content.append(f"  - {key}: ", style="")
            content.append("****************\n", style="yellow")
    return content


def _render_bordered_block(lines: list[str], *, style: str = "dim") -> Text:
    """Render lines inside a simple box border for visual separation."""
    if not lines:
        return Text("")
    inner_width = max(len(line) for line in lines)
    inner_width = max(inner_width, 4)
    horizontal = "─" * (inner_width + 2)
    content = Text()
    content.append(f" ┌{horizontal}┐\n", style="dim")
    for line in lines:
        padded = line.ljust(inner_width)
        content.append(f" │ {padded} │\n", style=style)
    content.append(f" └{horizontal}┘\n", style="dim")
    return content


def _render_config_files(
    config_files: list[PlanConfigRef],
    *,
    show_config: bool,
) -> Text:
    if not config_files:
        return Text("")
    toggle = "collapse" if show_config else "expand"
    content = Text(f"Config files to be written (Press 'c' to {toggle}):\n", style="bold")
    for config_file in config_files:
        content.append(f"  - {config_file.path} ({config_file.bytes} bytes)\n", style="cyan")
        if show_config:
            content.append(f"{sanitize_tool_text(config_file.content)}\n", style="dim")
    return content


def _render_yaml(
    compose_yaml: str,
    *,
    show_yaml: bool,
) -> Text:
    display_yaml = compose_yaml_for_preview(compose_yaml)
    toggle = "collapse" if show_yaml else "expand"
    content = Text(f"YAML Configuration (Press 'x' to {toggle}):\n", style="bold")
    if show_yaml:
        yaml_lines = sanitize_tool_text(display_yaml).split("\n")
        content.append_text(_render_bordered_block(yaml_lines))
    else:
        line_count = len(display_yaml.split("\n"))
        content.append(f" [YAML collapsed - {line_count} lines]", style="dim")
    return content


def render_plan_preview(
    *,
    compose_yaml: str,
    diff: StackDiff | None,
    auto_generated_secrets: list[PlanSecretRef] | None = None,
    config_files: list[PlanConfigRef] | None = None,
    show_yaml: bool = False,
    show_config: bool = False,
    status: PlanActivityStatus = "pending",
) -> Text:
    """Render a plan preview block for the chat timeline."""
    content = Text()
    content.append("Plan preview\n", style="bold cyan")
    if diff is not None:
        content.append(f"Plan: {diff.stack_name}\n", style="bold")
        content.append(f"Status: {diff.status}\n", style="dim")
        content.append("Services and changes:\n", style="bold")
        content.append_text(_render_service_diffs(diff))
    secrets = auto_generated_secrets or []
    files = config_files or []
    secrets_text = _render_secrets(secrets)
    if secrets_text.plain:
        content.append_text(secrets_text)
    config_text = _render_config_files(files, show_config=show_config)
    if config_text.plain:
        content.append_text(config_text)
    content.append_text(_render_yaml(compose_yaml, show_yaml=show_yaml))
    content.append("\n")
    if status == "pending":
        content.append(
            "Apply this plan? [y/n] (Press 'x' to view YAML, 'c' to view config files)\n",
            style="yellow",
        )
    elif status == "approved":
        content.append("Plan approved\n", style="green")
    else:
        content.append("Plan declined\n", style="red")
    return content


def render_plan_activity(activity: PlanActivity) -> Text:
    return render_plan_preview(
        compose_yaml=activity.compose_yaml,
        diff=activity.diff,
        auto_generated_secrets=activity.auto_generated_secrets,
        config_files=activity.config_files,
        show_yaml=activity.show_yaml,
        show_config=activity.show_config,
        status=activity.status,
    )


__all__ = [
    "AutoGeneratedSecret",
    "ConfigFile",
    "compose_yaml_for_preview",
    "render_plan_activity",
    "render_plan_preview",
]
