"""plan_stack tool."""

from __future__ import annotations

from collections.abc import AsyncIterator
from dataclasses import dataclass, field
from typing import Any, Literal

from docker_mcp_server.tools.base import ToolContext, ToolDone, ToolProgress
from docker_mcp_server.tools.resolve_dependency import ResolveDependencyResult
from docker_mcp_server.tools.shared.app_source_guard import AppSourceIssue
from docker_mcp_server.tools.shared.config_files import StagedConfigFile
from docker_mcp_server.tools.shared.db_port_guard import DbPortExposureIssue
from docker_mcp_server.tools.shared.network_guard import NetworkIssue
from docker_mcp_server.tools.shared.plan_phases import (
    AutoGeneratedSecret,
    assemble_compose,
    stage_stack_secrets,
)
from docker_mcp_server.tools.shared.port_conflicts import CheckPortConflictResult
from docker_mcp_server.tools.shared.resource_limits import ResourceLimitIssue
from docker_mcp_server.tools.shared.secret_staging import StagedSecretFile
from docker_mcp_server.tools.shared.spec_schemas import StackDraft
from docker_mcp_server.tools.shared.translator import prepare_stack_draft
from docker_mcp_server.tools.shared.volume_guard import VolumeIssue
from docker_mcp_server.tools.validate_spec import (
    PreflightReport,
    SpecIssue,
    preflight_report_to_artifact,
    preflight_report_to_validation_details,
    run_preflight,
)
from docker_mcp_server.types.stack import StackDiff


@dataclass
class PlanStackResultOk:
    blocked: Literal[False] = False
    compose_yaml: str = ""
    scale_overrides: dict[str, int] = field(default_factory=dict)
    diff: StackDiff | None = None
    auto_generated_secrets: list[AutoGeneratedSecret] = field(default_factory=list)
    config_files: list[StagedConfigFile] = field(default_factory=list)
    staged_secret_files: list[StagedSecretFile] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)
    hash: str = ""
    preflight_artifact: dict[str, Any] | None = None
    preflight_details: dict[str, Any] | None = None


@dataclass
class PlanStackResultBlocked:
    blocked: Literal[True] = True
    reason: str = ""
    issues: list[SpecIssue] | None = None
    dependency: ResolveDependencyResult | None = None
    port_check: CheckPortConflictResult | None = None
    resource_issues: list[ResourceLimitIssue] | None = None
    db_port_issues: list[DbPortExposureIssue] | None = None
    volume_issues: list[VolumeIssue] | None = None
    network_issues: list[NetworkIssue] | None = None
    missing_by_service: dict[str, list[str]] | None = None
    missing_files: list[str] | None = None
    app_source_issues: list[AppSourceIssue] | None = None
    error: str | None = None
    preflight_artifact: dict[str, Any] | None = None
    preflight_details: dict[str, Any] | None = None


PlanStackResult = PlanStackResultOk | PlanStackResultBlocked


def _blocked_from_preflight(report: PreflightReport) -> PlanStackResultBlocked:
    artifact = preflight_report_to_artifact(report)
    details = preflight_report_to_validation_details(report)
    reason = report.failure_reason or "invalid_spec"
    blocked = PlanStackResultBlocked(
        reason=reason,
        preflight_artifact=artifact,
        preflight_details=details,
    )
    if reason == "missing_app_source":
        blocked.app_source_issues = report.app_source_issues
    elif reason == "invalid_spec":
        blocked.issues = list(report.issues)
    elif reason == "invalid_dependency":
        blocked.dependency = report.dependency
    elif reason == "port_conflict":
        blocked.port_check = report.port_check
    elif reason == "resource_limit":
        blocked.resource_issues = report.resource_issues
    elif reason == "db_port_exposed":
        blocked.db_port_issues = report.db_port_issues
    elif reason == "db_app_wiring":
        blocked.issues = list(report.issues)
    elif reason in {"unsafe_volume", "undeclared_volume"}:
        blocked.volume_issues = report.volume_issues
    elif reason == "undeclared_network":
        blocked.network_issues = report.network_issues
    else:
        blocked.issues = list(report.issues)
    return blocked


class _PlanStackTool:
    name = "plan_stack"
    description = (
        "Generate a Docker Compose plan for a stack. The LLM provides the "
        "service intents; the tool translates, validates, configures safe "
        "ports, resource limits, logging, mounts, auto-generates secrets, "
        "and returns YAML."
    )
    input_schema = StackDraft
    category = "high-level"

    def needs_permission(self, _input: Any) -> bool:
        return False

    async def call(
        self, input: StackDraft, ctx: ToolContext
    ) -> AsyncIterator[ToolProgress | ToolDone]:
        yield ToolProgress(msg="Preparing stack draft...")

        prep = await prepare_stack_draft(input, ctx)
        if not prep.ok:
            yield ToolDone(
                PlanStackResultBlocked(
                    reason="invalid_spec",
                    issues=[
                        SpecIssue(
                            code="invalid_spec",
                            path="services",
                            message=prep.error or "unknown",
                        )
                    ],
                )
            )
            return
        assert prep.prepared is not None
        prepared = prep.prepared

        report = await run_preflight(
            stack_name=input.stack_name,
            prepared=prepared,
            config_files=input.config_files,
            ctx=ctx,
            stop_at_first=True,
        )
        for progress in report.progress:
            yield ToolProgress(msg=progress)
        for warning in report.warnings:
            yield ToolProgress(msg=warning)
        if not report.ok:
            yield ToolDone(_blocked_from_preflight(report))
            return

        secret_result = stage_stack_secrets(input, prepared, ctx)
        if not secret_result.ok:
            yield ToolDone(
                PlanStackResultBlocked(
                    reason=secret_result.reason,
                    issues=secret_result.issues,
                    missing_by_service=secret_result.missing_by_service,
                    missing_files=secret_result.missing_files,
                    preflight_artifact=preflight_report_to_artifact(report),
                    preflight_details=preflight_report_to_validation_details(report),
                )
            )
            return

        yield ToolProgress(msg="Assembling Compose YAML...")

        assert secret_result.stager is not None
        assemble_result = await assemble_compose(
            input,
            prepared,
            secret_result.services,
            secret_result.generated_env_file_sources,
            ctx,
        )
        if not assemble_result.ok:
            yield ToolDone(
                PlanStackResultBlocked(
                    reason=assemble_result.reason,
                    error=assemble_result.error,
                    preflight_artifact=preflight_report_to_artifact(report),
                    preflight_details=preflight_report_to_validation_details(report),
                )
            )
            return

        yield ToolDone(
            PlanStackResultOk(
                compose_yaml=assemble_result.compose_yaml,
                scale_overrides=assemble_result.scale_overrides,
                diff=assemble_result.diff,
                auto_generated_secrets=secret_result.auto_generated_secrets,
                config_files=secret_result.staged_files,
                staged_secret_files=secret_result.stager.staged_files(),
                warnings=report.warnings,
                hash=prepared.hash,
                preflight_artifact=preflight_report_to_artifact(report),
                preflight_details=preflight_report_to_validation_details(report),
            )
        )


plan_stack = _PlanStackTool()

__all__ = [
    "AutoGeneratedSecret",
    "PlanStackResult",
    "PlanStackResultBlocked",
    "PlanStackResultOk",
    "plan_stack",
]
