import type { StackDiff } from "./stack";

export type LoopEvent =
  | { type: "iteration_start"; n: number }
  | { type: "assistant_text"; delta: string }
  | { type: "tool_call"; name: string; input: unknown }
  | { type: "tool_progress"; msg: string }
  | { type: "tool_result"; name: string; output: unknown }
  | { type: "permission_request"; id: string; tool: string; input: unknown }
  | {
      type: "plan_ready";
      id: string;
      composeYaml: string;
      diff: StackDiff;
      autoGeneratedSecrets?: Array<{ service: string; keys: string[] }>;
    }
  | { type: "typed_confirm_request"; id: string; phrase: string; reason: string }
  | {
      type: "secrets_input_request";
      id: string;
      service: string;
      keys: string[];
      reason: string;
    }
  | { type: "usage"; inputTokens: number; outputTokens: number }
  | { type: "error"; error: Error };

export type { PermissionResponse } from "./permissions";
