"""LoopEvent discriminated union.

Parity: ``src/types/events.ts:12-50``. 13 variants keyed on ``type``.

Two design notes:

1. The ``error`` variant carries a real :class:`BaseException` reference for
   in-process dispatch (the QueryEngine forwards it to the structured logger as
   a Python object, not a serialised string). Pydantic v2 supports this via
   ``arbitrary_types_allowed=True``; downstream loggers serialise
   ``{"message": str(error), "type": type(error).__name__}`` themselves.
2. ``plan_ready`` embeds :class:`StackDiff` plus two optional lists of inline
   helper models (:class:`AutoGeneratedSecret`, :class:`ConfigFileRef`).
   These are NOT exported from the top-level package name because they only
   appear inside this variant — same convention as TS.
"""

from typing import Annotated, Any, Literal

from pydantic import BaseModel, ConfigDict, Field

from src.types.stack import StackDiff

_MODEL_CONFIG = ConfigDict(extra="forbid", populate_by_name=True)
_ERROR_CONFIG = ConfigDict(
    extra="forbid", populate_by_name=True, arbitrary_types_allowed=True
)


# --- inline helpers used only by plan_ready -----------------------------


class AutoGeneratedSecret(BaseModel):
    """``{"service": str, "keys": list[str]}`` row inside ``plan_ready``."""

    model_config = _MODEL_CONFIG
    service: str
    keys: list[str]


class ConfigFileRef(BaseModel):
    """``{"path": str, "content": str, "bytes": int}`` row inside ``plan_ready``."""

    model_config = _MODEL_CONFIG
    path: str
    content: str
    bytes: int


# --- 13 LoopEvent variants -----------------------------------------------


class IterationStart(BaseModel):
    model_config = _MODEL_CONFIG
    type: Literal["iteration_start"] = "iteration_start"
    n: int


class AssistantText(BaseModel):
    model_config = _MODEL_CONFIG
    type: Literal["assistant_text"] = "assistant_text"
    delta: str


class ToolCall(BaseModel):
    model_config = _MODEL_CONFIG
    type: Literal["tool_call"] = "tool_call"
    name: str
    input: Any


class ToolProgress(BaseModel):
    model_config = _MODEL_CONFIG
    type: Literal["tool_progress"] = "tool_progress"
    msg: str


class ToolResult(BaseModel):
    model_config = _MODEL_CONFIG
    type: Literal["tool_result"] = "tool_result"
    name: str
    output: Any


class PermissionRequest(BaseModel):
    """``permission_request`` event emitted by engine to the UI.

    Distinct from :class:`docker_agent.types.permissions.PermissionRequest`;
    that one is the *out-of-band* shape (no ``id``), this one carries the
    ``nanoid`` correlation id used by ``QueryEngine.respond_to(...)``.
    """

    model_config = _MODEL_CONFIG
    type: Literal["permission_request"] = "permission_request"
    id: str
    tool: str
    input: Any


class PlanReady(BaseModel):
    model_config = _MODEL_CONFIG
    type: Literal["plan_ready"] = "plan_ready"
    id: str
    compose_yaml: str = Field(alias="composeYaml")
    diff: StackDiff
    auto_generated_secrets: list[AutoGeneratedSecret] | None = Field(
        default=None, alias="autoGeneratedSecrets"
    )
    config_files: list[ConfigFileRef] | None = Field(
        default=None, alias="configFiles"
    )


class TypedConfirmRequest(BaseModel):
    model_config = _MODEL_CONFIG
    type: Literal["typed_confirm_request"] = "typed_confirm_request"
    id: str
    phrase: str
    reason: str


class SecretsInputRequest(BaseModel):
    model_config = _MODEL_CONFIG
    type: Literal["secrets_input_request"] = "secrets_input_request"
    id: str
    service: str
    keys: list[str]
    reason: str


class Usage(BaseModel):
    model_config = _MODEL_CONFIG
    type: Literal["usage"] = "usage"
    input_tokens: int = Field(alias="inputTokens")
    output_tokens: int = Field(alias="outputTokens")


class Error(BaseModel):
    """Carries a live ``BaseException`` reference; not JSON-serializable."""

    model_config = _ERROR_CONFIG
    type: Literal["error"] = "error"
    error: BaseException


class RollbackStarted(BaseModel):
    model_config = _MODEL_CONFIG
    type: Literal["rollback_started"] = "rollback_started"
    stack_name: str = Field(alias="stackName")
    reason: Literal["apply_failed", "unhealthy"]
    detail: str
    running_services: list[str] | None = Field(default=None, alias="runningServices")


class RollbackResult(BaseModel):
    model_config = _MODEL_CONFIG
    type: Literal["rollback_result"] = "rollback_result"
    stack_name: str = Field(alias="stackName")
    ok: bool
    restored: Literal["previous", "removed", "none"]
    detail: str | None = None


_LoopEventUnion = (
    IterationStart
    | AssistantText
    | ToolCall
    | ToolProgress
    | ToolResult
    | PermissionRequest
    | PlanReady
    | TypedConfirmRequest
    | SecretsInputRequest
    | Usage
    | Error
    | RollbackStarted
    | RollbackResult
)

LoopEvent = Annotated[_LoopEventUnion, Field(discriminator="type")]


from src.types.permissions import (  # noqa: E402
    PermissionResponse,
)

__all__ = [
    "AssistantText",
    "AutoGeneratedSecret",
    "ConfigFileRef",
    "Error",
    "IterationStart",
    "LoopEvent",
    "PermissionRequest",
    "PermissionResponse",
    "PlanReady",
    "RollbackResult",
    "RollbackStarted",
    "SecretsInputRequest",
    "ToolCall",
    "ToolProgress",
    "ToolResult",
    "TypedConfirmRequest",
    "Usage",
]