"""plan_stack tool."""

from __future__ import annotations

import contextlib
import copy
from collections.abc import AsyncIterator
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Literal, cast

from docker_agent.state.drift_detector import detect_drift
from docker_agent.state.env_file import merge_env
from docker_agent.state.secret_redactor import scrub_line, should_redact, looks_like_credential_uri
from docker_agent.tools.base import ToolContext, ToolDone, ToolProgress
from docker_agent.tools.shared.port_conflicts import (
    CheckPortConflictResult,
    check_port_conflicts,
)
from docker_agent.tools.resolve_dependency import (
    ResolveDependencyResult,
    resolve_dependencies,
)
from docker_agent.tools.shared.app_source_guard import AppSourceIssue, check_app_source_artifacts
from docker_agent.tools.shared.compose_builder import (
    PlanInput,
    build_stack_definition,
    stack_to_yaml,
)
from docker_agent.tools.shared.config_files import (
    StagedConfigFile,
    detect_missing_config_files,
    stage_config_files,
)
from docker_agent.tools.shared.db_app_wiring import wire_dependent_app_secrets
from docker_agent.tools.shared.db_port_guard import DbPortExposureIssue, check_db_port_exposure
from docker_agent.tools.shared.network_guard import NetworkIssue, check_network_references
from docker_agent.tools.shared.required_secrets import find_required_secrets, is_weak_secret_value
from docker_agent.tools.shared.resource_limits import ResourceLimitIssue, check_resource_limits
from docker_agent.tools.shared.secret_staging import SecretFileStager, StagedSecretFile
from docker_agent.tools.shared.spec_schemas import DraftServiceSpec, StackDraft
from docker_agent.tools.shared.translator import prepare_stack_draft
from docker_agent.tools.shared.volume_guard import (
    VolumeIssue,
    check_volume_references,
    check_volume_safety,
)
from docker_agent.tools.shared.yaml_round_trip import validate_yaml_round_trip
from docker_agent.tools.validate_spec import SpecIssue, validate_spec_input
from docker_agent.types.stack import EnvFileSource, ServiceSpec, StackDiff


@dataclass
class AutoGeneratedSecret:
    service: str
    keys: list[str]


@dataclass
class PlanStackResultOk:
    blocked: Literal[False] = False
    compose_yaml: str = ""
    scale_overrides: dict[str, int] = field(default_factory=dict)
    diff: StackDiff | None = None
    auto_generated_secrets: list[AutoGeneratedSecret] = field(default_factory=list)
    config_files: list[StagedConfigFile] = field(default_factory=list)
    staged_secret_files: list[StagedSecretFile] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)
    hash: str = ""


@dataclass
class PlanStackResultBlocked:
    blocked: Literal[True] = True
    reason: str = ""
    issues: list[SpecIssue] | None = None
    dependency: ResolveDependencyResult | None = None
    port_check: CheckPortConflictResult | None = None
    resource_issues: list[ResourceLimitIssue] | None = None
    db_port_issues: list[DbPortExposureIssue] | None = None
    volume_issues: list[VolumeIssue] | None = None
    network_issues: list[NetworkIssue] | None = None
    missing_by_service: dict[str, list[str]] | None = None
    missing_files: list[str] | None = None
    app_source_issues: list[AppSourceIssue] | None = None
    error: str | None = None


PlanStackResult = PlanStackResultOk | PlanStackResultBlocked


def _generated_env_file_path(cwd: str, stack_name: str, service_name: str) -> Path:
    return Path(cwd) / ".docker-agent" / "secrets" / f"{stack_name}-{service_name}.env"


def _generated_env_file_ref(stack_name: str, service_name: str) -> str:
    return f"./.docker-agent/secrets/{stack_name}-{service_name}.env"


def _resolve_env_file(cwd: str, ref_path: str) -> Path:
    return Path(cwd).resolve() / ref_path


def _to_service_spec(spec: DraftServiceSpec) -> ServiceSpec:
    return spec


class _PlanStackTool:
    name = "plan_stack"
    description = (
        "Generate a Docker Compose plan for a stack. The LLM provides the "
        "service intents; the tool translates, validates, configures safe "
        "ports, resource limits, logging, mounts, auto-generates secrets, "
        "and returns YAML."
    )
    input_schema = StackDraft
    category = "high-level"

    def needs_permission(self, _input: Any) -> bool:
        return False

    async def call(
        self, input: StackDraft, ctx: ToolContext
    ) -> AsyncIterator[ToolProgress | ToolDone]:
        yield ToolProgress(msg="Preparing stack draft...")

        prep = await prepare_stack_draft(input, ctx)
        if not prep.ok:
            yield ToolDone(
                PlanStackResultBlocked(
                    reason="invalid_spec",
                    issues=[
                        SpecIssue(
                            code="invalid_spec",
                            path="services",
                            message=prep.error or "unknown",
                        )
                    ],
                )
            )
            return
        assert prep.prepared is not None
        prepared = prep.prepared

        config_paths = set(input.config_files.keys()) if input.config_files else set()
        app_source_issues = check_app_source_artifacts(prepared.services, config_paths)
        if app_source_issues:
            yield ToolDone(
                PlanStackResultBlocked(
                    reason="missing_app_source",
                    app_source_issues=app_source_issues,
                )
            )
            return

        yield ToolProgress(msg="Validating service spec...")

        spec_input: dict[str, Any] = {"services": prepared.services}
        if input.config_files is not None:
            spec_input["config_files"] = input.config_files
        spec_check = await validate_spec_input(spec_input, ctx)
        for warning in spec_check.warnings:
            yield ToolProgress(msg=warning)
        if not spec_check.valid:
            yield ToolDone(
                PlanStackResultBlocked(
                    reason="invalid_spec",
                    issues=spec_check.issues,
                )
            )
            return

        dependency = resolve_dependencies(prepared.services)
        if not dependency.valid:
            yield ToolDone(
                PlanStackResultBlocked(
                    reason="invalid_dependency",
                    dependency=dependency,
                )
            )
            return

        port_check = await check_port_conflicts(
            input.stack_name, prepared.services, ctx
        )
        if not port_check.ok:
            yield ToolDone(
                PlanStackResultBlocked(
                    reason="port_conflict",
                    port_check=port_check,
                )
            )
            return

        resource_issues = check_resource_limits(prepared.services)
        if resource_issues:
            yield ToolDone(
                PlanStackResultBlocked(
                    reason="resource_limit",
                    resource_issues=resource_issues,
                )
            )
            return

        db_port_issues = check_db_port_exposure(prepared.services)
        if db_port_issues:
            yield ToolDone(
                PlanStackResultBlocked(
                    reason="db_port_exposed",
                    db_port_issues=db_port_issues,
                )
            )
            return

        volume_issues = check_volume_safety(ctx.cwd, prepared.services)
        if volume_issues:
            yield ToolDone(
                PlanStackResultBlocked(
                    reason="unsafe_volume",
                    volume_issues=volume_issues,
                )
            )
            return

        volume_ref_issues = check_volume_references(
            prepared.services, prepared.volumes
        )
        if volume_ref_issues:
            yield ToolDone(
                PlanStackResultBlocked(
                    reason="undeclared_volume",
                    volume_issues=volume_ref_issues,
                )
            )
            return

        network_issues = check_network_references(
            prepared.services, prepared.networks
        )
        if network_issues:
            yield ToolDone(
                PlanStackResultBlocked(
                    reason="undeclared_network",
                    network_issues=network_issues,
                )
            )
            return

        services = copy.deepcopy(prepared.services)
        staged_config = stage_config_files(
            ctx.cwd, services, input.config_files
        )
        if not staged_config.get("ok"):
            yield ToolDone(
                PlanStackResultBlocked(
                    reason="invalid_spec",
                    issues=[
                        SpecIssue(
                            code="invalid_config_path",
                            path="configFiles",
                            message=str(staged_config.get("error", "unknown")),
                        )
                    ],
                )
            )
            return
        staged_files = cast(
            list[StagedConfigFile], staged_config.get("staged", [])
        )

        auto_generated_secrets: list[AutoGeneratedSecret] = []
        generated_env_file_sources: dict[str, EnvFileSource] = {}
        missing_by_service: dict[str, list[str]] = {}
        stager = SecretFileStager()

        for service_name, spec in services.items():
            moved_secrets: dict[str, str] = {}
            inline_environment = dict(spec.environment or {})
            remaining_inline_environment: dict[str, str] = {}

            for key, value in inline_environment.items():
                if should_redact(key) or looks_like_credential_uri(value):
                    moved_secrets[key] = value
                else:
                    remaining_inline_environment[key] = value

            service_env_file = list(spec.env_file or [])

            if moved_secrets:
                target_path = _generated_env_file_path(
                    ctx.cwd, input.stack_name, service_name
                )
                stager.stage(
                    target_path,
                    {**stager.read(target_path), **moved_secrets},
                )
                target_ref = _generated_env_file_ref(input.stack_name, service_name)
                if target_ref not in service_env_file:
                    service_env_file.append(target_ref)
                existing = generated_env_file_sources.get(service_name)
                added_keys = [
                    *(existing.added_keys if existing and existing.added_keys else []),
                    *moved_secrets.keys(),
                ]
                generated_env_file_sources[service_name] = EnvFileSource(
                    generated=True,
                    path=target_ref,
                    added_keys=added_keys,
                )
                auto_generated_secrets.append(
                    AutoGeneratedSecret(
                        service=service_name,
                        keys=list(moved_secrets.keys()),
                    )
                )

            rule = find_required_secrets(spec.image)
            if rule and rule.required:
                from_env_file: dict[str, str] = {}
                for env_file_path in service_env_file:
                    from_env_file.update(
                        stager.read(_resolve_env_file(ctx.cwd, env_file_path))
                    )

                merged = merge_env(from_env_file, remaining_inline_environment)
                missing = [key for key in rule.required if merged.get(key) is None]
                weak = [
                    key
                    for key in rule.required
                    if merged.get(key) is not None
                    and isinstance(merged[key], str)
                    and is_weak_secret_value(key, merged[key], rule)
                ]
                replaceable = [*missing, *weak]
                safe_keys = [
                    key
                    for key in replaceable
                    if rule.safe_defaults.get(key) is not None
                ]
                unsafe_keys = [
                    key
                    for key in replaceable
                    if rule.safe_defaults.get(key) is None
                ]

                if unsafe_keys:
                    missing_by_service[service_name] = unsafe_keys

                if safe_keys:
                    target_path = _generated_env_file_path(
                        ctx.cwd, input.stack_name, service_name
                    )
                    target_values = dict(stager.read(target_path))
                    for key in safe_keys:
                        make_default = rule.safe_defaults.get(key)
                        if make_default is not None:
                            target_values[key] = make_default()
                    stager.stage(target_path, target_values)
                    target_ref = _generated_env_file_ref(
                        input.stack_name, service_name
                    )
                    if target_ref not in service_env_file:
                        service_env_file.append(target_ref)
                    existing = generated_env_file_sources.get(service_name)
                    added_keys = [
                        *(existing.added_keys if existing and existing.added_keys else []),
                        *safe_keys,
                    ]
                    generated_env_file_sources[service_name] = EnvFileSource(
                        generated=True,
                        path=target_ref,
                        added_keys=added_keys,
                    )
                    auto_generated_secrets.append(
                        AutoGeneratedSecret(service=service_name, keys=safe_keys)
                    )

            next_spec = spec.model_copy(
                update={
                    "environment": (
                        remaining_inline_environment
                        if remaining_inline_environment
                        else None
                    ),
                    "env_file": service_env_file or None,
                }
            )
            services[service_name] = next_spec

        wired_secrets = wire_dependent_app_secrets(
            ctx.cwd,
            input.stack_name,
            services,
            generated_env_file_sources,
            stager,
        )
        for service_name, keys in wired_secrets:
            auto_generated_secrets.append(
                AutoGeneratedSecret(service=service_name, keys=keys)
            )

        if missing_by_service:
            yield ToolDone(
                PlanStackResultBlocked(
                    reason="missing_required_env",
                    missing_by_service=missing_by_service,
                )
            )
            return

        missing_config = detect_missing_config_files(
            services,
            {f.path for f in staged_files},
            ctx.cwd,
        )
        if missing_config:
            yield ToolDone(
                PlanStackResultBlocked(
                    reason="missing_config_file",
                    missing_files=[item["path"] for item in missing_config],
                )
            )
            return

        yield ToolProgress(msg="Assembling Compose YAML...")

        previous = ctx.state_store.read(input.stack_name)
        stack_services = {
            name: _to_service_spec(spec) for name, spec in services.items()
        }
        plan_input = PlanInput(
            stack_name=input.stack_name,
            intent=input.intent,
            services=stack_services,
            networks=prepared.networks,
            volumes=prepared.volumes,
        )
        build = build_stack_definition(
            plan_input,
            previous,
            ctx.provider_name,
            ctx.model or f"{ctx.provider_name}-default",
        )
        definition = build.definition
        definition.x_docker_agent.env_file_sources = {
            **definition.x_docker_agent.env_file_sources,
            **generated_env_file_sources,
        }
        compose_yaml = stack_to_yaml(definition)
        yaml_check = validate_yaml_round_trip(compose_yaml)
        if not yaml_check.ok:
            yield ToolDone(
                PlanStackResultBlocked(
                    reason="invalid_yaml",
                    error=yaml_check.error or "unknown YAML error",
                )
            )
            return

        diff = StackDiff.model_validate(
            {
                "stackName": input.stack_name,
                "status": "missing",
                "serviceDiffs": [],
            }
        )
        with contextlib.suppress(Exception):
            diff = await detect_drift(
                input.stack_name, ctx.state_store, ctx.docker_engine, ctx.cwd
            )

        yield ToolDone(
            PlanStackResultOk(
                compose_yaml=compose_yaml,
                scale_overrides=build.scale_overrides,
                diff=diff,
                auto_generated_secrets=auto_generated_secrets,
                config_files=staged_files,
                staged_secret_files=stager.staged_files(),
                warnings=spec_check.warnings,
                hash=prepared.hash,
            )
        )


plan_stack = _PlanStackTool()

__all__ = [
    "AutoGeneratedSecret",
    "PlanStackResult",
    "PlanStackResultBlocked",
    "PlanStackResultOk",
    "plan_stack",
]
