import { Box, Text, useInput } from "ink";
import type React from "react";
import { useState, useRef } from "react";
import type { PermissionResponse } from "src/types/permissions";
import type { StackDiff } from "src/types/stack";
import fs from "node:fs";
import path from "node:path";

export interface PlanPreviewProps {
  composeYaml: string;
  diff: StackDiff;
  autoGeneratedSecrets?: Array<{ service: string; keys: string[] }>;
  onAnswer: (r: PermissionResponse) => void;
}

function readSecretValues(stackName: string, service: string): Record<string, string> {
  const file = path.join(process.cwd(), ".docker-agent", "secrets", `${stackName}-${service}.env`);
  if (!fs.existsSync(file)) return {};
  try {
    const content = fs.readFileSync(file, "utf8");
    const res: Record<string, string> = {};
    for (const line of content.split("\n")) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith("#")) continue;
      const idx = trimmed.indexOf("=");
      if (idx !== -1) {
        const k = trimmed.substring(0, idx).trim();
        const v = trimmed.substring(idx + 1).trim();
        res[k] = v;
      }
    }
    return res;
  } catch {
    return {};
  }
}

export function PlanPreview(props: PlanPreviewProps): React.ReactElement {
  const [showYaml, setShowYaml] = useState(false);
  const [showSecrets, setShowSecrets] = useState(false);
  const answeredRef = useRef(false);

  useInput((input) => {
    const keyStr = input.toLowerCase();
    if (keyStr === "y") {
      if (!answeredRef.current) {
        answeredRef.current = true;
        props.onAnswer({ kind: "approve" });
      }
    }
    if (keyStr === "n") {
      if (!answeredRef.current) {
        answeredRef.current = true;
        props.onAnswer({ kind: "deny" });
      }
    }
    if (keyStr === "x") {
      setShowYaml((prev) => !prev);
    }
    if (keyStr === "s") {
      setShowSecrets((prev) => !prev);
    }
  });

  return (
    <Box flexDirection="column" borderStyle="round" borderColor="yellow" paddingX={1} marginY={1}>
      <Text bold color="yellow">Plan: {props.diff.stackName}</Text>
      <Text>Status: <Text color={props.diff.status === "in_sync" ? "green" : "cyan"}>{props.diff.status}</Text></Text>

      {/* Services Table / Diff view */}
      <Box flexDirection="column" marginTop={1}>
        <Text bold underline>Services and changes:</Text>
        {props.diff.serviceDiffs.length === 0 ? (
          <Text dimColor>  No changes detected</Text>
        ) : (
          props.diff.serviceDiffs.map((sd, i) => {
            let actionText = "[~] (modify)";
            let actionColor = "yellow";
            if (!sd.actual) {
              actionText = "[+] (create)";
              actionColor = "green";
            } else if (!sd.desired) {
              actionText = "[-] (delete)";
              actionColor = "red";
            }

            return (
              <Box key={i} flexDirection="column" marginLeft={2} marginTop={1}>
                <Text color={actionColor} bold>{sd.service} {actionText}</Text>
                {sd.changes.map((c, ci) => (
                  <Text key={ci} dimColor>
                    {"  "}- {String(c.field)}: {JSON.stringify(c.from)} {"->"} {JSON.stringify(c.to)}
                  </Text>
                ))}
                {sd.desired && (
                  <Box flexDirection="column" marginLeft={2}>
                    <Text dimColor>- Image: {sd.desired.image}</Text>
                    {sd.desired.ports.length > 0 && (
                      <Text dimColor>- Ports: {sd.desired.ports.join(", ")}</Text>
                    )}
                    {sd.desired.volumes.length > 0 && (
                      <Text dimColor>- Volumes: {sd.desired.volumes.join(", ")}</Text>
                    )}
                  </Box>
                )}
              </Box>
            );
          })
        )}
      </Box>

      {/* Auto-generated secrets banner */}
      {props.autoGeneratedSecrets && props.autoGeneratedSecrets.length > 0 && (
        <Box flexDirection="column" marginTop={1} borderStyle="single" borderColor="cyan" paddingX={1}>
          <Text color="cyan" bold>Auto-generated secrets (Press 's' to toggle values):</Text>
          {props.autoGeneratedSecrets.map((s, i) => {
            const secretVals = readSecretValues(props.diff.stackName, s.service);
            return (
              <Box key={i} flexDirection="column" marginLeft={1}>
                <Text color="cyan" bold>{s.service}:</Text>
                {s.keys.map((k, ki) => {
                  const val = showSecrets ? (secretVals[k] ?? "not generated yet") : "****************";
                  return (
                    <Text key={ki}>
                      {"  "}- {k}: <Text color="yellow">{val}</Text>
                    </Text>
                  );
                })}
              </Box>
            );
          })}
        </Box>
      )}

      {/* Expandable YAML representation */}
      <Box flexDirection="column" marginTop={1}>
        <Text bold>YAML Configuration (Press 'x' to {showYaml ? "collapse" : "expand"}):</Text>
        {showYaml ? (
          <Box borderStyle="classic" borderColor="gray" paddingX={1} marginY={1}>
            <Text dimColor>{props.composeYaml}</Text>
          </Box>
        ) : (
          <Text dimColor>  [YAML collapsed - {props.composeYaml.split("\n").length} lines]</Text>
        )}
      </Box>

      {/* Decision prompt */}
      <Box marginTop={1}>
        <Text bold>Apply this plan? [<Text color="green">y</Text>/<Text color="red">N</Text>] <Text dimColor>(Press 'x' to view YAML, 's' to view secrets)</Text></Text>
      </Box>
    </Box>
  );
}
