"""Plan preview modal."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

import yaml
from rich.text import Text
from textual.app import ComposeResult
from textual.containers import Vertical
from textual.events import Key
from textual.screen import ModalScreen
from textual.widgets import Static

from src.types.permissions import Approve, Deny, PermissionResponse
from src.types.stack import StackDiff
from src.ui.tool_presentation import safe_json_value, sanitize_tool_text


@dataclass
class ConfigFile:
    path: str
    content: str
    bytes: int


@dataclass
class AutoGeneratedSecret:
    service: str
    keys: list[str]


def compose_yaml_for_preview(compose_yaml: str) -> str:
    try:
        parsed = yaml.safe_load(compose_yaml)
        if not isinstance(parsed, dict):
            return compose_yaml
        parsed.pop("x-docker-agent", None)
        dumped = yaml.safe_dump(parsed, default_flow_style=False).strip()
        return str(dumped)
    except yaml.YAMLError:
        return compose_yaml


class PlanPreview(ModalScreen[PermissionResponse]):
    def __init__(
        self,
        compose_yaml: str,
        diff: StackDiff,
        auto_generated_secrets: list[AutoGeneratedSecret] | None = None,
        config_files: list[ConfigFile] | None = None,
        **kwargs: Any,
    ) -> None:
        super().__init__(**kwargs)
        self._compose_yaml = compose_yaml
        self._diff = diff
        self._auto_generated_secrets = auto_generated_secrets or []
        self._config_files = config_files or []
        self._show_yaml = False
        self._show_config = False
        self._answered = False
        self._display_yaml = compose_yaml_for_preview(compose_yaml)

    def compose(self) -> ComposeResult:
        with Vertical(id="plan-preview"):
            yield Static(f"Plan: {self._diff.stack_name}", classes="title")
            yield Static(f"Status: {self._diff.status}", id="status-line")
            yield Static("Services and changes:", classes="section")
            yield Static("", id="service-diffs")
            yield Static("", id="secrets-banner")
            yield Static("", id="config-files")
            yield Static("", id="yaml-section")
            yield Static(
                "Apply this plan? [y/n] (Press 'x' to view YAML, 'c' to view config files)",
                classes="hint",
            )

    def on_mount(self) -> None:
        self._refresh()

    def _refresh(self) -> None:
        self.query_one("#service-diffs", Static).update(self._render_service_diffs())
        self.query_one("#secrets-banner", Static).update(self._render_secrets())
        self.query_one("#config-files", Static).update(self._render_config_files())
        self.query_one("#yaml-section", Static).update(self._render_yaml())

    def _render_service_diffs(self) -> Text:
        content = Text()
        if not self._diff.service_diffs:
            content.append(" No changes detected", style="dim")
            return content
        for service_diff in self._diff.service_diffs:
            if not service_diff.actual:
                action, color = "[+] (create)", "green"
            elif not service_diff.desired:
                action, color = "[-] (delete)", "red"
            else:
                action, color = "[~] (modify)", "yellow"
            content.append(f"{service_diff.service} {action}\n", style=f"bold {color}")
            for change in service_diff.changes:
                content.append(
                    f"  - {change.field}: {safe_json_value(change.from_)} -> "
                    f"{safe_json_value(change.to)}\n",
                    style="dim",
                )
            if service_diff.desired:
                content.append(f"  - Image: {service_diff.desired.image}\n", style="dim")
                if service_diff.desired.ports:
                    content.append(
                        f"  - Ports: {', '.join(service_diff.desired.ports)}\n",
                        style="dim",
                    )
        return content

    def _render_secrets(self) -> Text:
        if not self._auto_generated_secrets:
            return Text("")
        content = Text("Auto-generated secret keys (values hidden):\n", style="bold cyan")
        for entry in self._auto_generated_secrets:
            content.append(f"{entry.service}:\n", style="bold cyan")
            for key in entry.keys:
                content.append(f"  - {key}: ", style="")
                content.append("****************\n", style="yellow")
        return content

    def _render_config_files(self) -> Text:
        if not self._config_files:
            return Text("")
        toggle = "collapse" if self._show_config else "expand"
        content = Text(f"Config files to be written (Press 'c' to {toggle}):\n", style="bold")
        for config_file in self._config_files:
            content.append(f"  - {config_file.path} ({config_file.bytes} bytes)\n", style="cyan")
            if self._show_config:
                content.append(f"{sanitize_tool_text(config_file.content)}\n", style="dim")
        return content

    def _render_yaml(self) -> Text:
        toggle = "collapse" if self._show_yaml else "expand"
        content = Text(f"YAML Configuration (Press 'x' to {toggle}):\n", style="bold")
        if self._show_yaml:
            for line in sanitize_tool_text(self._display_yaml).split("\n"):
                content.append(f"{line}\n")
        else:
            line_count = len(self._display_yaml.split("\n"))
            content.append(f" [YAML collapsed - {line_count} lines]", style="dim")
        return content

    def on_key(self, event: Key) -> None:
        key = event.key.lower()
        if key == "x":
            self._show_yaml = not self._show_yaml
            self._refresh()
        elif key == "c":
            self._show_config = not self._show_config
            self._refresh()
        elif key == "y" and not self._answered:
            self._answered = True
            self.dismiss(Approve())
        elif key == "n" and not self._answered:
            self._answered = True
            self.dismiss(Deny())