import { Box, Text, useInput } from "ink";
import type React from "react";
import type { PermissionResponse } from "src/types/permissions";
import type { StackDiff } from "src/types/stack";

export interface PlanPreviewProps {
  composeYaml: string;
  diff: StackDiff;
  autoGeneratedSecrets?: Array<{ service: string; keys: string[] }>;
  onAnswer: (r: PermissionResponse) => void;
}

export function PlanPreview(props: PlanPreviewProps): React.ReactElement {
  useInput((input) => {
    if (input.toLowerCase() === "y") props.onAnswer({ kind: "approve" });
    if (input.toLowerCase() === "n") props.onAnswer({ kind: "deny" });
  });
  return (
    <Box flexDirection="column" borderStyle="round" borderColor="yellow" paddingX={1}>
      <Text bold>Plan: {props.diff.stackName}</Text>
      <Text dimColor>Status: {props.diff.status}</Text>
      <Box flexDirection="column" marginTop={1}>
        <Text dimColor>{props.composeYaml}</Text>
      </Box>
      {props.autoGeneratedSecrets && props.autoGeneratedSecrets.length > 0 && (
        <Box flexDirection="column" marginTop={1}>
          <Text color="cyan">Auto-generated secrets:</Text>
          {props.autoGeneratedSecrets.map((s, i) => (
            // biome-ignore lint/suspicious/noArrayIndexKey: stable static list
            <Text key={i}>
              {"  "}
              {s.service}: {s.keys.join(", ")}
            </Text>
          ))}
        </Box>
      )}
      <Box marginTop={1}>
        <Text>Apply this plan? [y/N]</Text>
      </Box>
    </Box>
  );
}
