"""Domain type re-exports — one-stop import for callers.

Mirrors the bundle of contracts that ``src/types/`` provides in TS. New type
modules added in later phases (e.g. policy types in Phase 4) extend this list
rather than introducing a new package layout.
"""

from docker_agent.types.events import (
    AssistantText,
    AutoGeneratedSecret,
    ConfigFileRef,
    Error,
    IterationStart,
    LoopEvent,
    PlanReady,
    RollbackResult,
    RollbackStarted,
    SecretsInputRequest,
    ToolCall,
    ToolProgress,
    ToolResult,
    TypedConfirmRequest,
    Usage,
)
from docker_agent.types.events import (
    PermissionRequest as PermissionRequestEvent,
)
from docker_agent.types.message import (
    AssistantBlock,
    AssistantMessage,
    Message,
    ToolResultMessage,
    UserMessage,
)
from docker_agent.types.permissions import (
    AlwaysAllowInSession,
    Approve,
    Deny,
    PermissionRequest,
    PermissionResponse,
    SecretsInputValues,
    TypedConfirmValue,
)
from docker_agent.types.stack import (
    DockerAgentMeta,
    EnvFileSource,
    EnvSnapshot,
    FieldChange,
    HealthcheckSpec,
    ServiceDiff,
    ServiceSnapshot,
    ServiceSpec,
    StackDefinition,
    StackDiff,
    StackSummary,
)

__all__ = [
    # permissions
    "AlwaysAllowInSession",
    "Approve",
    "Deny",
    "PermissionRequest",
    "PermissionRequestEvent",
    "PermissionResponse",
    "SecretsInputValues",
    "TypedConfirmValue",
    # message
    "AssistantBlock",
    "AssistantMessage",
    "Message",
    "ToolResultMessage",
    "UserMessage",
    # stack
    "DockerAgentMeta",
    "EnvFileSource",
    "EnvSnapshot",
    "FieldChange",
    "HealthcheckSpec",
    "ServiceDiff",
    "ServiceSnapshot",
    "ServiceSpec",
    "StackDefinition",
    "StackDiff",
    "StackSummary",
    # events
    "AssistantText",
    "AutoGeneratedSecret",
    "ConfigFileRef",
    "Error",
    "IterationStart",
    "LoopEvent",
    "PlanReady",
    "RollbackResult",
    "RollbackStarted",
    "SecretsInputRequest",
    "ToolCall",
    "ToolProgress",
    "ToolResult",
    "TypedConfirmRequest",
    "Usage",
]