import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import type { ToolContext } from "src/Tool";
import type { ComposeRunner } from "src/services/docker/composeRunner";
import type { ImageValidator } from "src/services/docker/imageValidator";
import { StateStore } from "src/state/StateStore";
import { planStack } from "src/tools/planStack";
import { beforeEach, describe, expect, test } from "vitest";
import { parse as parseYaml } from "yaml";
import { MockComposeRunner } from "../../../tests/mocks/mockComposeRunner";
import { MockDockerEngine } from "../../../tests/mocks/mockDockerEngine";

async function drain<T, R>(gen: AsyncGenerator<T, R>): Promise<R> {
  let r: IteratorResult<T, R>;
  while (true) {
    r = await gen.next();
    if (r.done) return r.value;
  }
}

function makeCtx(tmpRoot: string): ToolContext {
  const store = new StateStore(path.join(tmpRoot, ".docker-agent"));
  return {
    cwd: tmpRoot,
    stateStore: store,
    dockerEngine: new MockDockerEngine() as never,
    composeRunner: new MockComposeRunner() as unknown as ComposeRunner,
    abortSignal: new AbortController().signal,
  };
}

function invalidImageValidator(image: string): ImageValidator {
  return {
    validateImage: async () => ({
      image,
      status: "invalid",
      source: "registry",
      error: "manifest not found",
      suggestion: "postgres:17-alpine",
    }),
    validateImages: async () => [
      {
        image,
        status: "invalid",
        source: "registry",
        error: "manifest not found",
        suggestion: "postgres:17-alpine",
      },
    ],
  };
}

describe("plan_stack", () => {
  let tmpRoot: string;

  beforeEach(() => {
    tmpRoot = fs.mkdtempSync(path.join(os.tmpdir(), "plan-"));
  });

  test("simple nginx -> composeYaml + empty diff", async () => {
    const ctx = makeCtx(tmpRoot);
    const result = await drain(
      planStack.call(
        {
          stackName: "test",
          intent: "nginx",
          services: { nginx: { image: "nginx:1.27-alpine", ports: ["80:80"] } },
        },
        ctx,
      ),
    );

    if (result.blocked) throw new Error("plan should not be blocked");
    expect(result).toMatchObject({
      composeYaml: expect.stringContaining("nginx:1.27-alpine"),
      blocked: false,
    });
    expect(result.composeYaml).toContain("80:80");
  });

  test("inline secret auto-migrated to generated env_file", async () => {
    const ctx = makeCtx(tmpRoot);
    const result = await drain(
      planStack.call(
        {
          stackName: "s",
          intent: "x",
          services: {
            api: {
              image: "node:20",
              environment: { NODE_ENV: "prod", API_KEY: "leakvalue" },
            },
          },
        },
        ctx,
      ),
    );

    expect(result.blocked).toBe(false);
    if (result.blocked) throw new Error("plan should not be blocked");
    expect(result.composeYaml).not.toContain("leakvalue");
    expect(result.autoGeneratedSecrets).toContainEqual({
      service: "api",
      keys: ["API_KEY"],
    });
    expect(parseYaml(result.composeYaml)["x-docker-agent"].envFileSources).toEqual({
      api: {
        generated: true,
        path: "./.docker-agent/secrets/s-api.env",
        addedKeys: ["API_KEY"],
      },
    });
    const generatedPath = path.join(tmpRoot, ".docker-agent/secrets/s-api.env");
    expect(fs.existsSync(generatedPath)).toBe(true);
    expect(fs.readFileSync(generatedPath, "utf-8")).toContain("API_KEY=leakvalue");
  });

  test("postgres without env_file -> auto-generates POSTGRES_PASSWORD", async () => {
    const ctx = makeCtx(tmpRoot);
    const result = await drain(
      planStack.call(
        { stackName: "p", intent: "postgres", services: { db: { image: "postgres:16-alpine" } } },
        ctx,
      ),
    );

    expect(result.blocked).toBe(false);
    if (result.blocked) throw new Error("plan should not be blocked");
    expect(result.autoGeneratedSecrets).toContainEqual({
      service: "db",
      keys: ["POSTGRES_PASSWORD"],
    });
    const file = fs.readFileSync(path.join(tmpRoot, ".docker-agent/secrets/p-db.env"), "utf-8");
    expect(file).toMatch(/POSTGRES_PASSWORD=.{20,}/);
  });

  test("custom image without required-secret policy is not blocked", async () => {
    const ctx = makeCtx(tmpRoot);
    const result = await drain(
      planStack.call(
        {
          stackName: "b",
          intent: "billing",
          services: { worker: { image: "mycorp/billing:1.0" } },
        },
        ctx,
      ),
    );

    expect(result.blocked).toBe(false);
    if (result.blocked) throw new Error("plan should not be blocked");
  });

  test("scale field stored as services.<svc>.scale in YAML", async () => {
    const ctx = makeCtx(tmpRoot);
    const result = await drain(
      planStack.call(
        {
          stackName: "scaled",
          intent: "x",
          services: { api: { image: "node:20", scale: 2 } },
        },
        ctx,
      ),
    );

    if (result.blocked) throw new Error("plan should not be blocked");
    expect(result.composeYaml).toMatch(/api:\s*[\s\S]*scale:\s*2/);
    expect(result.scaleOverrides).toEqual({ api: 2 });
  });

  test("rejects invalid image tags before writing generated secrets", async () => {
    const ctx = makeCtx(tmpRoot);
    ctx.imageValidator = invalidImageValidator("postgres:99-alpine");

    const result = await drain(
      planStack.call(
        {
          stackName: "bad",
          intent: "postgres",
          services: { db: { image: "postgres:99-alpine" } },
        },
        ctx,
      ),
    );
    expect(result).toMatchObject({
      blocked: true,
      reason: "invalid_spec",
    });
    expect(fs.existsSync(path.join(tmpRoot, ".docker-agent/secrets/bad-db.env"))).toBe(false);
  });

  test("stages provided config file content", async () => {
    const ctx = makeCtx(tmpRoot);
    const result = await drain(
      planStack.call(
        {
          stackName: "web",
          intent: "nginx proxy",
          services: {
            nginx: { image: "nginx:1.27", volumes: ["./nginx.conf:/etc/nginx/nginx.conf"] },
          },
          configFiles: { "./nginx.conf": "events {}\n" },
        },
        ctx,
      ),
    );
    if (result.blocked) throw new Error("plan should not be blocked");
    expect(result.configFiles).toEqual([{ path: "nginx.conf", content: "events {}\n", bytes: 10 }]);
    // staging must not write to disk yet
    expect(fs.existsSync(path.join(tmpRoot, "nginx.conf"))).toBe(false);
  });

  test("blocks a file bind with no content and no host file", async () => {
    const ctx = makeCtx(tmpRoot);
    const result = await drain(
      planStack.call(
        {
          stackName: "web",
          intent: "nginx proxy",
          services: {
            nginx: { image: "nginx:1.27", volumes: ["./nginx.conf:/etc/nginx/nginx.conf"] },
          },
        },
        ctx,
      ),
    );
    expect(result).toMatchObject({
      blocked: true,
      reason: "invalid_spec",
    });
  });

  test("blocks on an unsafe config file path", async () => {
    const ctx = makeCtx(tmpRoot);
    const result = await drain(
      planStack.call(
        {
          stackName: "web",
          intent: "x",
          services: {
            nginx: { image: "nginx:1.27", volumes: ["./nginx.conf:/etc/nginx/nginx.conf"] },
          },
          configFiles: { "../evil.conf": "x" },
        },
        ctx,
      ),
    );
    expect(result).toMatchObject({
      blocked: true,
      reason: "invalid_spec",
    });
  });

  test("blocks missing dependency before writing secrets", async () => {
    const ctx = makeCtx(tmpRoot);
    const result = await drain(
      planStack.call(
        {
          stackName: "app",
          intent: "api",
          services: { api: { image: "example/api:1", depends_on: ["db"] } },
        },
        ctx,
      ),
    );
    expect(result).toMatchObject({
      blocked: true,
      reason: "invalid_dependency",
      dependency: { valid: false },
    });
    expect(fs.readdirSync(path.join(tmpRoot, ".docker-agent/secrets"))).toHaveLength(0);
  });

  test("blocks dependency cycle before writing secrets", async () => {
    const ctx = makeCtx(tmpRoot);
    const result = await drain(
      planStack.call(
        {
          stackName: "app",
          intent: "workers",
          services: {
            api: { image: "example/api:1", depends_on: ["worker"] },
            worker: { image: "example/worker:1", depends_on: ["api"] },
          },
        },
        ctx,
      ),
    );
    expect(result).toMatchObject({
      blocked: true,
      reason: "invalid_dependency",
      dependency: { valid: false },
    });
    expect(fs.readdirSync(path.join(tmpRoot, ".docker-agent/secrets"))).toHaveLength(0);
  });

  test("blocks running-container port collision before writing secrets", async () => {
    const engine = new MockDockerEngine();
    engine.containers.push({
      Id: "existing",
      Names: ["/existing"],
      State: "running",
      Labels: {},
    });
    engine.inspectById.set("existing", {
      NetworkSettings: {
        Ports: { "80/tcp": [{ HostIp: "0.0.0.0", HostPort: "8080" }] },
      },
    });
    const ctx = makeCtx(tmpRoot);
    ctx.dockerEngine = engine as never;

    const result = await drain(
      planStack.call(
        {
          stackName: "app",
          intent: "api",
          services: { api: { image: "example/api:1", ports: ["8080:80"] } },
        },
        ctx,
      ),
    );
    expect(result).toMatchObject({
      blocked: true,
      reason: "port_conflict",
    });
    expect(fs.readdirSync(path.join(tmpRoot, ".docker-agent/secrets"))).toHaveLength(0);
  });
});
