import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import type { ToolContext } from "src/Tool";
import type { ComposeRunner } from "src/services/docker/composeRunner";
import type { ImageValidator } from "src/services/docker/imageValidator";
import { StateStore } from "src/state/StateStore";
import { planStack } from "src/tools/planStack";
import { beforeEach, describe, expect, test } from "vitest";
import { parse as parseYaml } from "yaml";
import { MockComposeRunner } from "../../../tests/mocks/mockComposeRunner";
import { MockDockerEngine } from "../../../tests/mocks/mockDockerEngine";

async function drain<T, R>(gen: AsyncGenerator<T, R>): Promise<R> {
  let r: IteratorResult<T, R>;
  while (true) {
    r = await gen.next();
    if (r.done) return r.value;
  }
}

function makeCtx(tmpRoot: string): ToolContext {
  const store = new StateStore(path.join(tmpRoot, ".docker-agent"));
  return {
    cwd: tmpRoot,
    stateStore: store,
    dockerEngine: new MockDockerEngine() as never,
    composeRunner: new MockComposeRunner() as unknown as ComposeRunner,
    abortSignal: new AbortController().signal,
  };
}

function invalidImageValidator(image: string): ImageValidator {
  return {
    validateImage: async () => ({
      image,
      status: "invalid",
      source: "registry",
      error: "manifest not found",
      suggestion: "postgres:16-alpine",
    }),
    validateImages: async () => [
      {
        image,
        status: "invalid",
        source: "registry",
        error: "manifest not found",
        suggestion: "postgres:16-alpine",
      },
    ],
  };
}

describe("plan_stack", () => {
  let tmpRoot: string;

  beforeEach(() => {
    tmpRoot = fs.mkdtempSync(path.join(os.tmpdir(), "plan-"));
  });

  test("simple nginx -> composeYaml + empty diff", async () => {
    const ctx = makeCtx(tmpRoot);
    const result = await drain(
      planStack.call(
        {
          stackName: "test",
          intent: "nginx",
          services: [
            {
              name: "nginx",
              kind: "custom",
              image: "nginx:1.27-alpine",
              exposure: "public",
              hostPort: 8080,
              containerPort: 80,
            },
          ],
        },
        ctx,
      ),
    );

    if (result.blocked) throw new Error("plan should not be blocked");
    expect(result).toMatchObject({
      composeYaml: expect.stringContaining("nginx:1.27-alpine"),
      blocked: false,
    });
    expect(result.composeYaml).toContain("8080:80");
  });

  test("inline secret auto-migrated to generated env_file", async () => {
    const ctx = makeCtx(tmpRoot);
    const result = await drain(
      planStack.call(
        {
          stackName: "s",
          intent: "x",
          services: [
            {
              name: "api",
              kind: "custom",
              image: "node:20",
              environment: { NODE_ENV: "prod", API_KEY: "leakvalue" },
            },
          ],
        },
        ctx,
      ),
    );

    expect(result.blocked).toBe(false);
    if (result.blocked) throw new Error("plan should not be blocked");
    expect(result.composeYaml).not.toContain("leakvalue");
    expect(result.autoGeneratedSecrets).toContainEqual({
      service: "api",
      keys: ["API_KEY"],
    });
    expect(parseYaml(result.composeYaml)["x-docker-agent"].envFileSources).toEqual({
      api: {
        generated: true,
        path: "./.docker-agent/secrets/s-api.env",
        addedKeys: ["API_KEY"],
      },
    });
    const generatedPath = path.join(tmpRoot, ".docker-agent/secrets/s-api.env");
    expect(fs.existsSync(generatedPath)).toBe(true);
    expect(fs.readFileSync(generatedPath, "utf-8")).toContain("API_KEY=leakvalue");
  });

  test("postgres without env_file -> auto-generates POSTGRES_PASSWORD", async () => {
    const ctx = makeCtx(tmpRoot);
    const result = await drain(
      planStack.call(
        {
          stackName: "p",
          intent: "postgres",
          services: [
            {
              name: "db",
              kind: "catalog",
              catalogId: "postgresql:16",
            },
          ],
        },
        ctx,
      ),
    );

    expect(result.blocked).toBe(false);
    if (result.blocked) throw new Error("plan should not be blocked");
    expect(result.autoGeneratedSecrets).toContainEqual({
      service: "db",
      keys: ["POSTGRES_PASSWORD"],
    });
    const file = fs.readFileSync(path.join(tmpRoot, ".docker-agent/secrets/p-db.env"), "utf-8");
    expect(file).toMatch(/POSTGRES_PASSWORD=.{20,}/);
  });

  test("custom image without required-secret policy is not blocked", async () => {
    const ctx = makeCtx(tmpRoot);
    const result = await drain(
      planStack.call(
        {
          stackName: "b",
          intent: "billing",
          services: [
            {
              name: "worker",
              kind: "custom",
              image: "mycorp/billing:1.0",
            },
          ],
        },
        ctx,
      ),
    );

    expect(result.blocked).toBe(false);
    if (result.blocked) throw new Error("plan should not be blocked");
  });

  test("scale field stored as services.<svc>.scale in YAML", async () => {
    const ctx = makeCtx(tmpRoot);
    const result = await drain(
      planStack.call(
        {
          stackName: "scaled",
          intent: "x",
          services: [
            {
              name: "api",
              kind: "custom",
              image: "node:20",
              scale: 2,
            },
          ],
        },
        ctx,
      ),
    );

    if (result.blocked) throw new Error("plan should not be blocked");
    expect(result.composeYaml).toMatch(/api:\s*[\s\S]*scale:\s*2/);
    expect(result.scaleOverrides).toEqual({ api: 2 });
  });

  test("rejects invalid image tags before writing generated secrets", async () => {
    const ctx = makeCtx(tmpRoot);
    ctx.imageValidator = invalidImageValidator("postgres:99-alpine");

    const result = await drain(
      planStack.call(
        {
          stackName: "bad",
          intent: "postgres",
          services: [
            {
              name: "db",
              kind: "custom",
              image: "postgres:99-alpine",
            },
          ],
        },
        ctx,
      ),
    );
    expect(result).toMatchObject({
      blocked: true,
      reason: "invalid_spec",
    });
    expect(fs.existsSync(path.join(tmpRoot, ".docker-agent/secrets/bad-db.env"))).toBe(false);
  });

  test("stages provided config file content", async () => {
    const ctx = makeCtx(tmpRoot);
    const result = await drain(
      planStack.call(
        {
          stackName: "web",
          intent: "nginx proxy",
          services: [
            {
              name: "nginx",
              kind: "custom",
              image: "nginx:1.27",
              configMounts: [{ hostPath: "./nginx.conf", containerPath: "/etc/nginx/nginx.conf" }],
            },
          ],
          configFiles: { "./nginx.conf": "events {}\n" },
        },
        ctx,
      ),
    );
    if (result.blocked) throw new Error("plan should not be blocked");
    expect(result.configFiles).toEqual([
      { path: "nginx.conf", content: "events {}\n", bytes: 10 },
    ]);
    // staging must not write to disk yet
    expect(fs.existsSync(path.join(tmpRoot, "nginx.conf"))).toBe(false);
  });

  test("blocks a file bind with no content and no host file", async () => {
    const ctx = makeCtx(tmpRoot);
    const result = await drain(
      planStack.call(
        {
          stackName: "web",
          intent: "nginx proxy",
          services: [
            {
              name: "nginx",
              kind: "custom",
              image: "nginx:1.27",
              configMounts: [{ hostPath: "./nginx.conf", containerPath: "/etc/nginx/nginx.conf" }],
            },
          ],
        },
        ctx,
      ),
    );
    expect(result).toMatchObject({
      blocked: true,
      reason: "invalid_spec",
    });
  });

  test("blocks on an unsafe config file path", async () => {
    const ctx = makeCtx(tmpRoot);
    const result = await drain(
      planStack.call(
        {
          stackName: "web",
          intent: "x",
          services: [
            {
              name: "nginx",
              kind: "custom",
              image: "nginx:1.27",
              configMounts: [{ hostPath: "./nginx.conf", containerPath: "/etc/nginx/nginx.conf" }],
            },
          ],
          configFiles: { "../evil.conf": "x" },
        },
        ctx,
      ),
    );
    expect(result).toMatchObject({
      blocked: true,
      reason: "invalid_spec",
    });
  });

  test("blocks missing dependency before writing secrets", async () => {
    const ctx = makeCtx(tmpRoot);
    const result = await drain(
      planStack.call(
        {
          stackName: "app",
          intent: "api",
          services: [
            {
              name: "api",
              kind: "custom",
              image: "example/api:1",
              depends_on: ["db"],
            },
          ],
        },
        ctx,
      ),
    );
    expect(result).toMatchObject({
      blocked: true,
      reason: "invalid_dependency",
      dependency: { valid: false },
    });
    expect(fs.readdirSync(path.join(tmpRoot, ".docker-agent/secrets"))).toHaveLength(0);
  });

  test("blocks dependency cycle before writing secrets", async () => {
    const ctx = makeCtx(tmpRoot);
    const result = await drain(
      planStack.call(
        {
          stackName: "app",
          intent: "workers",
          services: [
            {
              name: "api",
              kind: "custom",
              image: "example/api:1",
              depends_on: ["worker"],
            },
            {
              name: "worker",
              kind: "custom",
              image: "example/worker:1",
              depends_on: ["api"],
            },
          ],
        },
        ctx,
      ),
    );
    expect(result).toMatchObject({
      blocked: true,
      reason: "invalid_dependency",
      dependency: { valid: false },
    });
    expect(fs.readdirSync(path.join(tmpRoot, ".docker-agent/secrets"))).toHaveLength(0);
  });

  test("auto-replaces weak POSTGRES_PASSWORD with generated value", async () => {
    const ctx = makeCtx(tmpRoot);
    const result = await drain(
      planStack.call(
        {
          stackName: "weakpw",
          intent: "postgres with weak password",
          services: [
            {
              name: "db",
              kind: "catalog",
              catalogId: "postgresql:16",
              environment: { POSTGRES_PASSWORD: "postgres" },
            },
          ],
        },
        ctx,
      ),
    );

    if (result.blocked) throw new Error("plan should not be blocked");
    expect(result.autoGeneratedSecrets).toEqual(
      expect.arrayContaining([
        expect.objectContaining({ service: "db", keys: ["POSTGRES_PASSWORD"] }),
      ]),
    );

    const envPath = path.join(tmpRoot, ".docker-agent", "secrets", "weakpw-db.env");
    const envContent = fs.readFileSync(envPath, "utf-8");
    expect(envContent).not.toContain("POSTGRES_PASSWORD=postgres");
    expect(envContent).toMatch(/POSTGRES_PASSWORD=.+/);
  });

  test("blocks when service count exceeds limit", async () => {
    const ctx = makeCtx(tmpRoot);
    const services: any[] = [];
    for (let i = 0; i <= 25; i++) {
      services.push({
        name: `svc${i}`,
        kind: "custom",
        image: "nginx:1.27-alpine",
      });
    }
    const result = await drain(
      planStack.call({ stackName: "toobig", intent: "too many services", services }, ctx),
    );
    expect(result.blocked).toBe(true);
    if (result.blocked) expect(result.reason).toBe("resource_limit");
  });

  test("blocks postgres 5432 published to host", async () => {
    const ctx = makeCtx(tmpRoot);
    const result = await drain(
      planStack.call(
        {
          stackName: "dbexposed",
          intent: "postgres exposed",
          services: [
            {
              name: "db",
              kind: "catalog",
              catalogId: "postgresql:16",
              exposure: "public",
              hostPort: 5432,
            },
          ],
        },
        ctx,
      ),
    );
    expect(result.blocked).toBe(true);
    if (result.blocked) expect(result.reason).toBe("db_port_exposed");
  });

  test("blocks path traversal in config file mount", async () => {
    const ctx = makeCtx(tmpRoot);
    const result = await drain(
      planStack.call(
        {
          stackName: "traversal",
          intent: "path traversal",
          services: [
            {
              name: "web",
              kind: "custom",
              image: "nginx:1.27-alpine",
              configMounts: [{ hostPath: "../../etc", containerPath: "/etc:ro" }],
            },
          ],
        },
        ctx,
      ),
    );
    expect(result.blocked).toBe(true);
    if (result.blocked) expect(result.reason).toBe("unsafe_volume");
  });

  test("blocks running-container port collision before writing secrets", async () => {
    const engine = new MockDockerEngine();
    engine.containers.push({
      Id: "existing",
      Names: ["/existing"],
      State: "running",
      Labels: {},
    });
    engine.inspectById.set("existing", {
      NetworkSettings: {
        Ports: { "80/tcp": [{ HostIp: "0.0.0.0", HostPort: "8080" }] },
      },
    });
    const ctx = makeCtx(tmpRoot);
    ctx.dockerEngine = engine as never;

    const result = await drain(
      planStack.call(
        {
          stackName: "app",
          intent: "api",
          services: [
            {
              name: "api",
              kind: "custom",
              image: "example/api:1",
              exposure: "public",
              hostPort: 8080,
            },
          ],
        },
        ctx,
      ),
    );
    expect(result).toMatchObject({
      blocked: true,
      reason: "port_conflict",
    });
    expect(fs.readdirSync(path.join(tmpRoot, ".docker-agent/secrets"))).toHaveLength(0);
  });

  test("custom network name generated when networkName is provided", async () => {
    const ctx = makeCtx(tmpRoot);
    const result = await drain(
      planStack.call(
        {
          stackName: "test-net",
          intent: "nginx",
          networkName: "custom-wp-net",
          services: [
            {
              name: "nginx",
              kind: "custom",
              image: "nginx:1.27-alpine",
            },
          ],
        },
        ctx,
      ),
    );

    if (result.blocked) throw new Error("plan should not be blocked");
    expect(result.composeYaml).toContain("custom-wp-net");
    const parsed = parseYaml(result.composeYaml);
    expect(parsed.networks?.default?.name).toBe("custom-wp-net");
  });

  test("volume name does not contain stackName prefix in generated YAML", async () => {
    const ctx = makeCtx(tmpRoot);
    const result = await drain(
      planStack.call(
        {
          stackName: "my-stack",
          intent: "mysql",
          services: [
            {
              name: "db",
              kind: "catalog",
              catalogId: "mysql:8.0",
              persistence: {
                size: "10Gi",
              },
            },
          ],
        },
        ctx,
      ),
    );

    if (result.blocked) throw new Error("plan should not be blocked");
    const parsed = parseYaml(result.composeYaml);
    expect(parsed.volumes?.db_data).toBeDefined();
    expect(parsed.volumes?.["my-stack_db_data"]).toBeUndefined();
    expect(parsed.services?.db?.volumes?.[0]).toContain("db_data:");
  });

  test("auto-injects database healthcheck and upgrades depends_on in composeYaml", async () => {
    const ctx = makeCtx(tmpRoot);
    const result = await drain(
      planStack.call(
        {
          stackName: "webapp-stack",
          intent: "wordpress + mysql",
          services: [
            {
              name: "db",
              kind: "custom",
              image: "mysql:8.0",
              environment: {
                MYSQL_ROOT_PASSWORD: "secretpassword",
              },
            },
            {
              name: "web",
              kind: "custom",
              image: "wordpress:latest",
              depends_on: ["db"],
            },
          ],
        },
        ctx,
      ),
    );

    if (result.blocked) throw new Error("plan should not be blocked");
    const parsed = parseYaml(result.composeYaml);

    expect(parsed.services?.db?.healthcheck).toBeDefined();
    expect(parsed.services?.db?.healthcheck?.test).toEqual(["CMD", "mysqladmin", "ping", "-h", "localhost"]);
    expect(parsed.services?.db?.healthcheck?.start_period).toBe("30s");

    expect(parsed.services?.web?.depends_on).toEqual({
      db: { condition: "service_healthy" },
    });
  });
});
