import type { StructuredLogger } from "src/state/logger";
import type { PermissionResponse } from "src/types/permissions";
import type { StackDiff } from "src/types/stack";
import type { ToolContext } from "./Tool";

export interface PlanReadyPayload {
  composeYaml: string;
  diff: StackDiff;
  autoGeneratedSecrets?: Array<{ service: string; keys: string[] }>;
  configFiles?: Array<{ path: string; content: string; bytes: number }>;
  hash?: string;
}

export interface LoopContext extends ToolContext {
  requestPermission(tool: string, input: unknown): Promise<PermissionResponse>;
  requestConfirm(plan: PlanReadyPayload): Promise<PermissionResponse>;
  requestTypedConfirm(phrase: string, reason: string): Promise<PermissionResponse>;
  requestSecretsInput(service: string, keys: string[], reason: string): Promise<PermissionResponse>;
  allowSet: Set<string>;
  logger?: StructuredLogger;
}
