import { nanoid } from "nanoid";
import type { LoopContext, PlanReadyPayload } from "src/loopContext";
import type { Provider } from "src/services/api/types";
import type { ComposeRunner } from "src/services/docker/composeRunner";
import type { EngineClient } from "src/services/docker/engineClient";
import type { SessionRecord, SessionStore } from "src/state/SessionStore";
import type { StateStore } from "src/state/StateStore";
import type { LoopEvent } from "src/types/events";
import type { Message } from "src/types/message";
import type { PermissionResponse } from "src/types/permissions";
import type { StackDiff } from "src/types/stack";
import { query } from "./query";
import { AsyncQueue } from "./utils/AsyncQueue";

export interface QueryEngineDeps {
  cwd: string;
  stateStore: StateStore;
  sessionStore?: SessionStore; // optional — if absent, session is not persisted
  dockerEngine: EngineClient;
  composeRunner: ComposeRunner;
  provider: Provider;
  model?: string;
  /** Override health-check deadline (ms). Defaults to 120 000 ms. Used in tests. */
  healthCheckDeadlineMs?: number;
}

type DeferredBase =
  | { type: "permission_request"; tool: string; input: unknown }
  | {
      type: "plan_ready";
      composeYaml: string;
      diff: StackDiff;
      autoGeneratedSecrets?: Array<{ service: string; keys: string[] }>;
      configFiles?: Array<{ path: string; content: string; bytes: number }>;
    }
  | { type: "typed_confirm_request"; phrase: string; reason: string }
  | { type: "secrets_input_request"; service: string; keys: string[]; reason: string };

export class QueryEngine {
  private messages: Message[] = [];
  private pending = new Map<string, (v: PermissionResponse) => void>();
  private sessionAllowSet = new Set<string>();
  private abortController = new AbortController();
  private _sessionId: string = nanoid();
  private resumedId: string | null = null;
  public provider: Provider;
  public model: string | undefined;
  public totalUsage = { inputTokens: 0, outputTokens: 0 };

  constructor(private deps: QueryEngineDeps) {
    this.provider = deps.provider;
    this.model = deps.model;
  }

  get sessionId(): string {
    return this._sessionId;
  }

  /** Rehydrate a prior session record. Must be called before the first query(). */
  loadSession(record: SessionRecord): void {
    if (record.schemaVersion !== 1) return; // guard against bad calls
    this.messages = [...record.messages];
    this.resumedId = record.id;
    this._sessionId = record.id; // continue under same id
    this.pending.clear();
    this.sessionAllowSet.clear(); // permissions are NEVER resumed (safety)
  }

  /** Returns current messages for REPL repaint after resume. */
  getMessages(): readonly Message[] {
    return this.messages;
  }

  async *query(userInput: string): AsyncGenerator<LoopEvent, void> {
    this.messages.push({ role: "user", content: userInput });
    const eventQueue = new AsyncQueue<LoopEvent>();

    const ctx: LoopContext = {
      cwd: this.deps.cwd,
      stateStore: this.deps.stateStore,
      dockerEngine: this.deps.dockerEngine,
      composeRunner: this.deps.composeRunner,
      abortSignal: this.abortController.signal,
      sessionId: this._sessionId,
      ...(this.deps.healthCheckDeadlineMs !== undefined
        ? { healthCheckDeadlineMs: this.deps.healthCheckDeadlineMs }
        : {}),
      requestPermission: (tool, input) =>
        this.deferUserResponse(eventQueue, { type: "permission_request", tool, input }),
      requestConfirm: (plan: PlanReadyPayload) =>
        this.deferUserResponse(eventQueue, {
          type: "plan_ready",
          composeYaml: plan.composeYaml,
          diff: plan.diff,
          ...(plan.autoGeneratedSecrets ? { autoGeneratedSecrets: plan.autoGeneratedSecrets } : {}),
          ...(plan.configFiles ? { configFiles: plan.configFiles } : {}),
        }),
      requestTypedConfirm: (phrase, reason) =>
        this.deferUserResponse(eventQueue, { type: "typed_confirm_request", phrase, reason }),
      requestSecretsInput: (service, keys, reason) =>
        this.deferUserResponse(eventQueue, {
          type: "secrets_input_request",
          service,
          keys,
          reason,
        }),
      allowSet: this.sessionAllowSet,
    };

    const loopPromise = (async () => {
      try {
        for await (const ev of query({
          messages: this.messages,
          ctx,
          provider: this.provider,
          ...(this.model ? { model: this.model } : {}),
        })) {
          eventQueue.push(ev);
        }
      } catch (err) {
        eventQueue.push({ type: "error", error: err as Error });
      } finally {
        eventQueue.close();
        for (const [, resolve] of this.pending) resolve({ kind: "deny" });
        this.pending.clear();
      }
    })();

    try {
      for await (const ev of eventQueue) {
        if (ev.type === "usage") {
          this.totalUsage.inputTokens += ev.inputTokens;
          this.totalUsage.outputTokens += ev.outputTokens;
        }
        yield ev;
      }
    } finally {
      this.abortController.abort();
      await loopPromise.catch(() => {});
      // Persist transcript after turn ends
      if (this.deps.sessionStore) {
        const firstUserMsg = this.messages.find((m) => m.role === "user");
        const firstPrompt = firstUserMsg?.role === "user" ? firstUserMsg.content : "(empty)";
        this.deps.sessionStore.save({
          schemaVersion: 1,
          id: this._sessionId,
          createdAt: new Date().toISOString(), // SessionStore.save will update updatedAt on overwrite
          updatedAt: new Date().toISOString(),
          cwd: this.deps.cwd,
          provider:
            typeof this.provider === "object" && "name" in this.provider
              ? (this.provider as { name: string }).name
              : "unknown",
          firstPrompt,
          stackNames: [],
          messages: this.messages,
        });
      }
    }
  }

  respondTo(id: string, answer: PermissionResponse): boolean {
    const resolver = this.pending.get(id);
    if (!resolver) return false;
    this.pending.delete(id);
    resolver(answer);
    return true;
  }

  abort(): void {
    this.abortController.abort();
    this.abortController = new AbortController();
  }

  reset(): void {
    this.messages = [];
    this.pending.clear();
    this.sessionAllowSet.clear();
    this.abortController = new AbortController();
  }

  private deferUserResponse(
    queue: AsyncQueue<LoopEvent>,
    base: DeferredBase,
  ): Promise<PermissionResponse> {
    const id = nanoid();
    queue.push({ ...base, id } as LoopEvent);
    return new Promise((resolve) => {
      this.pending.set(id, resolve);
    });
  }
}
