import type { Message, AssistantBlock } from "src/types/message";
import type { LoopEvent } from "src/types/events";
import type { LoopContext } from "src/loopContext";
import type { Provider } from "src/services/api/types";
import { classifyIntent, buildSystemPrompt } from "./context";
import { getToolsForMode, type QueryMode } from "./tools";
import { applyStack } from "./tools/applyStack";
import { planStack } from "./tools/planStack";
import { destroyAllStacks } from "./tools/destroyAllStacks";
import { findToolByName, type Tool } from "./Tool";

export interface QueryParams {
  messages: Message[];
  ctx: LoopContext;
  provider: Provider;
}

interface CollectedToolUse {
  id: string;
  name: string;
  argsPartial: string;
}

async function* runProvider(
  provider: Provider,
  messages: Message[],
  mode: QueryMode,
  ctx: LoopContext,
): AsyncGenerator<LoopEvent, { text: string; toolUses: CollectedToolUse[] }> {
  const tools = getToolsForMode(mode);
  const system = buildSystemPrompt(mode, ctx.stateStore.summary());
  const provEvents = provider.stream({
    messages,
    tools: tools.map((t) => ({
      name: t.name,
      description: t.description,
      inputSchema: t.inputSchema,
    })),
    system,
  });
  let text = "";
  const toolUses: CollectedToolUse[] = [];
  for await (const ev of provEvents) {
    switch (ev.type) {
      case "text_delta":
        text += ev.text;
        yield { type: "assistant_text", delta: ev.text };
        break;
      case "tool_use_start":
        toolUses.push({ id: ev.id, name: ev.name, argsPartial: "" });
        break;
      case "tool_use_delta": {
        const u = toolUses.find((t) => t.id === ev.id);
        if (u) u.argsPartial += ev.argsPartialJson;
        break;
      }
      case "tool_use_stop":
        break;
      case "error":
        yield { type: "error", error: ev.error };
        break;
      case "message_stop":
        return { text, toolUses };
      case "usage":
        break;
    }
  }
  return { text, toolUses };
}

async function* runTool<TIn, TOut>(
  tool: Tool<TIn, TOut>,
  input: TIn,
  ctx: LoopContext,
): AsyncGenerator<LoopEvent, TOut> {
  yield { type: "tool_call", name: tool.name, input };
  const gen = tool.call(input, ctx);
  let result: TOut;
  while (true) {
    const r = await gen.next();
    if (r.done) {
      result = r.value;
      break;
    }
    yield { type: "tool_progress", msg: r.value.msg };
  }
  yield { type: "tool_result", name: tool.name, output: result };
  return result;
}

function assistantBlocksFromCollected(
  text: string,
  toolUses: CollectedToolUse[],
): AssistantBlock[] {
  const blocks: AssistantBlock[] = [];
  if (text) blocks.push({ type: "text", text });
  for (const tu of toolUses) {
    let input: unknown = {};
    try {
      input = JSON.parse(tu.argsPartial || "{}");
    } catch {
      /* keep {} */
    }
    blocks.push({ type: "tool_use", id: tu.id, name: tu.name, input });
  }
  return blocks;
}

async function* handlePlanStackToolUse(
  tu: CollectedToolUse,
  ctx: LoopContext,
): AsyncGenerator<LoopEvent, { applied: boolean; resultMessage: string }> {
  let parsed: unknown = (() => {
    try {
      return planStack.inputSchema.parse(JSON.parse(tu.argsPartial || "{}"));
    } catch (err) {
      return { _error: (err as Error).message };
    }
  })();

  while (true) {
    if ((parsed as { _error?: string })._error) {
      return {
        applied: false,
        resultMessage: `plan_stack validation failed: ${(parsed as { _error: string })._error}`,
      };
    }
    const reParsed = planStack.inputSchema.parse(parsed);
    const planResult = yield* runTool(planStack, reParsed, ctx);
    if (planResult.blocked) {
      let injected: Record<string, string[]> = planResult.missingByService;
      for (const [service, keys] of Object.entries(injected)) {
        const resp = yield* requestSecretsAndPatch(service, keys, ctx, parsed as never);
        if (resp === null) {
          return { applied: false, resultMessage: "User cancelled secrets input." };
        }
        parsed = resp.patchedInput as typeof parsed;
      }
      continue;
    }

    yield {
      type: "plan_ready",
      id: "auto",
      composeYaml: planResult.composeYaml,
      diff: planResult.diff,
      ...(planResult.autoGeneratedSecrets.length
        ? { autoGeneratedSecrets: planResult.autoGeneratedSecrets }
        : {}),
    };
    const confirm = await ctx.requestConfirm({
      composeYaml: planResult.composeYaml,
      diff: planResult.diff,
      ...(planResult.autoGeneratedSecrets.length
        ? { autoGeneratedSecrets: planResult.autoGeneratedSecrets }
        : {}),
    });
    if (confirm.kind !== "approve") {
      return { applied: false, resultMessage: "User declined plan." };
    }
    yield* runTool(applyStack, {
      stackName: (parsed as { stackName: string }).stackName,
      composeYaml: planResult.composeYaml,
      ...(Object.keys(planResult.scaleOverrides).length
        ? { scaleOverrides: planResult.scaleOverrides }
        : {}),
    }, ctx);
    return { applied: true, resultMessage: "Stack applied." };
  }
}

async function* requestSecretsAndPatch(
  service: string,
  keys: string[],
  ctx: LoopContext,
  currentInput: unknown,
): AsyncGenerator<LoopEvent, { patchedInput: unknown } | null> {
  const resp = await ctx.requestSecretsInput(service, keys, "missing required env");
  if (resp.kind !== "secrets_input_values") return null;
  const input = currentInput as {
    stackName: string;
    services: Record<string, { env_file?: string[]; environment?: Record<string, string> }>;
  };
  const fs = await import("node:fs");
  const path = await import("node:path");
  const secretsDir = path.join(ctx.cwd, ".docker-agent", "secrets");
  fs.mkdirSync(secretsDir, { recursive: true });
  const file = path.join(secretsDir, `${input.stackName}-${service}.env`);
  const lines = Object.entries(resp.values)
    .map(([k, v]) => `${k}=${v}`)
    .join("\n") + "\n";
  fs.writeFileSync(file, lines, { mode: 0o600 });
  const rel = `./.docker-agent/secrets/${input.stackName}-${service}.env`;
  const svc = input.services[service];
  if (svc) {
    svc.env_file = svc.env_file ?? [];
    if (!svc.env_file.includes(rel)) svc.env_file.push(rel);
  }
  return { patchedInput: input };
}

export async function* query(params: QueryParams): AsyncGenerator<LoopEvent, void> {
  const { ctx, provider } = params;
  const messages = [...params.messages];
  const lastUser = [...messages]
    .reverse()
    .find((m): m is { role: "user"; content: string } => m.role === "user");
  const mode = lastUser ? classifyIntent(lastUser.content) : "react";
  const maxIterations = mode === "plan-once" ? 1 : 8;

  for (let iter = 0; iter < maxIterations; iter++) {
    yield { type: "iteration_start", n: iter + 1 };
    const stream = runProvider(provider, messages, mode, ctx);
    let collected: { text: string; toolUses: CollectedToolUse[] } = { text: "", toolUses: [] };
    while (true) {
      const r = await stream.next();
      if (r.done) {
        collected = r.value;
        break;
      }
      yield r.value;
    }
    messages.push({
      role: "assistant",
      content: assistantBlocksFromCollected(collected.text, collected.toolUses),
    });
    if (collected.toolUses.length === 0) return;

    for (const tu of collected.toolUses) {
      if (tu.name === "plan_stack") {
        const r = yield* handlePlanStackToolUse(tu, ctx);
        messages.push({
          role: "tool",
          toolUseId: tu.id,
          content: r.resultMessage,
          isError: false,
        });
        if (mode === "plan-once") return;
        continue;
      }
      if (tu.name === "destroy_all_stacks") {
        const typed = await ctx.requestTypedConfirm(
          "DESTROY ALL",
          `This will destroy ${ctx.stateStore.list().length} stacks.`,
        );
        if (typed.kind !== "typed_confirm_value" || typed.value !== "DESTROY ALL") {
          messages.push({
            role: "tool",
            toolUseId: tu.id,
            content: "destroy_all aborted: typed confirmation did not match",
            isError: false,
          });
          continue;
        }
        let parsed: unknown = {};
        try {
          parsed = destroyAllStacks.inputSchema.parse(JSON.parse(tu.argsPartial || "{}"));
        } catch {
          /* fall through */
        }
        const result = yield* runTool(destroyAllStacks, parsed as never, ctx);
        messages.push({
          role: "tool",
          toolUseId: tu.id,
          content: JSON.stringify(result),
          isError: false,
        });
        continue;
      }
      const tool = findToolByName(getToolsForMode(mode), tu.name);
      if (!tool) {
        messages.push({
          role: "tool",
          toolUseId: tu.id,
          content: `unknown tool: ${tu.name}`,
          isError: true,
        });
        continue;
      }
      let parsed: unknown = {};
      try {
        parsed = tool.inputSchema.parse(JSON.parse(tu.argsPartial || "{}"));
      } catch (err) {
        messages.push({
          role: "tool",
          toolUseId: tu.id,
          content: `validation failed: ${(err as Error).message}`,
          isError: true,
        });
        continue;
      }
      if (tool.needsPermission(parsed)) {
        if (!ctx.allowSet.has(tool.name)) {
          const resp = await ctx.requestPermission(tool.name, parsed);
          if (resp.kind === "deny") {
            messages.push({
              role: "tool",
              toolUseId: tu.id,
              content: "User denied permission.",
              isError: false,
            });
            continue;
          }
          if (resp.kind === "always_allow_in_session") ctx.allowSet.add(tool.name);
        }
      }
      const result = yield* runTool(tool as Tool, parsed, ctx);
      messages.push({
        role: "tool",
        toolUseId: tu.id,
        content: JSON.stringify(result),
        isError: false,
      });
    }

    if (mode === "plan-once") return;
  }
  yield { type: "error", error: new Error("max iterations reached") };
}