import { nanoid } from "nanoid";
import type { LoopContext, PlanReadyPayload } from "src/loopContext";
import type { Provider } from "src/services/api/types";
import type { ComposeRunner } from "src/services/docker/composeRunner";
import type { EngineClient } from "src/services/docker/engineClient";
import type { StateStore } from "src/state/StateStore";
import type { LoopEvent } from "src/types/events";
import type { Message } from "src/types/message";
import type { PermissionResponse } from "src/types/permissions";
import type { StackDiff } from "src/types/stack";
import { query } from "./query";
import { AsyncQueue } from "./utils/AsyncQueue";

export interface QueryEngineDeps {
  cwd: string;
  stateStore: StateStore;
  dockerEngine: EngineClient;
  composeRunner: ComposeRunner;
  provider: Provider;
  model?: string;
}

type DeferredBase =
  | { type: "permission_request"; tool: string; input: unknown }
  | {
      type: "plan_ready";
      composeYaml: string;
      diff: StackDiff;
      autoGeneratedSecrets?: Array<{ service: string; keys: string[] }>;
    }
  | { type: "typed_confirm_request"; phrase: string; reason: string }
  | { type: "secrets_input_request"; service: string; keys: string[]; reason: string };

export class QueryEngine {
  private messages: Message[] = [];
  private pending = new Map<string, (v: PermissionResponse) => void>();
  private sessionAllowSet = new Set<string>();
  private abortController = new AbortController();
  public provider: Provider;
  public model: string | undefined;
  public totalUsage = { inputTokens: 0, outputTokens: 0 };

  constructor(private deps: QueryEngineDeps) {
    this.provider = deps.provider;
    this.model = deps.model;
  }

  async *query(userInput: string): AsyncGenerator<LoopEvent, void> {
    this.messages.push({ role: "user", content: userInput });
    const eventQueue = new AsyncQueue<LoopEvent>();

    const ctx: LoopContext = {
      cwd: this.deps.cwd,
      stateStore: this.deps.stateStore,
      dockerEngine: this.deps.dockerEngine,
      composeRunner: this.deps.composeRunner,
      abortSignal: this.abortController.signal,
      requestPermission: (tool, input) =>
        this.deferUserResponse(eventQueue, { type: "permission_request", tool, input }),
      requestConfirm: (plan: PlanReadyPayload) =>
        this.deferUserResponse(eventQueue, {
          type: "plan_ready",
          composeYaml: plan.composeYaml,
          diff: plan.diff,
          ...(plan.autoGeneratedSecrets ? { autoGeneratedSecrets: plan.autoGeneratedSecrets } : {}),
        }),
      requestTypedConfirm: (phrase, reason) =>
        this.deferUserResponse(eventQueue, { type: "typed_confirm_request", phrase, reason }),
      requestSecretsInput: (service, keys, reason) =>
        this.deferUserResponse(eventQueue, {
          type: "secrets_input_request",
          service,
          keys,
          reason,
        }),
      allowSet: this.sessionAllowSet,
    };

    const loopPromise = (async () => {
      try {
        for await (const ev of query({
          messages: this.messages,
          ctx,
          provider: this.provider,
          ...(this.model ? { model: this.model } : {}),
        })) {
          eventQueue.push(ev);
        }
      } catch (err) {
        eventQueue.push({ type: "error", error: err as Error });
      } finally {
        eventQueue.close();
        for (const [, resolve] of this.pending) resolve({ kind: "deny" });
        this.pending.clear();
      }
    })();

    try {
      for await (const ev of eventQueue) {
        if (ev.type === "usage") {
          this.totalUsage.inputTokens += ev.inputTokens;
          this.totalUsage.outputTokens += ev.outputTokens;
        }
        yield ev;
      }
    } finally {
      this.abortController.abort();
      await loopPromise.catch(() => {});
    }
  }

  respondTo(id: string, answer: PermissionResponse): boolean {
    const resolver = this.pending.get(id);
    if (!resolver) return false;
    this.pending.delete(id);
    resolver(answer);
    return true;
  }

  abort(): void {
    this.abortController.abort();
    this.abortController = new AbortController();
  }

  reset(): void {
    this.messages = [];
    this.pending.clear();
    this.sessionAllowSet.clear();
    this.abortController = new AbortController();
  }

  private deferUserResponse(
    queue: AsyncQueue<LoopEvent>,
    base: DeferredBase,
  ): Promise<PermissionResponse> {
    const id = nanoid();
    queue.push({ ...base, id } as LoopEvent);
    return new Promise((resolve) => {
      this.pending.set(id, resolve);
    });
  }
}
