import { nanoid } from "nanoid";
import type { LoopContext, PlanReadyPayload } from "src/loopContext";
import type { Provider } from "src/services/api/types";
import type { ComposeRunner } from "src/services/docker/composeRunner";
import type { EngineClient } from "src/services/docker/engineClient";
import {
  type SessionRecord,
  type SessionStore,
  sessionCwdMismatchWarning,
} from "src/state/SessionStore";
import type { StateStore } from "src/state/StateStore";
import type { LogEntry, StructuredLogger } from "src/state/logger";
import type { LoopEvent } from "src/types/events";
import type { Message } from "src/types/message";
import type { PermissionResponse } from "src/types/permissions";
import type { StackDiff } from "src/types/stack";
import { query } from "./query";
import { AsyncQueue } from "./utils/AsyncQueue";

export interface QueryEngineDeps {
  cwd: string;
  stateStore: StateStore;
  sessionStore?: SessionStore; // optional — if absent, session is not persisted
  dockerEngine: EngineClient;
  composeRunner: ComposeRunner;
  provider: Provider;
  model?: string;
  /** Override health-check deadline (ms). Defaults to 120 000 ms. Used in tests. */
  healthCheckDeadlineMs?: number;
}

type DeferredBase =
  | { type: "permission_request"; tool: string; input: unknown }
  | {
      type: "plan_ready";
      composeYaml: string;
      diff: StackDiff;
      autoGeneratedSecrets?: Array<{ service: string; keys: string[] }>;
      configFiles?: Array<{ path: string; content: string; bytes: number }>;
    }
  | { type: "typed_confirm_request"; phrase: string; reason: string }
  | { type: "secrets_input_request"; service: string; keys: string[]; reason: string };

export class QueryEngine {
  private messages: Message[] = [];
  private pending = new Map<string, (v: PermissionResponse) => void>();
  private sessionAllowSet = new Set<string>();
  private activeController: AbortController | null = null;
  private _sessionId: string = nanoid();
  private resumedId: string | null = null;
  private sessionCreatedAt: string | null = null;
  public provider: Provider;
  public model: string | undefined;
  public totalUsage = { inputTokens: 0, outputTokens: 0 };
  private logger: StructuredLogger | null = null;
  private currentIteration = 0;

  constructor(private deps: QueryEngineDeps) {
    this.provider = deps.provider;
    this.model = deps.model;
  }

  get sessionId(): string {
    return this._sessionId;
  }

  /** Whether this engine continued an existing persisted session. */
  get isResumed(): boolean {
    return this.resumedId !== null;
  }

  /** Rehydrate a prior session record. Must be called before the first query(). */
  loadSession(record: SessionRecord): string | undefined {
    if (record.schemaVersion !== 1) return undefined;
    this.messages = [...record.messages];
    this.resumedId = record.id;
    this._sessionId = record.id;
    this.sessionCreatedAt = record.createdAt;
    if (record.model !== undefined) {
      this.model = record.model;
    }
    this.pending.clear();
    this.sessionAllowSet.clear(); // permissions are NEVER resumed (safety)
    const warning = sessionCwdMismatchWarning(record, this.deps.cwd);
    if (warning) {
      process.stderr.write(`[docker-agent] ${warning}\n`);
    }
    return warning;
  }

  /** Returns current messages for REPL repaint after resume. */
  getMessages(): readonly Message[] {
    return this.messages;
  }

  setLogger(logger: StructuredLogger): void {
    this.logger = logger;
  }

  async *query(userInput: string): AsyncGenerator<LoopEvent, void> {
    const controller = new AbortController();
    this.activeController = controller;
    this.messages.push({ role: "user", content: userInput });
    this.logger?.log({
      ts: new Date().toISOString(),
      level: "info",
      sessionId: this._sessionId,
      category: "turn_start",
      message: userInput,
    });
    const eventQueue = new AsyncQueue<LoopEvent>();

    const ctx: LoopContext = {
      cwd: this.deps.cwd,
      stateStore: this.deps.stateStore,
      dockerEngine: this.deps.dockerEngine,
      composeRunner: this.deps.composeRunner,
      abortSignal: controller.signal,
      sessionId: this._sessionId,
      ...(this.deps.healthCheckDeadlineMs !== undefined
        ? { healthCheckDeadlineMs: this.deps.healthCheckDeadlineMs }
        : {}),
      requestPermission: (tool, input) =>
        this.deferUserResponse(eventQueue, { type: "permission_request", tool, input }),
      requestConfirm: (plan: PlanReadyPayload) =>
        this.deferUserResponse(eventQueue, {
          type: "plan_ready",
          composeYaml: plan.composeYaml,
          diff: plan.diff,
          ...(plan.autoGeneratedSecrets ? { autoGeneratedSecrets: plan.autoGeneratedSecrets } : {}),
          ...(plan.configFiles ? { configFiles: plan.configFiles } : {}),
        }),
      requestTypedConfirm: (phrase, reason) =>
        this.deferUserResponse(eventQueue, { type: "typed_confirm_request", phrase, reason }),
      requestSecretsInput: (service, keys, reason) =>
        this.deferUserResponse(eventQueue, {
          type: "secrets_input_request",
          service,
          keys,
          reason,
        }),
      allowSet: this.sessionAllowSet,
      ...(this.logger ? { logger: this.logger } : {}),
    };

    const loopPromise = (async () => {
      try {
        for await (const ev of query({
          messages: this.messages,
          ctx,
          provider: this.provider,
          ...(this.model ? { model: this.model } : {}),
        })) {
          eventQueue.push(ev);
        }
      } catch (err) {
        if (!controller.signal.aborted) {
          eventQueue.push({ type: "error", error: err as Error });
        }
      } finally {
        eventQueue.close();
        for (const [, resolve] of this.pending) resolve({ kind: "deny" });
        this.pending.clear();
      }
    })();

    try {
      for await (const ev of eventQueue) {
        if (ev.type === "usage") {
          this.totalUsage.inputTokens += ev.inputTokens;
          this.totalUsage.outputTokens += ev.outputTokens;
        }
        this.logger?.log(this.toLogEntry(ev, this.currentIteration));
        yield ev;
      }
    } finally {
      this.activeController = null;
      await loopPromise.catch(() => {});
      this.logger?.log({
        ts: new Date().toISOString(),
        level: "info",
        sessionId: this._sessionId,
        category: "turn_end",
        message: "turn complete",
      });
      this.logger?.close();
      // Persist transcript after turn ends
      if (this.deps.sessionStore) {
        const now = new Date().toISOString();
        if (this.sessionCreatedAt === null) {
          this.sessionCreatedAt = now;
        }
        const firstUserMsg = this.messages.find((m) => m.role === "user");
        const firstPrompt = firstUserMsg?.role === "user" ? firstUserMsg.content : "(empty)";
        this.deps.sessionStore.save({
          schemaVersion: 1,
          id: this._sessionId,
          createdAt: this.sessionCreatedAt,
          updatedAt: now,
          cwd: this.deps.cwd,
          provider:
            typeof this.provider === "object" && "name" in this.provider
              ? (this.provider as { name: string }).name
              : "unknown",
          ...(this.model ? { model: this.model } : {}),
          firstPrompt,
          stackNames: this.deps.stateStore.list().map((stack) => stack.name),
          messages: this.messages,
        });
      }
    }
  }

  respondTo(id: string, answer: PermissionResponse): boolean {
    const resolver = this.pending.get(id);
    if (!resolver) return false;
    this.pending.delete(id);
    resolver(answer);
    return true;
  }

  abort(): void {
    this.activeController?.abort();
    for (const [, resolve] of this.pending) resolve({ kind: "deny" });
    this.pending.clear();
  }

  reset(): void {
    this.abort();
    this.messages = [];
    this.pending.clear();
    this.sessionAllowSet.clear();
    this.activeController = null;
    this.resumedId = null;
    this.sessionCreatedAt = null;
    this._sessionId = nanoid();
  }

  private toLogEntry(ev: LoopEvent, iteration: number): LogEntry {
    const ts = new Date().toISOString();
    const sessionId = this._sessionId;
    switch (ev.type) {
      case "iteration_start":
        this.currentIteration = ev.n;
        return {
          ts,
          level: "info",
          sessionId,
          iteration: ev.n,
          category: "iteration_start",
          message: `iteration ${ev.n}`,
        };
      case "assistant_text":
        return {
          ts,
          level: "info",
          sessionId,
          iteration,
          category: "thought",
          message: "assistant text",
          data: { text: ev.delta },
        };
      case "tool_call":
        return {
          ts,
          level: "info",
          sessionId,
          iteration,
          category: "action",
          message: `tool_call: ${ev.name}`,
          data: { name: ev.name, input: ev.input },
        };
      case "tool_progress":
        return {
          ts,
          level: "debug",
          sessionId,
          iteration,
          category: "progress",
          message: ev.msg,
        };
      case "tool_result":
        return {
          ts,
          level: "info",
          sessionId,
          iteration,
          category: "observation",
          message: `tool_result: ${ev.name}`,
          data: { name: ev.name, output: ev.output },
        };
      case "plan_ready":
        return {
          ts,
          level: "info",
          sessionId,
          iteration,
          category: "plan_ready",
          message: "plan ready for confirmation",
        };
      case "permission_request":
        return {
          ts,
          level: "info",
          sessionId,
          iteration,
          category: "permission_request",
          message: `permission: ${ev.tool}`,
        };
      case "error":
        return {
          ts,
          level: "error",
          sessionId,
          iteration,
          category: "error",
          message: ev.error.message,
          data: { stack: ev.error.stack },
        };
      case "usage":
        return {
          ts,
          level: "debug",
          sessionId,
          iteration,
          category: "usage",
          message: `tokens: ${ev.inputTokens} in / ${ev.outputTokens} out`,
          data: { inputTokens: ev.inputTokens, outputTokens: ev.outputTokens },
        };
      case "rollback_started":
        return {
          ts,
          level: "warn",
          sessionId,
          iteration,
          category: "rollback_started",
          message: `rollback: ${ev.stackName} (${ev.reason})`,
        };
      case "rollback_result":
        return {
          ts,
          level: ev.ok ? "info" : "error",
          sessionId,
          iteration,
          category: "rollback_result",
          message: `rollback ${ev.ok ? "ok" : "failed"}: ${ev.stackName}`,
        };
      default:
        return {
          ts,
          level: "debug",
          sessionId,
          iteration,
          category: "event",
          message: `event: ${(ev as { type: string }).type}`,
        };
    }
  }

  private deferUserResponse(
    queue: AsyncQueue<LoopEvent>,
    base: DeferredBase,
  ): Promise<PermissionResponse> {
    const id = nanoid();
    queue.push({ ...base, id } as LoopEvent);
    return new Promise((resolve) => {
      this.pending.set(id, resolve);
    });
  }
}
