"""Parity tests for docker_agent.types.events — mirrors src/types/events.ts:12-50."""

import pytest
from pydantic import TypeAdapter, ValidationError

from docker_agent.types.events import (
    AssistantText,
    Error,
    IterationStart,
    LoopEvent,
    PermissionRequest,
    PlanReady,
    RollbackResult,
    RollbackStarted,
    SecretsInputRequest,
    ToolCall,
    ToolProgress,
    ToolResult,
    TypedConfirmRequest,
    Usage,
)

loop_adapter = TypeAdapter(LoopEvent)


# --- simple variants -----------------------------------------------------

def test_iteration_start() -> None:
    ev = loop_adapter.validate_python({"type": "iteration_start", "n": 1})
    assert isinstance(ev, IterationStart)
    assert ev.n == 1


def test_assistant_text() -> None:
    ev = loop_adapter.validate_python({"type": "assistant_text", "delta": "hi"})
    assert isinstance(ev, AssistantText)
    assert ev.delta == "hi"


def test_tool_call_input_can_be_complex() -> None:
    ev = loop_adapter.validate_python(
        {"type": "tool_call", "name": "plan_stack", "input": {"stackName": "db", "services": []}}
    )
    assert isinstance(ev, ToolCall)
    assert ev.input == {"stackName": "db", "services": []}


def test_tool_progress() -> None:
    ev = loop_adapter.validate_python({"type": "tool_progress", "msg": "pulling"})
    assert isinstance(ev, ToolProgress)
    assert ev.msg == "pulling"


def test_tool_result_output_can_be_complex() -> None:
    ev = loop_adapter.validate_python(
        {"type": "tool_result", "name": "list_stacks", "output": [{"name": "x"}]}
    )
    assert isinstance(ev, ToolResult)
    assert ev.output == [{"name": "x"}]


def test_permission_request_uses_id_tool_input() -> None:
    ev = loop_adapter.validate_python({
        "type": "permission_request",
        "id": "p1",
        "tool": "destroy_stack",
        "input": {"stackName": "db"},
    })
    assert isinstance(ev, PermissionRequest)
    assert ev.id == "p1"
    assert ev.tool == "destroy_stack"


def test_usage_uses_snake_case_aliases() -> None:
    ev = loop_adapter.validate_python({"type": "usage", "inputTokens": 100, "outputTokens": 50})
    assert isinstance(ev, Usage)
    assert ev.input_tokens == 100
    assert ev.output_tokens == 50


# --- plan_ready ----------------------------------------------------------

def test_plan_ready_minimal_payload() -> None:
    payload = {
        "type": "plan_ready",
        "id": "p1",
        "composeYaml": "services: {}",
        "diff": {"stackName": "web", "status": "in_sync", "serviceDiffs": []},
    }
    ev = loop_adapter.validate_python(payload)
    assert isinstance(ev, PlanReady)
    assert ev.compose_yaml == "services: {}"
    assert ev.diff.status == "in_sync"
    assert ev.auto_generated_secrets is None
    assert ev.config_files is None


def test_plan_ready_with_optional_arrays() -> None:
    payload = {
        "type": "plan_ready",
        "id": "p1",
        "composeYaml": "x",
        "diff": {"stackName": "web", "status": "drift", "serviceDiffs": []},
        "autoGeneratedSecrets": [{"service": "db", "keys": ["POSTGRES_PASSWORD"]}],
        "configFiles": [{"path": "config.yaml", "content": "data", "bytes": 4}],
    }
    ev = loop_adapter.validate_python(payload)
    assert isinstance(ev, PlanReady)
    assert ev.auto_generated_secrets is not None
    assert ev.auto_generated_secrets[0].service == "db"
    assert ev.config_files is not None
    assert ev.config_files[0].path == "config.yaml"


# --- typed_confirm_request, secrets_input_request ------------------------

def test_typed_confirm_request() -> None:
    ev = loop_adapter.validate_python({
        "type": "typed_confirm_request",
        "id": "t1",
        "phrase": "DESTROY ALL",
        "reason": "destructive",
    })
    assert isinstance(ev, TypedConfirmRequest)
    assert ev.phrase == "DESTROY ALL"


def test_secrets_input_request() -> None:
    ev = loop_adapter.validate_python(
        {
            "type": "secrets_input_request",
            "id": "s1",
            "service": "db",
            "keys": ["POSTGRES_PASSWORD"],
            "reason": "missing required env",
        }
    )
    assert isinstance(ev, SecretsInputRequest)
    assert ev.service == "db"
    assert ev.keys == ["POSTGRES_PASSWORD"]


# --- error variant carrying a BaseException ------------------------------

def test_error_carries_exception_reference() -> None:
    err = RuntimeError("boom")
    ev = loop_adapter.validate_python({"type": "error", "error": err})
    assert isinstance(ev, Error)
    assert ev.error is err


# --- rollback_* ---------------------------------------------------------

def test_rollback_started_with_optional_running_services() -> None:
    payload = {
        "type": "rollback_started",
        "stackName": "web",
        "reason": "unhealthy",
        "detail": "unhealthy: db",
        "runningServices": ["web"],
    }
    ev = loop_adapter.validate_python(payload)
    assert isinstance(ev, RollbackStarted)
    assert ev.reason == "unhealthy"
    assert ev.running_services == ["web"]


def test_rollback_started_without_running_services() -> None:
    ev = loop_adapter.validate_python({
        "type": "rollback_started",
        "stackName": "web",
        "reason": "apply_failed",
        "detail": "exit 1",
    })
    assert isinstance(ev, RollbackStarted)
    assert ev.running_services is None


def test_rollback_result_restored_enum() -> None:
    ev = loop_adapter.validate_python(
        {"type": "rollback_result", "stackName": "web", "ok": True, "restored": "previous"}
    )
    assert isinstance(ev, RollbackResult)
    assert ev.restored == "previous"
    assert ev.detail is None


def test_rollback_result_invalid_reason_rejected() -> None:
    with pytest.raises(ValidationError):
        loop_adapter.validate_python(
            {"type": "rollback_started", "stackName": "x", "reason": "combined", "detail": "x"}
        )


# --- unknown discriminator -----------------------------------------------

def test_unknown_type_discriminator_rejected() -> None:
    with pytest.raises(ValidationError):
        loop_adapter.validate_python({"type": "audit", "msg": "x"})


# --- round-trip a typical event stream ----------------------------------

def test_event_sequence_round_trip() -> None:
    payload = [
        {"type": "iteration_start", "n": 1},
        {"type": "assistant_text", "delta": "ok"},
        {"type": "tool_call", "name": "list_stacks", "input": {}},
        {"type": "tool_progress", "msg": "scanning"},
        {"type": "tool_result", "name": "list_stacks", "output": []},
        {"type": "usage", "inputTokens": 5, "outputTokens": 10},
    ]
    parsed = [loop_adapter.validate_python(p) for p in payload]
    dumped = [m.model_dump(by_alias=True) for m in parsed]
    assert dumped == payload