import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { nanoid } from "nanoid";
import type { LoopContext } from "src/loopContext";
import type { Provider, ProviderEvent } from "src/services/api/types";
import type { ComposeRunner } from "src/services/docker/composeRunner";
import type { EngineClient } from "src/services/docker/engineClient";
import { StateStore } from "src/state/StateStore";
import type { LoopEvent } from "src/types/events";
import type { PermissionResponse } from "src/types/permissions";
import { afterEach, beforeEach, describe, expect, test } from "vitest";
import { MockComposeRunner } from "../../../../tests/mocks/mockComposeRunner";
import { MockDockerEngine } from "../../../../tests/mocks/mockDockerEngine";
import { LangGraphBackend } from "../LangGraphBackend";

function fakeProvider(calls: ProviderEvent[][]) {
  let callIdx = 0;
  return {
    name: "fake",
    stream: async function* () {
      const events = calls[callIdx++] ?? [];
      for (const ev of events) yield ev;
    },
  };
}

function toolUseCall(toolName: string, input: unknown): ProviderEvent[] {
  const inputJson = JSON.stringify(input);
  return [
    { type: "tool_use_start", id: "t1", name: toolName },
    { type: "tool_use_delta", id: "t1", argsPartialJson: inputJson },
    { type: "tool_use_stop", id: "t1" },
    { type: "message_stop", stopReason: "tool_use" },
  ];
}

function textDone(): ProviderEvent[] {
  return [
    { type: "text_delta", text: "done" },
    { type: "message_stop", stopReason: "end_turn" },
  ];
}

interface ContextOptions {
  emit?: (ev: LoopEvent) => void;
  permissionResponse?: PermissionResponse;
  typedConfirmResponse?: PermissionResponse;
  confirmResponse?: PermissionResponse;
  allowSet?: Set<string>;
  stateStore?: StateStore;
  composeRunner?: MockComposeRunner;
}

function makeContext(tmp: string, opts: ContextOptions = {}): LoopContext {
  return {
    cwd: tmp,
    stateStore: opts.stateStore ?? new StateStore(tmp),
    dockerEngine: new MockDockerEngine() as unknown as EngineClient,
    composeRunner: (opts.composeRunner ?? new MockComposeRunner(tmp)) as unknown as ComposeRunner,
    abortSignal: new AbortController().signal,
    requestPermission: async (tool, input) => {
      opts.emit?.({ type: "permission_request", id: nanoid(), tool, input });
      return opts.permissionResponse ?? { kind: "approve" as const };
    },
    requestConfirm: async (plan) => {
      opts.emit?.({
        type: "plan_ready",
        id: nanoid(),
        composeYaml: plan.composeYaml,
        diff: plan.diff,
        ...(plan.autoGeneratedSecrets ? { autoGeneratedSecrets: plan.autoGeneratedSecrets } : {}),
        ...(plan.configFiles ? { configFiles: plan.configFiles } : {}),
      });
      return opts.confirmResponse ?? { kind: "approve" as const };
    },
    requestTypedConfirm: async (phrase, reason) => {
      opts.emit?.({ type: "typed_confirm_request", id: nanoid(), phrase, reason });
      return opts.typedConfirmResponse ?? { kind: "typed_confirm_value" as const, value: "x" };
    },
    requestSecretsInput: async () => ({ kind: "deny" as const }),
    allowSet: opts.allowSet ?? new Set<string>(),
  };
}

async function runBackend(
  tmp: string,
  toolName: string,
  input: unknown,
  ctx?: LoopContext,
): Promise<LoopEvent[]> {
  const events: LoopEvent[] = [];
  const context = ctx ?? makeContext(tmp, { emit: (ev) => events.push(ev) });
  const backend = new LangGraphBackend();
  for await (const ev of backend.query({
    messages: [{ role: "user", content: `run ${toolName}` }],
    ctx: context,
    provider: fakeProvider([toolUseCall(toolName, input), textDone()]) as unknown as Provider,
  })) {
    events.push(ev);
  }
  return events;
}

function expectEventOrder(events: LoopEvent[], ...types: LoopEvent["type"][]) {
  const indices = types.map((t) => events.findIndex((e) => e.type === t));
  for (let i = 0; i < indices.length - 1; i++) {
    const current = indices[i];
    const next = indices[i + 1];
    if (current === undefined || next === undefined) {
      throw new Error("unexpected undefined event index");
    }
    expect(current).toBeGreaterThanOrEqual(0);
    expect(current).toBeLessThan(next);
  }
}

describe("typed-confirm parity", () => {
  let tmp: string;
  beforeEach(() => {
    tmp = fs.mkdtempSync(path.join(os.tmpdir(), "lg-confirm-"));
    fs.writeFileSync(path.join(tmp, "project-policies.yaml"), "project: {}");
  });
  afterEach(() => fs.rmSync(tmp, { recursive: true, force: true }));

  test("destroy_all_stacks typed confirm match executes", async () => {
    const events: LoopEvent[] = [];
    const ctx = makeContext(tmp, {
      emit: (ev) => events.push(ev),
      typedConfirmResponse: { kind: "typed_confirm_value", value: "DESTROY ALL" },
    });
    const collected = await runBackend(tmp, "destroy_all_stacks", {}, ctx);
    events.push(...collected);

    expectEventOrder(events, "typed_confirm_request", "tool_call", "tool_result");
    const toolResult = events.find(
      (e): e is LoopEvent & { type: "tool_result" } =>
        e.type === "tool_result" && e.name === "destroy_all_stacks",
    );
    expect(toolResult).toBeDefined();
    expect(typeof toolResult?.output).toBe("object");
    expect(Array.isArray((toolResult?.output as { destroyed: unknown[] }).destroyed)).toBe(true);
  });

  test("destroy_all_stacks typed confirm mismatch aborts", async () => {
    const events: LoopEvent[] = [];
    const ctx = makeContext(tmp, {
      emit: (ev) => events.push(ev),
      typedConfirmResponse: { kind: "typed_confirm_value", value: "WRONG" },
    });
    const collected = await runBackend(tmp, "destroy_all_stacks", {}, ctx);
    events.push(...collected);

    expect(events.map((e) => e.type)).toContain("typed_confirm_request");
    expect(events.map((e) => e.type)).not.toContain("tool_call");
    expect(events.map((e) => e.type)).not.toContain("tool_result");
  });

  test("destroy_stack with removeVolumes typed confirm match executes", async () => {
    const events: LoopEvent[] = [];
    const ctx = makeContext(tmp, {
      emit: (ev) => events.push(ev),
      typedConfirmResponse: { kind: "typed_confirm_value", value: "DESTROY test" },
    });
    const collected = await runBackend(
      tmp,
      "destroy_stack",
      { stackName: "test", removeVolumes: true },
      ctx,
    );
    events.push(...collected);

    expectEventOrder(events, "typed_confirm_request", "tool_call", "tool_result");
    const toolResult = events.find(
      (e): e is LoopEvent & { type: "tool_result" } =>
        e.type === "tool_result" && e.name === "destroy_stack",
    );
    expect(toolResult).toBeDefined();
    expect((toolResult?.output as { ok: boolean }).ok).toBe(true);
  });

  test("destroy_stack with removeVolumes typed confirm mismatch aborts", async () => {
    const events: LoopEvent[] = [];
    const ctx = makeContext(tmp, {
      emit: (ev) => events.push(ev),
      typedConfirmResponse: { kind: "typed_confirm_value", value: "x" },
    });
    const collected = await runBackend(
      tmp,
      "destroy_stack",
      { stackName: "test", removeVolumes: true },
      ctx,
    );
    events.push(...collected);

    expect(events.map((e) => e.type)).toContain("typed_confirm_request");
    expect(events.map((e) => e.type)).not.toContain("tool_call");
    expect(events.map((e) => e.type)).not.toContain("tool_result");
  });

  test("destroy_stack without removeVolumes goes through normal permission gate", async () => {
    const events: LoopEvent[] = [];
    const ctx = makeContext(tmp, { emit: (ev) => events.push(ev) });
    const collected = await runBackend(tmp, "destroy_stack", { stackName: "test" }, ctx);
    events.push(...collected);

    expectEventOrder(events, "permission_request", "tool_call", "tool_result");
    expect(events.map((e) => e.type)).not.toContain("typed_confirm_request");
  });

  test("destroy_stack without removeVolumes permission denied aborts", async () => {
    const events: LoopEvent[] = [];
    const ctx = makeContext(tmp, {
      emit: (ev) => events.push(ev),
      permissionResponse: { kind: "deny" },
    });
    const collected = await runBackend(tmp, "destroy_stack", { stackName: "test" }, ctx);
    events.push(...collected);

    expect(events.map((e) => e.type)).toContain("permission_request");
    expect(events.map((e) => e.type)).not.toContain("tool_call");
    expect(events.map((e) => e.type)).not.toContain("tool_result");
    expect(events.map((e) => e.type)).not.toContain("typed_confirm_request");
  });
}, 20_000);

describe("remediate_drift parity", () => {
  let tmp: string;
  beforeEach(() => {
    tmp = fs.mkdtempSync(path.join(os.tmpdir(), "lg-remediate-"));
    fs.writeFileSync(path.join(tmp, "project-policies.yaml"), "project: {}");
  });
  afterEach(() => fs.rmSync(tmp, { recursive: true, force: true }));

  test("remediate_drift approval -> apply succeeds", async () => {
    const stateStore = new StateStore(tmp);
    const composeRunner = new MockComposeRunner(tmp);
    composeRunner.onBoundRunnerCreated = (runner) => {
      runner.setRunningServices(["web"]);
    };

    stateStore.write("test", {
      "x-docker-agent": {
        name: "test",
        createdAt: new Date().toISOString(),
        lastApplied: null,
        intent: "test",
        provider: "fake",
        generatedBy: "test",
        envFileSources: {},
      },
      services: {
        web: { image: "nginx:1.27" },
      },
    });

    const events: LoopEvent[] = [];
    const ctx = makeContext(tmp, {
      emit: (ev) => events.push(ev),
      stateStore,
      composeRunner,
      confirmResponse: { kind: "approve" },
    });

    const collected = await runBackend(tmp, "remediate_drift", { stackName: "test" }, ctx);
    events.push(...collected);

    expect(events.map((e) => e.type)).toContain("plan_ready");
    expectEventOrder(events, "tool_call", "tool_result");

    const remediateResult = events.find(
      (e): e is LoopEvent & { type: "tool_result" } =>
        e.type === "tool_result" && e.name === "remediate_drift",
    );
    expect(remediateResult).toBeDefined();
    expect((remediateResult?.output as { remediable: boolean }).remediable).toBe(true);

    const applyResult = events.find(
      (e): e is LoopEvent & { type: "tool_result" } =>
        e.type === "tool_result" && e.name === "apply_stack",
    );
    expect(applyResult).toBeDefined();
    expect((applyResult?.output as { ok: boolean }).ok).toBe(true);
  });
}, 20_000);
