"""Inline action review rendering for the activity timeline."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from rich.text import Text

from infra_agent.ui.activity import (
    ActionReviewActivity,
    ActionReviewArtifactRef,
    ActionReviewStatus,
    PlanConfigRef,
    PlanSecretRef,
)
from infra_agent.ui.tool_presentation import safe_json_value, sanitize_tool_text


@dataclass
class ConfigFile:
    path: str
    content: str
    bytes: int


@dataclass
class AutoGeneratedSecret:
    service: str
    keys: list[str]


def _artifact_content_as_text(content: Any) -> str:
    if isinstance(content, str):
        return content
    return safe_json_value(content)


def _render_secrets(auto_generated_secrets: list[PlanSecretRef]) -> Text:
    if not auto_generated_secrets:
        return Text("")
    content = Text("Secret keys required (values hidden):\n", style="bold cyan")
    for entry in auto_generated_secrets:
        content.append(f"{entry.service}:\n", style="bold cyan")
        for key in entry.keys:
            content.append(f"  - {key}: ", style="")
            content.append("****************\n", style="yellow")
    return content


def _render_bordered_block(lines: list[str], *, style: str = "dim") -> Text:
    """Render lines inside a simple ASCII border for visual separation."""
    if not lines:
        return Text("")
    inner_width = max(len(line) for line in lines)
    inner_width = max(inner_width, 4)
    horizontal = "-" * (inner_width + 2)
    content = Text()
    content.append(f" +{horizontal}+\n", style="dim")
    for line in lines:
        padded = line.ljust(inner_width)
        content.append(f" | {padded} |\n", style=style)
    content.append(f" +{horizontal}+\n", style="dim")
    return content


def _render_config_files(
    config_files: list[PlanConfigRef],
    *,
    show_config: bool,
) -> Text:
    if not config_files:
        return Text("")
    toggle = "collapse" if show_config else "expand"
    content = Text(f"Config files to be written (Press 'c' to {toggle}):\n", style="bold")
    for config_file in config_files:
        content.append(f"  - {config_file.path} ({config_file.bytes} bytes)\n", style="cyan")
        if show_config:
            content.append(f"{sanitize_tool_text(config_file.content)}\n", style="dim")
    return content


def _render_artifacts(
    artifacts: list[ActionReviewArtifactRef],
    *,
    show_artifacts: bool,
) -> Text:
    if not artifacts:
        return Text("")
    toggle = "collapse" if show_artifacts else "expand"
    content = Text(f"Artifacts (Press 'x' to {toggle}):\n", style="bold")
    for artifact in artifacts:
        language = f" [{artifact.language}]" if artifact.language else ""
        content.append(f"  - {artifact.label}{language}\n", style="cyan")
        artifact_text = _artifact_content_as_text(artifact.content)
        if show_artifacts:
            lines = sanitize_tool_text(artifact_text).split("\n")
            content.append_text(_render_bordered_block(lines))
        else:
            line_count = len(artifact_text.split("\n"))
            content.append(f"    collapsed - {line_count} lines\n", style="dim")
    return content


def render_action_review_preview(
    *,
    tool: str,
    title: str,
    summary: str,
    artifacts: list[ActionReviewArtifactRef] | None = None,
    auto_generated_secrets: list[PlanSecretRef] | None = None,
    config_files: list[PlanConfigRef] | None = None,
    show_artifacts: bool = False,
    show_config: bool = False,
    status: ActionReviewStatus = "pending",
) -> Text:
    """Render a plugin-neutral action review block for the chat timeline."""
    content = Text()
    content.append("Action review\n", style="bold cyan")
    content.append(f"{title}\n", style="bold")
    if tool:
        content.append(f"Tool: {tool}\n", style="dim")
    if summary:
        content.append(f"{summary}\n", style="dim")
    content.append_text(_render_artifacts(artifacts or [], show_artifacts=show_artifacts))
    secrets_text = _render_secrets(auto_generated_secrets or [])
    if secrets_text.plain:
        content.append_text(secrets_text)
    config_text = _render_config_files(config_files or [], show_config=show_config)
    if config_text.plain:
        content.append_text(config_text)
    content.append("\n")
    if status == "pending":
        content.append(
            "Approve this action? [y/n] (Press 'x' to view artifacts, 'c' to view config files)\n",
            style="yellow",
        )
    elif status == "approved":
        content.append("Action approved\n", style="green")
    else:
        content.append("Action declined\n", style="red")
    return content


def render_action_review_activity(activity: ActionReviewActivity) -> Text:
    return render_action_review_preview(
        tool=activity.tool,
        title=activity.title,
        summary=activity.summary,
        artifacts=activity.artifacts,
        auto_generated_secrets=activity.auto_generated_secrets,
        config_files=activity.config_files,
        show_artifacts=activity.show_artifacts,
        show_config=activity.show_config,
        status=activity.status,
    )


__all__ = [
    "AutoGeneratedSecret",
    "ConfigFile",
    "render_action_review_activity",
    "render_action_review_preview",
]