"""Main REPL screen.

Parity: ``src/screens/REPL.tsx``.
"""

from __future__ import annotations

import asyncio
import os
from pathlib import Path
from typing import Any, cast

from textual import events
from textual.app import App, ComposeResult
from textual.reactive import reactive
from textual.widgets import Static

from docker_agent.commands.registry import Command, create_default_registry
from docker_agent.components.activity_timeline import ActivityTimeline
from docker_agent.components.api_key_input_dialog import ApiKeyInputDialog
from docker_agent.components.command_palette import CommandPalette
from docker_agent.components.footer import StatusFooter, build_footer_content
from docker_agent.components.log_pane import LogPane
from docker_agent.components.model_picker_dialog import ModelChoice, ModelPickerDialog
from docker_agent.components.ollama_setup_dialog import OllamaSetupDialog
from docker_agent.components.permission_dialog import PermissionDialog
from docker_agent.components.plan_preview import (
    AutoGeneratedSecret as PlanAutoSecret,
)
from docker_agent.components.plan_preview import (
    ConfigFile as PlanConfigFile,
)
from docker_agent.components.plan_preview import (
    PlanPreview,
)
from docker_agent.components.prompt_input import PromptInput, PromptSubmitted, ResumeQueue
from docker_agent.components.provider_connect_dialog import ProviderConnectDialog
from docker_agent.components.queue_panel import QueuePanel
from docker_agent.components.secrets_input_dialog import SecretsInputDialog
from docker_agent.components.thinking_indicator import ThinkingIndicator
from docker_agent.components.tool_details_panel import ToolDetailsPanel
from docker_agent.components.typed_confirm_dialog import TypedConfirmDialog
from docker_agent.components.welcome_banner import WelcomeBanner
from docker_agent.config import PROVIDER_NAMES, ProviderName, stack_state_yaml_path
from docker_agent.query_engine import QueryEngine
from docker_agent.screens.apply_slash_effects import SlashEffectApplierDeps, apply_slash_effects
from docker_agent.screens.use_interaction_session import InteractionSession
from docker_agent.secrets.api_key_store import (
    ApiKeyProviderName,
    ApiKeyStore,
    api_key_env_var,
    create_api_key_store,
    describe_api_key_status,
    is_api_key_provider_name,
)
from docker_agent.services.api import resolve_provider_for_request
from docker_agent.services.model_catalog import build_model_catalog, flatten_catalog
from docker_agent.services.provider_status import get_provider_statuses
from docker_agent.slash_router import SlashRouterContext, route_slash_command
from docker_agent.state.logger import StructuredLogger
from docker_agent.state.secret_redactor import scrub_line
from docker_agent.tools.shared.secret_keys import SecretKeysContext, collect_secret_keys
from docker_agent.types.events import (
    PermissionRequest,
    PlanReady,
    SecretsInputRequest,
    TypedConfirmRequest,
)
from docker_agent.ui.activity import ToolActivity


class REPL(App[None]):
    BINDINGS = [
        ("ctrl+c", "cancel", "Cancel"),
        ("ctrl+o", "toggle_details", "Details"),
        ("ctrl+p", "toggle_palette", "Palette"),
        ("ctrl+q", "toggle_queue", "Queue"),
    ]

    show_banner: reactive[bool] = reactive(True)
    active_provider_name: reactive[str] = reactive("openai")
    active_model: reactive[str | None] = reactive(None)
    show_details: reactive[bool] = reactive(False)
    show_palette: reactive[bool] = reactive(False)
    show_queue: reactive[bool] = reactive(False)

    def __init__(
        self,
        *,
        engine: QueryEngine,
        version: str,
        api_key_store: ApiKeyStore | None = None,
        show_banner: bool = True,
        yes: bool = False,
        resumed_record: dict[str, Any] | None = None,
        **kwargs: Any,
    ) -> None:
        super().__init__(**kwargs)
        self.engine = engine
        self.version = version
        self.api_key_store = api_key_store or create_api_key_store()
        self.show_banner = show_banner
        self.yes = yes
        self.resumed_record = resumed_record
        self.session = InteractionSession(engine)
        self._session_task: asyncio.Task[None] | None = None
        self._log_controller: asyncio.Event | None = None
        self._log_lines: list[str] = []
        self._active_log_pane: LogPane | None = None
        self._local_pending: str | None = None
        self._timeline_key = 0
        self._cwd = engine._cwd  # noqa: SLF001
        self._state_store = engine._state_store  # noqa: SLF001
        self._compose_runner = engine._compose_runner  # noqa: SLF001
        self._session_store = engine._session_store  # noqa: SLF001

    def on_mount(self) -> None:
        log_dir = Path(self._cwd) / ".docker-agent" / "logs"
        self.engine.set_logger(StructuredLogger(str(log_dir), self.engine.session_id))
        self._session_task = asyncio.create_task(self.session.run_loop())
        if self.resumed_record:
            from docker_agent.state.session_store import session_cwd_mismatch_warning

            warning = session_cwd_mismatch_warning(self.resumed_record, self._cwd)
            if warning:
                self.session.dispatch_activity({"type": "assistant_text", "delta": warning})
        asyncio.create_task(self._tick_ui())

    def on_unmount(self) -> None:
        if self._session_task is not None:
            self._session_task.cancel()
        self._stop_log_pane()

    def compose(self) -> ComposeResult:
        if self.show_banner:
            yield WelcomeBanner(
                version=self.version,
                provider=self.active_provider_name,
                model=self.active_model,
                compact=self.size.height <= 16 or self.size.width < 84,
                id="welcome",
            )
        else:
            yield Static(
                (
                    f"docker-agent | provider: {self.active_provider_name} | "
                    f"model: {self.active_model or 'default'}"
                ),
                id="header",
            )
        yield ActivityTimeline(
            items=self.session.activity_state.items,
            active_tool_activity_id=self.session.activity_state.active_tool_activity_id,
            id="timeline",
        )
        yield PromptInput(id="prompt")
        if self.session.interaction.phase == "running":
            yield ThinkingIndicator(id="thinking")
        yield StatusFooter(
            usage=self.engine.total_usage,
            session_id=self.engine.session_id,
            active_tool=self._active_tool_title(),
            queue_count=len(self.session.interaction.queue),
            id="footer",
        )

    def _active_tool_title(self) -> str | None:
        active_id = self.session.activity_state.active_tool_activity_id
        for item in self.session.activity_state.items:
            if item.type == "tool" and item.id == active_id:
                return item.title
        return None

    def _latest_tool(self) -> ToolActivity | None:
        for item in reversed(self.session.activity_state.items):
            if item.type == "tool":
                return item
        return None

    def _refresh_ui(self) -> None:
        try:
            timeline = self.query_one("#timeline", ActivityTimeline)
            timeline.items = self.session.activity_state.items
            timeline.active_tool_activity_id = self.session.activity_state.active_tool_activity_id
            timeline.refresh_timeline()
            prompt = self.query_one("#prompt", PromptInput)
            prompt.phase = self.session.interaction.phase
            footer = self.query_one("#footer", StatusFooter)
            footer.update(
                build_footer_content(
                    usage=self.engine.total_usage,
                    session_id=self.engine.session_id,
                    active_tool=self._active_tool_title(),
                    queue_count=len(self.session.interaction.queue),
                )
            )
            thinking = self.query("#thinking")
            if self.session.interaction.phase == "running" and not thinking:
                self.mount(ThinkingIndicator(id="thinking"))
            elif self.session.interaction.phase != "running" and thinking:
                thinking.remove()
        except Exception:
            return

    async def _tick_ui(self) -> None:
        while True:
            await asyncio.sleep(0.1)
            self._refresh_ui()
            if self.yes and isinstance(self.session.pending_event, PermissionRequest):
                from docker_agent.types.permissions import Approve

                self.session.respond(self.session.pending_event.id, Approve())
            await self._maybe_show_pending()

    async def _maybe_show_pending(self) -> None:
        if self.session.pending_event is None or self._local_pending is not None:
            return
        pending = self.session.pending_event
        if isinstance(pending, PermissionRequest):
            self._local_pending = "permission"
            result = await self.push_screen_wait(
                PermissionDialog(tool=pending.tool, input_data=pending.input)
            )
            if result is not None:
                self.session.respond(pending.id, result)
            self._local_pending = None
        elif isinstance(pending, PlanReady):
            self._local_pending = "plan"
            plan_secrets = (
                [
                    PlanAutoSecret(service=item.service, keys=list(item.keys))
                    for item in pending.auto_generated_secrets
                ]
                if pending.auto_generated_secrets
                else None
            )
            plan_files = (
                [
                    PlanConfigFile(path=item.path, content=item.content, bytes=item.bytes)
                    for item in pending.config_files
                ]
                if pending.config_files
                else None
            )
            result = await self.push_screen_wait(
                PlanPreview(
                    compose_yaml=pending.compose_yaml,
                    diff=pending.diff,
                    auto_generated_secrets=plan_secrets,
                    config_files=plan_files,
                )
            )
            if result is not None:
                self.session.respond(pending.id, result)
            self._local_pending = None
        elif isinstance(pending, TypedConfirmRequest):
            self._local_pending = "typed"
            result = await self.push_screen_wait(
                TypedConfirmDialog(phrase=pending.phrase, reason=pending.reason)
            )
            if result is not None:
                self.session.respond(pending.id, result)
            self._local_pending = None
        elif isinstance(pending, SecretsInputRequest):
            self._local_pending = "secrets"
            result = await self.push_screen_wait(
                SecretsInputDialog(
                    service=pending.service,
                    keys=pending.keys,
                    reason=pending.reason,
                )
            )
            if result is not None:
                self.session.respond(pending.id, result)
            self._local_pending = None

    def _stop_log_pane(self) -> None:
        if self._log_controller is not None:
            self._log_controller.set()
            self._log_controller = None
        if self._active_log_pane is not None:
            self.pop_screen()
            self._active_log_pane = None
        self._log_lines = []

    def _start_log_pane(self, stack_name: str, service: str | None = None) -> None:
        yaml_path = stack_state_yaml_path(stack_name, self._cwd)
        if not Path(yaml_path).exists():
            self.session.dispatch_activity(
                {
                    "type": "user_text",
                    "text": f"/logs {stack_name}{f' {service}' if service else ''}",
                }
            )
            self.session.dispatch_activity(
                {"type": "error", "error": RuntimeError(f"stack {stack_name} not found")}
            )
            return
        self._stop_log_pane()
        controller = asyncio.Event()
        self._log_controller = controller
        self._log_lines = []
        pane = LogPane(stack_name=stack_name, service=service, lines=[])
        self._active_log_pane = pane
        self.push_screen(pane)
        secret_keys = collect_secret_keys(
            stack_name,
            SecretKeysContext(cwd=self._cwd, state_store=self._state_store),
        )
        bound = self._compose_runner.for_stack(stack_name, yaml_path)

        async def follow_logs() -> None:
            try:
                async for chunk in bound.logs(
                    follow=True,
                    tail_lines=50,
                    signal=controller,
                    service=service,
                ):
                    if controller.is_set():
                        break
                    scrubbed = scrub_line(chunk, secret_keys)
                    self._log_lines.append(scrubbed)
                    if len(self._log_lines) > 200:
                        self._log_lines = self._log_lines[-200:]
                    if self._active_log_pane is not None:
                        self._active_log_pane.append_line(scrubbed)
            except Exception:
                return

        asyncio.create_task(follow_logs())

    async def _resolve_all_providers(self) -> dict[ProviderName, Any]:
        return {
            name: resolve_provider_for_request(
                name, os.environ, api_key_store=self.api_key_store
            )
            for name in PROVIDER_NAMES
        }

    async def _open_provider_connect(self) -> None:
        instances = await self._resolve_all_providers()
        statuses = await get_provider_statuses(
            api_key_store=self.api_key_store,
            providers=instances,
        )
        api_key_statuses = await describe_api_key_status(self.api_key_store, os.environ)
        provider = await self.push_screen_wait(
            ProviderConnectDialog(
                statuses=statuses,
                api_key_statuses=api_key_statuses,
            )
        )
        if provider is None:
            return
        status = next((s for s in statuses if s.provider == provider), None)
        if status and status.connected:
            await self._open_model_picker(provider)
        else:
            await self._on_connect_provider(provider)

    async def _open_model_picker(self, scope_provider: str | None = None) -> None:
        instances = await self._resolve_all_providers()
        statuses = await get_provider_statuses(
            api_key_store=self.api_key_store,
            providers=instances,
        )
        catalog = await build_model_catalog(statuses, instances)
        rows = flatten_catalog(catalog)
        if scope_provider:
            rows = [
                row
                for row in rows
                if (row.kind == "header" and row.provider == scope_provider)
                or (row.kind != "header" and row.provider == scope_provider)
            ]
        has_navigable = any(row.kind in {"model", "connect"} for row in rows)
        if not has_navigable:
            self.session.dispatch_activity(
                {
                    "type": "error",
                    "error": RuntimeError("No providers connected. Use /connect first."),
                }
            )
            await self._open_provider_connect()
            return
        choice = await self.push_screen_wait(
            ModelPickerDialog(
                rows=rows,
                current={
                    "provider": self.active_provider_name,
                    "model": self.active_model or "",
                },
            )
        )
        if choice is None:
            self.session.dispatch_activity(
                {"type": "assistant_text", "delta": "Model selection cancelled"}
            )
            return
        if isinstance(choice, ModelChoice):
            self._on_model_picked(choice)
        elif choice == "connect":
            await self._open_provider_connect()
        else:
            await self._on_connect_provider(choice)

    def _on_model_picked(self, choice: ModelChoice) -> None:
        self.engine.provider = resolve_provider_for_request(
            choice.provider, os.environ, api_key_store=self.api_key_store
        )
        self.engine.model = choice.model
        self.active_provider_name = choice.provider
        self.active_model = choice.model
        self.session.dispatch_activity(
            {
                "type": "assistant_text",
                "delta": f"Model set to {choice.model} ({choice.provider})",
            }
        )

    async def _on_connect_provider(self, provider: str | None = None) -> None:
        if provider and is_api_key_provider_name(provider):
            result = await self.push_screen_wait(
                ApiKeyInputDialog(
                    provider=provider,  # type: ignore[arg-type]
                    env_var_name=api_key_env_var(provider),  # type: ignore[arg-type]
                )
            )
            if result:
                await self._on_api_key_submit(
                    cast(ApiKeyProviderName, provider),
                    result,
                    return_to="modelPicker",
                )
            return
        if provider == "ollama":
            host = os.environ.get("OLLAMA_HOST", "http://localhost:11434")
            ollama_result = await self.push_screen_wait(OllamaSetupDialog(host=host))
            if ollama_result is not None:
                os.environ["OLLAMA_HOST"] = ollama_result.host
            return
        await self._open_provider_connect()

    async def _on_api_key_submit(
        self,
        provider: ApiKeyProviderName,
        value: str,
        *,
        return_to: str | None = None,
    ) -> None:
        try:
            await self.api_key_store.set(provider, value)
            os.environ[api_key_env_var(provider)] = value
            self.session.dispatch_activity(
                {"type": "assistant_text", "delta": f"API key saved for {provider}"}
            )
            if return_to == "modelPicker":
                await self._open_model_picker(provider)
        except Exception as err:  # noqa: BLE001
            self.session.dispatch_activity({"type": "error", "error": err})

    def _slash_deps(self, input_text: str = "") -> SlashEffectApplierDeps:
        return SlashEffectApplierDeps(
            input=input_text,
            session=self.session,
            engine=self.engine,
            api_key_store=self.api_key_store,
            session_store=self._session_store,
            exit=self.exit,
            stop_log_pane=self._stop_log_pane,
            set_show_details=lambda value: setattr(self, "show_details", value),
            set_show_palette=lambda value: setattr(self, "show_palette", value),
            set_show_queue=lambda value: setattr(self, "show_queue", value),
            set_timeline_key=lambda _value: setattr(
                self, "_timeline_key", self._timeline_key + 1
            ),
            set_active_provider_name=lambda value: setattr(
                self, "active_provider_name", value
            ),
            set_active_model=lambda value: setattr(self, "active_model", value),
            open_provider_connect=self._open_provider_connect,
            open_model_picker=self._open_model_picker,
            start_log_pane=self._start_log_pane,
        )

    async def _handle_submit(self, input_text: str) -> None:
        target = input_text.strip()
        lowered = target.lower()
        if lowered in {"exit", "/exit"}:
            self.session.cancel_current()
            self.exit()
            return
        if target.startswith("/"):
            result = await route_slash_command(
                input_text,
                SlashRouterContext(
                    cwd=self._cwd,
                    state_store=self._state_store,
                    active_provider_name=self.active_provider_name,  # type: ignore[arg-type]
                    api_key_store=self.api_key_store,
                    session_store=self._session_store,
                ),
            )
            await apply_slash_effects(result.effects, self._slash_deps(input_text))
            if result.handled:
                return
        self.session.submit(target)

    async def on_prompt_submitted(self, message: PromptSubmitted) -> None:
        if self._input_blocked():
            return
        await self._handle_submit(message.text)

    async def on_resume_queue(self, _message: ResumeQueue) -> None:
        self.session.resume_queue()

    def _input_blocked(self) -> bool:
        return (
            self.session.pending_event is not None
            or self._local_pending is not None
            or self.show_palette
            or self.show_queue
            or (self.show_details and self._latest_tool() is not None)
            or self._active_log_pane is not None
        )

    def action_cancel(self) -> None:
        if self._active_log_pane is not None:
            self._stop_log_pane()
        elif self._local_pending is not None:
            self._local_pending = None
        else:
            self.session.cancel_current()

    async def action_toggle_details(self) -> None:
        if self.session.pending_event or self._local_pending or self._active_log_pane:
            return
        latest = self._latest_tool()
        if latest is None:
            return
        self.show_palette = False
        self.show_queue = False
        self.show_details = not self.show_details
        existing = self.query("#tool-details")
        if self.show_details and not existing:
            self.mount(ToolDetailsPanel(activity=latest, id="tool-details"))
        elif not self.show_details and existing:
            existing.remove()

    async def action_toggle_palette(self) -> None:
        if self.session.pending_event or self._local_pending or self._active_log_pane:
            return
        self.show_details = False
        self.show_queue = False
        registry = create_default_registry()
        registry.register(
            Command(
                id="cancel",
                title="Cancel",
                description="Cancel current turn",
                shortcut="Ctrl+C",
                action=self.session.cancel_current,
            )
        )
        command = await self.push_screen_wait(CommandPalette(commands=registry.get_all()))
        if command is None:
            return
        if command.action is not None:
            command.action()
        elif command.insert_text:
            self.query_one("#prompt", PromptInput).prefill = command.insert_text

    async def action_toggle_queue(self) -> None:
        if self.session.pending_event or self._local_pending or self._active_log_pane:
            return
        self.show_details = False
        self.show_palette = False
        action = await self.push_screen_wait(
            QueuePanel(
                queue=self.session.interaction.queue,
                on_remove=self.session.remove_queued,
                on_clear=self.session.clear_queue,
                on_resume=self.session.resume_queue,
            )
        )
        if action is not None and action.kind == "resume":
            self.session.resume_queue()

    async def on_key(self, event: events.Key) -> None:
        if event.key == "escape" and self._active_log_pane is not None:
            self._stop_log_pane()
            event.stop()


__all__ = ["REPL"]