import * as path from "node:path";
import type { Tool, ToolProgress } from "src/Tool";
import { detectDrift } from "src/state/driftDetector";
import { mergeEnv, readEnvFile, writeEnvFile } from "src/state/envFile";
import { shouldRedact } from "src/state/secretRedactor";
import type { EnvFileSource, ServiceSpec, StackDiff } from "src/types/stack";
import { z } from "zod";
import { buildStackDefinition, stackToYaml } from "./shared/composeBuilder";
import { findRequiredSecrets } from "./shared/requiredSecrets";

const ServiceSpecSchema = z.object({
  image: z.string(),
  command: z.union([z.string(), z.array(z.string())]).optional(),
  ports: z.array(z.string()).optional(),
  environment: z.record(z.string()).optional(),
  env_file: z.array(z.string()).optional(),
  volumes: z.array(z.string()).optional(),
  depends_on: z
    .union([
      z.array(z.string()),
      z.record(
        z.object({
          condition: z.enum([
            "service_started",
            "service_healthy",
            "service_completed_successfully",
          ]),
        }),
      ),
    ])
    .optional(),
  healthcheck: z
    .object({
      test: z.union([z.string(), z.array(z.string())]),
      interval: z.string().optional(),
      timeout: z.string().optional(),
      retries: z.number().optional(),
      start_period: z.string().optional(),
    })
    .optional(),
  restart: z.enum(["no", "always", "on-failure", "unless-stopped"]).optional(),
  labels: z.record(z.string()).optional(),
  networks: z.array(z.string()).optional(),
  scale: z.number().int().min(1).optional(),
});

export const PlanStackInputSchema = z.object({
  stackName: z.string().regex(/^[a-z][a-z0-9_-]{0,62}$/),
  intent: z.string(),
  services: z.record(ServiceSpecSchema).refine((services) => Object.keys(services).length > 0, {
    message: "at least one service",
  }),
  networks: z.record(z.unknown()).optional(),
  volumes: z.record(z.unknown()).optional(),
});

export type PlanStackInput = z.infer<typeof PlanStackInputSchema>;
type PlanStackServiceSpec = PlanStackInput["services"][string];

export interface PlanStackResultOk {
  blocked: false;
  composeYaml: string;
  scaleOverrides: Record<string, number>;
  diff: StackDiff;
  autoGeneratedSecrets: Array<{ service: string; keys: string[] }>;
  warnings: string[];
}

export interface PlanStackResultBlocked {
  blocked: true;
  reason: "missing_required_env";
  missingByService: Record<string, string[]>;
}

export type PlanStackResult = PlanStackResultOk | PlanStackResultBlocked;

function resolveEnvFile(cwd: string, envFilePath: string): string {
  return path.isAbsolute(envFilePath) ? envFilePath : path.join(cwd, envFilePath);
}

function generatedEnvFilePath(cwd: string, stackName: string, serviceName: string): string {
  return path.join(cwd, ".docker-agent", "secrets", `${stackName}-${serviceName}.env`);
}

function generatedEnvFileRef(stackName: string, serviceName: string): string {
  return `./.docker-agent/secrets/${stackName}-${serviceName}.env`;
}

function toServiceSpec(spec: PlanStackServiceSpec): ServiceSpec {
  const out: ServiceSpec = { image: spec.image };
  if (spec.command !== undefined) out.command = spec.command;
  if (spec.ports !== undefined) out.ports = spec.ports;
  if (spec.environment !== undefined) out.environment = spec.environment;
  if (spec.env_file !== undefined) out.env_file = spec.env_file;
  if (spec.volumes !== undefined) out.volumes = spec.volumes;
  if (spec.depends_on !== undefined) out.depends_on = spec.depends_on;
  if (spec.healthcheck !== undefined) {
    out.healthcheck = { test: spec.healthcheck.test };
    if (spec.healthcheck.interval !== undefined)
      out.healthcheck.interval = spec.healthcheck.interval;
    if (spec.healthcheck.timeout !== undefined) out.healthcheck.timeout = spec.healthcheck.timeout;
    if (spec.healthcheck.retries !== undefined) out.healthcheck.retries = spec.healthcheck.retries;
    if (spec.healthcheck.start_period !== undefined) {
      out.healthcheck.start_period = spec.healthcheck.start_period;
    }
  }
  if (spec.restart !== undefined) out.restart = spec.restart;
  if (spec.labels !== undefined) out.labels = spec.labels;
  if (spec.networks !== undefined) out.networks = spec.networks;
  if (spec.scale !== undefined) out.scale = spec.scale;
  return out;
}

export const planStack: Tool<PlanStackInput, PlanStackResult> = {
  name: "plan_stack",
  description:
    "Generate a Docker Compose plan for a stack. The LLM provides the full services map; the tool validates, assembles the YAML, handles secrets (auto-migrate, auto-generate, or block).",
  inputSchema: PlanStackInputSchema,
  category: "high-level",
  needsPermission: () => false,
  call: async function* (input, ctx): AsyncGenerator<ToolProgress, PlanStackResult> {
    yield { type: "progress", msg: "Validating service spec..." };

    const services = structuredClone(input.services);
    const autoGeneratedSecrets: Array<{ service: string; keys: string[] }> = [];
    const generatedEnvFileSources: Record<string, EnvFileSource> = {};
    const missingByService: Record<string, string[]> = {};

    for (const [serviceName, spec] of Object.entries(services)) {
      const movedSecrets: Record<string, string> = {};
      const inlineEnvironment = spec.environment ?? {};
      const remainingInlineEnvironment: Record<string, string> = {};

      for (const [key, value] of Object.entries(inlineEnvironment)) {
        if (shouldRedact(key)) {
          movedSecrets[key] = value;
        } else {
          remainingInlineEnvironment[key] = value;
        }
      }

      const serviceEnvFile = spec.env_file ? [...spec.env_file] : [];

      if (Object.keys(movedSecrets).length > 0) {
        const targetPath = generatedEnvFilePath(ctx.cwd, input.stackName, serviceName);
        writeEnvFile(targetPath, { ...readEnvFile(targetPath), ...movedSecrets });
        const targetRef = generatedEnvFileRef(input.stackName, serviceName);
        if (!serviceEnvFile.includes(targetRef)) {
          serviceEnvFile.push(targetRef);
        }
        generatedEnvFileSources[serviceName] = {
          generated: true,
          path: targetRef,
          addedKeys: [
            ...(generatedEnvFileSources[serviceName]?.addedKeys ?? []),
            ...Object.keys(movedSecrets),
          ],
        };
        autoGeneratedSecrets.push({ service: serviceName, keys: Object.keys(movedSecrets) });
      }

      const rule = findRequiredSecrets(spec.image);
      if (rule && rule.required.length > 0) {
        const fromEnvFile: Record<string, string> = {};
        for (const envFilePath of serviceEnvFile) {
          Object.assign(fromEnvFile, readEnvFile(resolveEnvFile(ctx.cwd, envFilePath)));
        }

        const merged = mergeEnv(fromEnvFile, remainingInlineEnvironment);
        const missing = rule.required.filter((key) => merged[key] === undefined);
        const safeKeys = missing.filter((key) => rule.safeDefaults?.[key] !== undefined);
        const unsafeKeys = missing.filter((key) => rule.safeDefaults?.[key] === undefined);

        if (unsafeKeys.length > 0) {
          missingByService[serviceName] = unsafeKeys;
        }

        if (safeKeys.length > 0) {
          const targetPath = generatedEnvFilePath(ctx.cwd, input.stackName, serviceName);
          const targetValues = { ...readEnvFile(targetPath) };
          for (const key of safeKeys) {
            const makeDefault = rule.safeDefaults?.[key];
            if (makeDefault) {
              targetValues[key] = makeDefault();
            }
          }
          writeEnvFile(targetPath, targetValues);
          const targetRef = generatedEnvFileRef(input.stackName, serviceName);
          if (!serviceEnvFile.includes(targetRef)) {
            serviceEnvFile.push(targetRef);
          }
          generatedEnvFileSources[serviceName] = {
            generated: true,
            path: targetRef,
            addedKeys: [...(generatedEnvFileSources[serviceName]?.addedKeys ?? []), ...safeKeys],
          };
          autoGeneratedSecrets.push({ service: serviceName, keys: safeKeys });
        }
      }

      const { environment: _environment, env_file: _envFile, ...baseSpec } = spec;
      const nextSpec: PlanStackServiceSpec = { ...baseSpec };
      if (Object.keys(remainingInlineEnvironment).length > 0) {
        nextSpec.environment = remainingInlineEnvironment;
      }

      if (serviceEnvFile.length > 0) {
        nextSpec.env_file = serviceEnvFile;
      }

      services[serviceName] = nextSpec;
    }

    if (Object.keys(missingByService).length > 0) {
      return { blocked: true, reason: "missing_required_env", missingByService };
    }

    yield { type: "progress", msg: "Assembling Compose YAML..." };

    const previous = ctx.stateStore.read(input.stackName);
    const stackServices = Object.fromEntries(
      Object.entries(services).map(([name, spec]) => [name, toServiceSpec(spec)]),
    ) as Record<string, ServiceSpec>;
    const planInput = {
      stackName: input.stackName,
      intent: input.intent,
      services: stackServices,
      ...(input.networks !== undefined ? { networks: input.networks } : {}),
      ...(input.volumes !== undefined ? { volumes: input.volumes } : {}),
    };
    const { def, scaleOverrides } = buildStackDefinition(planInput, previous, "unknown", "unknown");
    def["x-docker-agent"].envFileSources = {
      ...def["x-docker-agent"].envFileSources,
      ...generatedEnvFileSources,
    };
    const composeYaml = stackToYaml(def);

    let diff: StackDiff = {
      stackName: input.stackName,
      status: "missing",
      serviceDiffs: [],
    };
    try {
      diff = await detectDrift(input.stackName, ctx.stateStore, ctx.dockerEngine, ctx.cwd);
    } catch {
      // Engine access is best-effort during planning; apply_stack owns deployment.
    }

    return {
      blocked: false,
      composeYaml,
      scaleOverrides,
      diff,
      autoGeneratedSecrets,
      warnings: [],
    };
  },
};
