import * as path from "node:path";
import type { Tool, ToolProgress } from "src/Tool";
import { detectDrift } from "src/state/driftDetector";
import { mergeEnv, readEnvFile, writeEnvFile } from "src/state/envFile";
import { shouldRedact } from "src/state/secretRedactor";
import type { EnvFileSource, ServiceSpec, StackDiff } from "src/types/stack";
import { checkPortConflicts } from "./checkPortConflict";
import { resolveDependencies, type ResolveDependencyResult } from "./resolveDependency";
import { buildStackDefinition, stackToYaml } from "./shared/composeBuilder";
import {
  type StagedConfigFile,
  detectMissingConfigFiles,
  stageConfigFiles,
} from "./shared/configFiles";
import { type DbPortExposureIssue, checkDbPortExposure } from "./shared/dbPortGuard";
import { type NetworkIssue, checkNetworkReferences } from "./shared/networkGuard";
import { findRequiredSecrets, isWeakSecretValue } from "./shared/requiredSecrets";
import { type ResourceLimitIssue, checkResourceLimits } from "./shared/resourceLimits";
import { type DraftServiceSpec, type StackDraft, StackDraftSchema } from "./shared/specSchemas";
import { type VolumeIssue, checkVolumeSafety } from "./shared/volumeGuard";
import { validateYamlRoundTrip } from "./shared/yamlRoundTrip";
import { type SpecIssue, validateSpecInput } from "./validateSpec";
import { prepareStackDraft } from "./shared/translator";

export const PlanStackInputSchema = StackDraftSchema;
export type PlanStackInput = StackDraft;
export type PlanStackServiceSpec = DraftServiceSpec;

export interface PlanStackResultOk {
  blocked: false;
  composeYaml: string;
  scaleOverrides: Record<string, number>;
  diff: StackDiff;
  autoGeneratedSecrets: Array<{ service: string; keys: string[] }>;
  configFiles: StagedConfigFile[];
  warnings: string[];
  hash: string;
}

export type PlanStackResultBlocked =
  | { blocked: true; reason: "invalid_spec"; issues: SpecIssue[] }
  | {
      blocked: true;
      reason: "invalid_dependency";
      dependency: ResolveDependencyResult;
    }
  | { blocked: true; reason: "port_conflict"; portCheck: any }
  | { blocked: true; reason: "resource_limit"; issues: ResourceLimitIssue[] }
  | { blocked: true; reason: "db_port_exposed"; issues: DbPortExposureIssue[] }
  | { blocked: true; reason: "unsafe_volume"; issues: VolumeIssue[] }
  | { blocked: true; reason: "undeclared_network"; issues: NetworkIssue[] }
  | { blocked: true; reason: "missing_required_env"; missingByService: Record<string, string[]> }
  | { blocked: true; reason: "missing_config_file"; missingFiles: string[] }
  | { blocked: true; reason: "invalid_yaml"; error: string };

export type PlanStackResult = PlanStackResultOk | PlanStackResultBlocked;

function generatedEnvFilePath(cwd: string, stackName: string, serviceName: string): string {
  return path.join(cwd, ".docker-agent", "secrets", `${stackName}-${serviceName}.env`);
}

function generatedEnvFileRef(stackName: string, serviceName: string): string {
  return `./.docker-agent/secrets/${stackName}-${serviceName}.env`;
}

function resolveEnvFile(cwd: string, refPath: string): string {
  return path.resolve(cwd, refPath);
}

function toServiceSpec(spec: PlanStackServiceSpec): ServiceSpec {
  return spec;
}

export const planStack: Tool<PlanStackInput, PlanStackResult> = {
  name: "plan_stack",
  description:
    "Generate a Docker Compose plan for a stack. The LLM provides the service intents; the tool translates, validates, configures safe ports, resource limits, logging, mounts, auto-generates secrets, and returns YAML.",
  inputSchema: PlanStackInputSchema,
  category: "high-level",
  needsPermission: () => false,
  call: async function* (input, ctx): AsyncGenerator<ToolProgress, PlanStackResult> {
    yield { type: "progress", msg: "Preparing stack draft..." };

    const prep = await prepareStackDraft(input, ctx);
    if (!prep.ok) {
      return {
        blocked: true,
        reason: "invalid_spec",
        issues: (prep.issues as SpecIssue[]) ?? [
          { code: "invalid_spec", path: "services", message: prep.error },
        ],
      };
    }
    const { prepared } = prep;

    yield { type: "progress", msg: "Validating service spec..." };

    const specCheck = await validateSpecInput(
      {
        services: prepared.services,
        ...(input.configFiles ? { configFiles: input.configFiles } : {}),
      },
      ctx,
    );
    for (const warning of specCheck.warnings) yield { type: "progress", msg: warning };
    if (!specCheck.valid) {
      return { blocked: true, reason: "invalid_spec", issues: specCheck.issues };
    }

    const dependency = resolveDependencies(prepared.services);
    if (!dependency.valid) {
      return {
        blocked: true,
        reason: "invalid_dependency",
        dependency,
      };
    }

    const portCheck = await checkPortConflicts(
      input.stackName,
      prepared.services,
      ctx,
    );
    if (!portCheck.ok) {
      return { blocked: true, reason: "port_conflict", portCheck };
    }

    const resourceIssues = checkResourceLimits(prepared.services);
    if (resourceIssues.length > 0) {
      return { blocked: true, reason: "resource_limit", issues: resourceIssues };
    }

    const dbPortIssues = checkDbPortExposure(prepared.services);
    if (dbPortIssues.length > 0) {
      return { blocked: true, reason: "db_port_exposed", issues: dbPortIssues };
    }

    const volumeIssues = checkVolumeSafety(ctx.cwd, prepared.services);
    if (volumeIssues.length > 0) {
      return { blocked: true, reason: "unsafe_volume", issues: volumeIssues };
    }

    const networkIssues = checkNetworkReferences(prepared.services, prepared.networks);
    if (networkIssues.length > 0) {
      return { blocked: true, reason: "undeclared_network", issues: networkIssues };
    }

    const services = structuredClone(prepared.services);
    const stagedConfig = stageConfigFiles(
      ctx.cwd,
      services,
      input.configFiles,
    );
    if (!stagedConfig.ok) {
      return {
        blocked: true,
        reason: "invalid_spec",
        issues: [
          {
            code: "invalid_config_path",
            path: "configFiles",
            message: stagedConfig.error,
          },
        ],
      };
    }

    const autoGeneratedSecrets: Array<{ service: string; keys: string[] }> = [];
    const generatedEnvFileSources: Record<string, EnvFileSource> = {};
    const missingByService: Record<string, string[]> = {};

    for (const [serviceName, spec] of Object.entries(services)) {
      const movedSecrets: Record<string, string> = {};
      const inlineEnvironment = spec.environment ?? {};
      const remainingInlineEnvironment: Record<string, string> = {};

      for (const [key, value] of Object.entries(inlineEnvironment)) {
        if (shouldRedact(key)) {
          movedSecrets[key] = value;
        } else {
          remainingInlineEnvironment[key] = value;
        }
      }

      const serviceEnvFile = spec.env_file ? [...spec.env_file] : [];

      if (Object.keys(movedSecrets).length > 0) {
        const targetPath = generatedEnvFilePath(ctx.cwd, input.stackName, serviceName);
        writeEnvFile(targetPath, { ...readEnvFile(targetPath), ...movedSecrets });
        const targetRef = generatedEnvFileRef(input.stackName, serviceName);
        if (!serviceEnvFile.includes(targetRef)) {
          serviceEnvFile.push(targetRef);
        }
        generatedEnvFileSources[serviceName] = {
          generated: true,
          path: targetRef,
          addedKeys: [
            ...(generatedEnvFileSources[serviceName]?.addedKeys ?? []),
            ...Object.keys(movedSecrets),
          ],
        };
        autoGeneratedSecrets.push({ service: serviceName, keys: Object.keys(movedSecrets) });
      }

      const rule = findRequiredSecrets(spec.image);
      if (rule && rule.required.length > 0) {
        const fromEnvFile: Record<string, string> = {};
        for (const envFilePath of serviceEnvFile) {
          Object.assign(fromEnvFile, readEnvFile(resolveEnvFile(ctx.cwd, envFilePath)));
        }

        const merged = mergeEnv(fromEnvFile, remainingInlineEnvironment);
        const missing = rule.required.filter((key) => merged[key] === undefined);
        const weak = rule.required.filter(
          (key) =>
            merged[key] !== undefined &&
            typeof merged[key] === "string" &&
            isWeakSecretValue(key, merged[key] as string, rule),
        );
        const replaceable = [...missing, ...weak];
        const safeKeys = replaceable.filter((key) => rule.safeDefaults?.[key] !== undefined);
        const unsafeKeys = replaceable.filter((key) => rule.safeDefaults?.[key] === undefined);

        if (unsafeKeys.length > 0) {
          missingByService[serviceName] = unsafeKeys;
        }

        if (safeKeys.length > 0) {
          const targetPath = generatedEnvFilePath(ctx.cwd, input.stackName, serviceName);
          const targetValues = { ...readEnvFile(targetPath) };
          for (const key of safeKeys) {
            const makeDefault = rule.safeDefaults?.[key];
            if (makeDefault) {
              targetValues[key] = makeDefault();
            }
          }
          writeEnvFile(targetPath, targetValues);
          const targetRef = generatedEnvFileRef(input.stackName, serviceName);
          if (!serviceEnvFile.includes(targetRef)) {
            serviceEnvFile.push(targetRef);
          }
          generatedEnvFileSources[serviceName] = {
            generated: true,
            path: targetRef,
            addedKeys: [...(generatedEnvFileSources[serviceName]?.addedKeys ?? []), ...safeKeys],
          };
          autoGeneratedSecrets.push({ service: serviceName, keys: safeKeys });
        }
      }

      const { environment: _environment, env_file: _envFile, ...baseSpec } = spec;
      const nextSpec: PlanStackServiceSpec = { ...baseSpec };
      if (Object.keys(remainingInlineEnvironment).length > 0) {
        nextSpec.environment = remainingInlineEnvironment;
      }

      if (serviceEnvFile.length > 0) {
        nextSpec.env_file = serviceEnvFile;
      }

      services[serviceName] = nextSpec;
    }

    if (Object.keys(missingByService).length > 0) {
      return { blocked: true, reason: "missing_required_env", missingByService };
    }

    const missingConfig = detectMissingConfigFiles(
      services,
      new Set(stagedConfig.staged.map((f) => f.path)),
      ctx.cwd,
    );
    if (missingConfig.length > 0) {
      return { blocked: true, reason: "missing_config_file", missingFiles: missingConfig.map((f) => f.path) };
    }

    yield { type: "progress", msg: "Assembling Compose YAML..." };

    const previous = ctx.stateStore.read(input.stackName);
    const stackServices = Object.fromEntries(
      Object.entries(services).map(([name, spec]) => [name, toServiceSpec(spec)]),
    ) as Record<string, ServiceSpec>;
    const planInput = {
      stackName: input.stackName,
      intent: input.intent,
      services: stackServices,
      networks: prepared.networks,
      volumes: prepared.volumes,
    };
    const { def, scaleOverrides } = buildStackDefinition(planInput, previous, "unknown", "unknown");
    def["x-docker-agent"].envFileSources = {
      ...def["x-docker-agent"].envFileSources,
      ...generatedEnvFileSources,
    };
    const composeYaml = stackToYaml(def);
    const yamlCheck = validateYamlRoundTrip(composeYaml);
    if (!yamlCheck.ok) {
      return {
        blocked: true,
        reason: "invalid_yaml",
        error: yamlCheck.error ?? "unknown YAML error",
      };
    }

    let diff: StackDiff = {
      stackName: input.stackName,
      status: "missing",
      serviceDiffs: [],
    };
    try {
      diff = await detectDrift(input.stackName, ctx.stateStore, ctx.dockerEngine, ctx.cwd);
    } catch {
      // Engine access is best-effort during planning; apply_stack owns deployment.
    }

    return {
      blocked: false,
      composeYaml,
      scaleOverrides,
      diff,
      autoGeneratedSecrets,
      configFiles: stagedConfig.staged,
      warnings: specCheck.warnings,
      hash: prepared.hash,
    };
  },
};
